### ISSUE TITLE
Storage Implementation: kafka

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#10]
A kafka implementation of the storage interface.

**Comment by lbroudoux** [comment]
Hi @EricWittmann and all,

As of today it seems that Kafka storage implementation has only one configuration property that is the bootstrap url or Kafka broker to use.

Do you think of adding more connection properties to support secured broker connection ? Ideally we'd need a way to inject / mount client certificate and CA for accessing remote broker.

Thanks,

**Comment by alesj** [comment]
Anything starting with "registry.streams.topology." will go into Streams config.
And anything starting with "registry.streams.storage-producer." will go into Producer feeding this Streams.

So you can already add anything you like.

**Comment by EricWittmann** [comment]
Possible we need to expose all of those things through Docker so they can be customized in k8s/openshift?

**Comment by EricWittmann** [comment]
@lbroudoux can you comment on whether the configuration options that @alesj described is enough to support secure connections?  I'm not sure how the certs are configured in this use-case.

**Comment by alesj** [comment]
This looks like it's gonna fix the issue:
* https://github.com/quarkusio/quarkus/blob/6c124cfbfe8e596e2d1e1363f91a4b3342394360/docs/src/main/asciidoc/kubernetes-config.adoc

(coming in Quarkus 1.4)

**Comment by alesj** [comment]
Where this already works:
* https://quarkus.io/guides/config#overriding-properties-at-runtime

**Comment by lbroudoux** [comment]
Thanks for all this infos. Will have a look ASAP and let you know. 

Cheers,

**Comment by elakito** [comment]
I have a question when using just docker to start apicurio-registry-kafka and using the environment variable JAVA_OPTS to set those kafka properties.

I can use something like `-e JAVA_OPTIONS='-D%prod.registry.kafka.storage-producer.security.protocol=SASL_PLAINTEXT -D%prod.registry.kafka.storage-producer.sasl.mechanism=PLAIN ...' ` to set those values not containing whitespace but to set a value containing whitespace like e.g., `-D%prod.registry.kafka.storage-producer.sasl.jaas.config` having value `org.apache.kafka.common.security.plain.PlainLoginModule required username=kafkaclient password=kafkaclient-secret`, I tried several quoting and escaping approaches but nothing worked. Is it possible to set such values using this environment variable approach?

**Comment by EricWittmann** [comment]
@alesj do you know the answer to this offhand?

**Comment by antonmry** [comment]
This quoting and escaping approach worked for me in a similar case:

`"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafkaclient\" password=\"kafkaclient-secret\";"`

**Comment by EricWittmann** [comment]
By the way - we'll definitely be looking at making it easier to configure various security configurations like this without relying so heavily on e.g. `JAVA_OPTIONS`.  Next release things should be easier.  In fact, I think Quarkus has a feature to make this easier.

**Comment by elakito** [comment]
I created another ticket #733  to follow up on the question of whether it is possible to pass sasl.jaas.config in the current apicurio-registry-storage-kafka-1.2.3.Final. The approach suggested by @antonmry didn't seem to work for me or maybe I didn't understand how exactly the parameters must be quoted.

**Comment by EricWittmann** [comment]
Thanks for opening the other ticket - that makes sense.  I've pinged the relevant experts. :)
