### ISSUE TITLE
Feature Request: add AsyncAPI Document tab in UI

### ISSUE THREAD

**Issue by mbande** [Apicurio/apicurio-registry#1011]
as there is a (auto generated) Documentation for OpenAPI, please add the same functionality for AsyncAPI.

**Comment by EricWittmann** [comment]
I actually tried adding the AsyncAPI UI when I initially implemented the UI but it wouldn't render.  I don't recall the exact errors, but due to time constraints I had to drop it.  But I agree we should include it if we can!

**Comment by mbande** [comment]
@EricWittmann thank you. meybe the official [html-template](https://github.com/asyncapi/html-template) could help

**Comment by EricWittmann** [comment]
Perhaps - I was trying this:  https://github.com/asyncapi/asyncapi-react

Since our UI is also React it seemed to make sense.

**Comment by tpresthus** [comment]
I was able to use the asyncapi-react component to render documentation in Apicurio, but because of dependencies in asyncapi-react, quite a few node core polyfills were needed.

Would be happy to clean up my attempt and open a pull request, but unsure what Apicurio's policy on these polyfills are?
