### ISSUE TITLE
The SQL Storage implementation doesn't populate all required data for SearchedVersions

### ISSUE THREAD

**Issue by pabloromeo** [Apicurio/apicurio-registry#1015]
When using SQL Storage, fetching the versions in order to populate the UI dropdown fails to map and return the "version" property, causing it to list empty items in the dropdown, which can't be used to change versions since it causes an "undefined" in the URL path.

Uploading a new version causes this:
![image](https://user-images.githubusercontent.com/41338020/99431715-f4885b00-28e9-11eb-89ac-de09b8b71092.png)

I've opened a PR which adds the mapping for the "version" property for SearchedVersions:
https://github.com/Apicurio/apicurio-registry/pull/1014

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1014
