### ISSUE TITLE
Implement configurable content-size limits

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1040]
We should have a configurable limit where we reject content if it exceeds a certain size.  With a default of perhaps 1MB.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1055

**Comment by famartinrh** [comment]
I guess we are going to specify this limit via config property, no?

does it make sense to be able to configure this during runtime? perhaps configurable per tenant?

**Comment by jsenko** [comment]
Definitely runtime configuration. This should become part of the resource management and scheduling of tenants.

**Comment by jsenko** [comment]
I would think of this task in a wider context - not only content size limits, but the overall storage size as well, configurable per tenant. Possibly even limiting request throughput (maybe with some soft/hard limits), so the tenants are isolated as much as possible.

**Comment by jsenko** [comment]
Can we consider requiring users to setup tenant manager if they want to use this functionality (even if they end up using only 1 tenant)?

**Comment by famartinrh** [comment]
> I would think of this task in a wider context - not only content size limits, but the overall storage size as well, configurable per tenant. Possibly even limiting request throughput (maybe with some soft/hard limits), so the tenants are isolated as much as possible.

I completely agree with your point of view, this feature related to the overall tenant management. Regarding all sorts of per-tenant configurations I imagined the tenant-manager providing a "flexible" api to configure things like limits per total num. of artifacts, maybe reqs. per second, content-size,... whatever limit that makes sense... this way the catalog of "registry flavors" can be kept outside as a list of config permutations.

**Comment by EricWittmann** [comment]
Generally agree with you guys on this.  I think this is a longer discussion, but overall we definitely should try to achieve per-tenant limits.  But we need to determine which of the limits we want will be implemented in the application vs. which ones are enforced externally (e.g. via an API management gateway or some other ingress handle).

We should update our existing Limits & Boundaries google doc to reflect our current thinking around multi-tenancy.

**Comment by EricWittmann** [comment]
Closing as stale.
