### ISSUE TITLE
Improve the Kafka+SQL serde implementations

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1059]
Right now we're using Jackson to serialize the Keys and Values into JSON.  Instead we should consider Avro or Protobuf.

**Comment by EricWittmann** [comment]
One interesting thought here is to make this pluggable.  We recently got a question here:  https://github.com/Apicurio/apicurio-registry/issues/1091

That question includes asking whether we use Avro to encode our own Kafka messages.  It seems like we could make the serdes more pluggable than they currently are, so that the community could provide alternative implementations if that were important.  I'm not suggesting we create more than 1, just that we design it so that someone could easily contribute something different.

**Comment by EricWittmann** [comment]
@Apicurio/developers Anyone interested in working on this?  I think it's probably out of scope for the 2.0.0.Final release though.

**Comment by carlesarnal** [comment]
I think we're pretty happy with what we have now for version 3.
