### ISSUE TITLE
Kafka+SQL storage - auto create kafka topic if it is missing

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1075]
When the application starts, the kafkasql storage should check for the existence of a Kafka topic of the appropriate name.  If no topic exists, we should create one with appropriate default settings.  This includes some (small?) number of partitions and log-compaction enabled.

**Comment by EricWittmann** [comment]
Hey @alesj - how difficult would this be to implement?  Does the Streams impl auto-create the topics in Kafka, or assume that they are already there?

@jsenko Does the operator create the topics for the Streams impl?

**Comment by alesj** [comment]
> how difficult would this be to implement? 

Pretty simple with Kafka's AdminClient.

> Does the Streams impl auto-create the topics in Kafka, or assume that they are already there?

No, afaik it doesn't. And it fails if the required topics are not there.
At least that's the default, afaik. Perhaps there is some config that auto creates it ...

**Comment by EricWittmann** [comment]
Any chance you could put together some code that would (optionally) auto-create the topics for the Streams impl?  Would be a nice to have feature IMO.

**Comment by alesj** [comment]
We need something similar to this:
* https://github.com/alesj/strimzi-kafka-operator/blob/ts_streams/topic-operator/src/main/java/io/strimzi/operator/topic/KafkaStreamsTopicStoreService.java#L127

I'll prepare some PR in the next days ...
