### ISSUE TITLE
Confluent compat mode behavior difference on PUT /config

### ISSUE THREAD

**Issue by lbroudoux** [Apicurio/apicurio-registry#1097]
Hi,

I'm realizing tests of Apicurio Registry using https://kafkajs.github.io/confluent-schema-registry/ by replacing Confluent registry with Apicurio one and there's a difference that makes my producer fails.

At startup, Kafkajs SchemaRegistry lib is looking for configuration of subject and - even if config does not exists yet - it tries to update its `compatibility` flag. Curiously the Confluent registry does not raise any error and create the subject config when updating it.

I have captured the following API calls to easily reproduce it. I have used Confluent Registry `5.4.3`:

```sh
$ curl localhost:8888/config/users-value
< HTTP/1.1 404 Not Found
{"error_code":40401,"message":"Subject not found."}

$ curl localhost:8888/config/users-value -XPUT -H 'Content-type: application/json' -d '{"compatibility":"NONE"}'
< HTTP/1.1 200 OK
{"compatibility":"NONE"}

$ curl localhost:8888/config/users-value
< HTTP/1.1 200 OK
{"compatibility":"NONE"}
```

Now using the same API calls on Apicurio Registry `1.3.2.Final`:

```sh
$ curl localhost:8888/api/ccompat/config/users-value
< HTTP/1.1 404 Not Found
{"message":"No artifact with ID 'users-value' was found.","error_code":404}

$ curl localhost:8888/api/ccompat/config/users-value -XPUT -H 'Content-type: application/json' -d '{"compatibility":"NONE"}'
< HTTP/1.1 404 Not Found
{"message":"No artifact with ID 'users-value' was found.","error_code":404}

$ curl localhost:8888/api/ccompat/config/users-value
< HTTP/1.1 404 Not Found
{"message":"No artifact with ID 'users-value' was found.","error_code":404}
```

Behavior is different and even if Confluent one is weird then fixing it in Apicurio would break existing Kafka lib or clients ...

**Comment by EricWittmann** [comment]
Oh my this is unfortunate.  So the summary here is that in Confluent you can configure the compatibility for a subject before actually creating the subject.

Our goal for the `ccompat` API is certainly to be compatible with the Confluent API as best we can.  In this case, our internal data model will make it difficult to mimic the Confluent behavior.  We don't currently have a way to configure rules for an Artifact that does not exist.

Is this a blocker for you?

**Comment by lbroudoux** [comment]
Thanks @EricWittmann !

Actually, this is not a blocker as I just use Kafkajs SchemaRegistry lib for tests.

Just found it was better to spot this difference.

**Comment by EricWittmann** [comment]
OK great - I very much appreciate the feedback.  We definitely want to know whenever our functionality differs from the Confluent Schema Registry, so anytime you find something like this it's super helpful to report it.  Most of the time it's something we can easily fix, but this one is a tougher nut to crack.  :)

I'll leave this open for discussion though.
