### ISSUE TITLE
Ensure authentication failure to API is properly formatted

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1126]
Let's see if we can customize the output (http response) we send when the API is accessed without proper AuthN/Z.  Often times the default behavior is a 403 response with some HTML payload.  Because we are protecting a REST API, let's make sure we customize the response to return a JSON error in the standard Apicurio Registry API error format.

**Comment by carlesarnal** [comment]
After a quick look, there is good and bad news. This doesn't seem possible right now, but it seems that it will be possible in a near future thanks to [this](https://github.com/quarkusio/quarkus/issues/8570).

**Comment by EricWittmann** [comment]
OK great can you please monitor that and then apply it to registry when appropriate?

**Comment by carlesarnal** [comment]
This is possible right now using [this](https://quarkus.io/guides/security-built-in-authentication#how-to-customize-authentication-exception-responses). This change has been added in Quarkus 2.x.

**Comment by carlesarnal** [comment]
Sure, I'll add this.

**Comment by carlesarnal** [comment]
This is blocked until we move to Quarkus 2.7.x and is tracked on the mas-sr project, so I'm closing this one.
