### ISSUE TITLE
Prepare auth support for multitenancy

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#1140]
Since we're going to introduce multitenancy, let's adapt the authentication part so it's capable of support it. For more information on how to achieve it see [this](https://quarkus.io/guides/security-openid-connect-multitenancy).

**Comment by EricWittmann** [comment]
@carlesarnal This is done, yes?

**Comment by carlesarnal** [comment]
Done, yes.

**Comment by carlesarnal** [comment]
Done, yes.
