### ISSUE TITLE
Create Version info endpoint to the REST API

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#1142]
Provide an API like `/api/admin/version` or whatever other path... that returns the version of the registry.
Then this endpoint should be used in the rest-client to determine if the client support the server...

Later on when we start introducing breaking changes to our REST API we may want to make our API versioned , i.e `/api/v2/artifacts`, but still the version endpoint would be useful for clients to determine what APIs the client can use

**Comment by famartinrh** [comment]
All this "smart client" features will be useful when we start to provide an official quarkus extension and we are forced to follow the quarkus release cadence... Imagine a quarkus app with a version X of the client and we ship a new version of the registry of version Y , our registry Y have to be compatible with client X, at least during the period of time the quarkus version cannot be updated with the newer version of the client.... We must ensure the client X can talk to registry Y.
so it will be nice if we ensure our rest-client is resilient and old versions of the client can talk to newer versions of the registry.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1316
