### ISSUE TITLE
Error fetching JS libraries when running in a closed network

### ISSUE THREAD

**Issue by mdhender** [Apicurio/apicurio-registry#1151]
I am running 1.3.2.Final.

Is there a way to bundle JS libraries during the build? My build environment has access to the internet, but the deploy environment has no connection to the internet. Running calls to CDN from the browser will fail there. For example:

> react-dom.production.min.js:209 Error: Error downloading http://xxxx/openapi?format=JSON 
> Failed to fetch
>     at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28049
>     at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:36080

**Comment by EricWittmann** [comment]
I agree that the ReDoc bundle should be bundled and deployed with the app rather than point to a CDN.  The current approach was just laziness I think.
