### ISSUE TITLE
Add bearer and basic working together support

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#1154]
Now that we have bearer and basic auth support let's introduce some other features. For some scenarios, it will be ideal to have both bearer and basic auth support in the same deployment. This can be achieved by injecting the `OidcAuthenticationMechanism` into a custom `HttpAuthenticationMechanism`. If the provided auth is OIDC based, then fall back to the `OidcAuthenticationMechanism`, if not, we'll need to write some code in order to contact Keycloak and authenticate the request.

**Comment by tszappanos** [comment]
Please specify this functionality. Does this mean that if I set up OIDC auth with keycloak in the registry, it will be possible to call the Registry API  with basic auth as well? So far it is not possible? What are / will I be able to call in the maven plugin, avro serde component (registry rest client)? Thank you for your answer.

**Comment by carlesarnal** [comment]
Hi @tszappanos, 

> Please specify this functionality. Does this mean that if I set up OIDC auth with keycloak in the registry, it will be possible to call the Registry API with basic auth as well?
Yes, that's exactly the purpose of this feature.

> So far it is not possible? What are / will I be able to call in the maven plugin, avro serde component (registry rest client)? Thank you for your answer.

This is not possible right now since it's not possible in Quarkus to use multiple auth providers at the same time. It is possible to configure the registry to use basic (quarkus standard) OR bearer (oidc based) but it's not possible to configure them together. In response to the maven plugin, avro etc, you'll need to add some configuration properties for the client to be able to make secured requests to the registry.

**Comment by EricWittmann** [comment]
@carlesarnal Do we need another task to configure the maven plugin with auth properties so that the maven plugin will work when auth is enabled?  If yes, can you add a GH issue for that and add it to the backlog?

**Comment by carlesarnal** [comment]
> @carlesarnal Do we need another task to configure the maven plugin with auth properties so that the maven plugin will work when auth is enabled? If yes, can you add a GH issue for that and add it to the backlog?

Yes, we need another task for configuring client credentials in the maven plugin. I'll add it.
