### ISSUE TITLE
Encapsulate dependency to com.worldturner.medeia:medeia-validator-jackson

### ISSUE THREAD

**Issue by viecili** [Apicurio/apicurio-registry#1159]
As best practice and adherence to SOLID principles, the dependency to `com.worldturner` classes should not be exposed in the Deserializer API and encapsulated. The project `com.worldturner.medeia:medeia-validator-jackson` doesn't seem to be actively maintained too.

**Comment by EricWittmann** [comment]
Are you aware of a JSON Schema validation library in Java that is actively maintained?  I haven't looked in awhile, so would be very happy for a recommendation.

**Comment by viecili** [comment]
They have a list on https://json-schema.org/implementations.html#validator-java 

I don't have experience with any one listed there, but https://github.com/eclipse-vertx/vertx-json-schema is early stage and looks promising since it is based on Vert.x , some of the other ones have a lot more contributors.

**Comment by carlesarnal** [comment]
Closing as we don't use this dependency anymore.
