### ISSUE TITLE
Relocate or remove KafkaRetryTest

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#1187]
I noticed the `KafkaRetryTest` in `utils/kafka` module is waiting up to one minute before it throws `TestAbortedException` to skip the test...
I wonder if we could relocate the test to the `storage/streams` or `storage/kafkasql` modules to ensure it is triggered only when it's expected to be executed, otherwise we are making the rest of the builds much slower.

looks like @alesj wrote that test, what do you think?

**Comment by EricWittmann** [comment]
Can we re-implement this test in your integration test suite?

**Comment by alesj** [comment]
Well, it tests that Kafka util lib ...
(that lib is used in Strimzi as well, etc)

Perhaps just a better / quicker mechanism to see that there is no Kafka running ...
