### ISSUE TITLE
API date-time return value wrong

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry#1215]
In the openapi documentation it's documented that you return a `date-time`. This is the case for meta data `modifiedOn` as an example at https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/assets-attachments/registry-rest-api.htm#operation/getArtifactMetaDataByGlobalId.

As you can guess now you return a "integer" timestamp which cases my generated client in go to fail as it's expecting a valid date-time string format as seen at https://swagger.io/docs/specification/data-models/data-types/

**Comment by famartinrh** [comment]
This problem was addressed in this PR #1132 and the fix will be available in the next release.

btw, just for curiosity, do you have a link to your golang client? :) it could be useful for the project

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1132

**Comment by dweber019** [comment]
Yes sure https://github.com/dweber019/apicurio-registry-artifact-operator. As you can read in the README I generate the client form your openApi.

Our usecase is to do gitOps with artifacts in our firm. I first wanted to fork the apicurio-registry-operator but it gave me a hard time installing, as the operator sdk is some versions ago and I'm new to the operator sdk.

**Comment by EricWittmann** [comment]
This looks really cool, @dweber019  - any interest in contributing it to the Apicurio community?

**Comment by dweber019** [comment]
Thanks, yes sure. How could I do this?

**Comment by EricWittmann** [comment]
@Apicurio/developers What do you guys think?  Should we keep this as a separate repository?  Or incorporate the functionality into the existing operator or operator repo?

**Comment by carlesarnal** [comment]
I have a slight preference for the separate repo.

**Comment by dweber019** [comment]
Maybe it would make sense to add an auto discover mode for the registry operator by a kube selector to get the service.
What do you think?

**Comment by jsenko** [comment]
I would prefer to use a separate repo. We could use the Apicurio Registry Operator to deploy the Artifact Operator as an optional dependency, and provide it with configuration automatically.

**Comment by EricWittmann** [comment]
@jsenko that sounds reasonable to me - what do you think @dweber019 ?

**Comment by famartinrh** [comment]
I would prefer to keep it in a separated repo, but at the same time have some integration between the two operators.

Said so jakub's suggestion sounds reasonable, however it may be preferrable to make the new "artifact synchronizer" operator dependent in the our original operator, instead of making it the other way around. This way our main operator (to deploy the registry) provides the API (ApicurioRegistry CR) in which the "artifact synchronizer" depends on.

wdyt?

**Comment by jsenko** [comment]
Could you explain more how would that dependency work? I imagined something simple like have a property in the `ApicurioRegistry` CR to instruct the operator do deploy and configure Artifact Operator which then would do it's own thing.

**Comment by jsenko** [comment]
You envision the Artifact operator would watch and act on `ApicurioRegistry` CR?

**Comment by famartinrh** [comment]
My proposal is the Artifact Operator would be configured with it's own CR, that CR will have a field with the name of an ApicurioRegistry CR that will have to exist.

**Comment by jsenko** [comment]
I see, sounds good. This actually results in a more decoupled deployment, so we could start there, and optionally add more integration as we go.

**Comment by EricWittmann** [comment]
I'll leave the creation of the repository and whatnot to you guys.  I think you have sufficient privs within the Apicurio GH org to do that.  If not, please let me know.  Once the repo is created, let @dweber019 know so they can submit a PR!  :) :) 

Thanks everyone.

**Comment by dweber019** [comment]
sounds good to me ;)

**Comment by jsenko** [comment]
hi @dweber019 Please create a PR to https://github.com/Apicurio/apicurio-registry-content-sync-operator and we will merge it. Thanks again for contributing!

**Comment by dweber019** [comment]
Perfect, will do it this weekend ;)

**Comment by dweber019** [comment]
Pull request is open https://github.com/Apicurio/apicurio-registry-content-sync-operator/pull/1
