### ISSUE TITLE
Re-organize APIs for consistency and future-proofing

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1238]
We have multiple APIs we support right now, including:

* Apicurio Registry core API
* Confluent Schema Registry API
* IBM Schema Registry API
* CNCF Schema Registry API

We should organize these as follows:

* `/apis/registry/v1` and `/apis/registry/v2`
* `/apis/ccompat/v6`
* `/apis/icompat/v1`  (confirm version # with ibm)
* `/apis/cncf/v0`

**Comment by gunnarmorling** [comment]
As dicussed in our call, it'd be worth considering whether the old V1 URL path can be kept (deprecated), as that'd help a lot with upgrading procedures.

**Comment by EricWittmann** [comment]
Agreed.  That's captured here:  https://github.com/Apicurio/apicurio-registry/issues/1250
