### ISSUE TITLE
Implementation of BACKWARD_TRANSITIVE, FORWARD_TRANSITIVE might be incorrect

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1239]
My understanding of transitive compatibility modes (BACKWARD_TRANSITIVE, FORWARD_TRANSITIVE) is that schema registry ensures that the updated schema version is compatible with all the versions in the registry. 

However, the code in [JsonSchemaCompatibilityChecker](https://github.com/Apicurio/apicurio-registry/blob/cef3931f3c1cd681de1d23bad9126880b2cd1823/app/src/main/java/io/apicurio/registry/rules/compatibility/JsonSchemaCompatibilityChecker.java#L86) checks compatibility between old versions. 

Current behavior:
```
isCompatible(latest, latest-1) && isCompatible(latest - 1, latest - 2) && isCompatible(latest - 2, latest - 3) ...
```
Expected behavior:
```
isCompatible(latest, latest-1) && isCompatible(latest , latest - 2) && isCompatible(latest, latest - 3) ...
```

Is my understanding correct?

**Comment by EricWittmann** [comment]
Thoughts @jsenko ?

**Comment by jsenko** [comment]
The standard definition of transitivity is `A <c B and B <c C implies A <c C`. You are right, we are checking the left side but not the right side.

**Comment by jsenko** [comment]
I found other issues in the current master, I'm working on a PR.

**Comment by EricWittmann** [comment]
I recommend you do any work against the `feat/artifact-groups` branch.
