### ISSUE TITLE
Deprecate (but keep for now) the /api/ v1 endpoint 

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1250]
We are re-organizing the API endpoints.  As part of that the old `/api/` endpoint will be relocated to `/apis/registry/v1`.  Let's keep the old endpoint around and either redirect or rewrite inbound requests to dispatch them to the new endpoint.  This should hopefully make upgrades easier for anyone using the Registry.  They can upgrade the server without consumers breaking.  Those consumers can then be upgraded later.

**Comment by famartinrh** [comment]
I can implement the filter to rewrite `/api/` requests to `/apis/registry/v1/`

**Comment by EricWittmann** [comment]
This has been implemented.  Thanks @famartinrh
