### ISSUE TITLE
Operator not visible after installation is done in Openshift 4 Cluster

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-registry#1251]
Hello folks,

Our cluster admin has installed Operator using https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/getting-started/assembly-installing-registry-openshift.html into Openshift 4

Our development team can't see Operator in their dedicated project(s). Can you please support us? What should we ask our operations team to do in order to enable Operator for particular project(s)?

Thanks

**Comment by famartinrh** [comment]
If I'm not mistaken, the operator version we have available in operator hub (version `v0.0.4-v1.3.2.final`) does not support multi-namespace installations, and so operator is only available in the namespace it was installed (`my-project` in the case of the example used in the docs)

You will have to install the operator in every namespace it is required.

For our next release the operator will have multi-namespace support and so it will be possible to install it only once.

**Comment by jsenko** [comment]
That's right, the multi-namespace support is implemented and will be available in the next release.

**Comment by tillias** [comment]
Thanks folks, this was really helpful. We will ask our cluster admin to install it into concrete project than.
