### ISSUE TITLE
apicurio/apicurio-registry-sql image in docker hub seems to be broken

### ISSUE THREAD

**Issue by ChloePont** [Apicurio/apicurio-registry#1300]
I tried running the latest-snapshot and got the following error:
```
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/opt/agent-bond/agent-bond.jar=jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/apicurio-registry-storage-sql-2.0.0-SNAPSHOT-runner.jar

Exception in thread "main" java.lang.UnsupportedClassVersionError: io/apicurio/registry/services/RegistryConfigSource has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by carlesarnal** [comment]
Hi @ChloePont, that error states that you're using a version of java (52 - java 8) lower than the one needed (55 - java 11). Latest-snapshot is being compiled using java 11 so you'll need to upgrade your java version.

**Comment by jsenko** [comment]
Hi, we are aware of the problem and updating our Docker files to use JDK 11. @famartinrh correct?

**Comment by famartinrh** [comment]
yes exactly, we just fixed that today, there should be a working image published as of today

**Comment by ChloePont** [comment]
Nice - thanks for letting me know! 
And I assume you're aware but just in case: the [build to upgrade to jdk 11](https://github.com/Apicurio/apicurio-registry/pull/1299 ) failed earlier today.

**Comment by famartinrh** [comment]
yes yes I'm aware, we are working on the fix now
