### ISSUE TITLE
Make registry UI work with multitenancy + authentication

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry#1313]
In multitenancy scenarios the auth details are different for every tenant, the UI uses the servlet `ConfigJsServlet` to get that information. That servlet have to be modified to use the tenant info from the context to return specific config file for every tenant.
Look at `CustomTenantConfigResolver` for ideas on how to get the tenant info.

**Comment by EricWittmann** [comment]
Note that we have temporarily disabled the UI when in multi-tenant mode.  Until we can figure out a good way to automatically support a multi-tenant enabled UI.

**Comment by EricWittmann** [comment]
A new UI has been created for MT scenarios:  https://github.com/apicurio/apicurio-registry-mt-ui

**Comment by carlesarnal** [comment]
Closing this as the new UI structure is working fine for us in Operate First.
