### ISSUE TITLE
JSON compatibility check for exclusive maximum/minimum

### ISSUE THREAD

**Issue by hhkkxxx133** [Apicurio/apicurio-registry#1318]
Hello, 

We were testing the JSON compatibility rule. For the test case, I believe they are essentially the same as both are requiring number > 10. Therefore, they should be backward, forward and full compatible, right? But the result turns out to be incompatible for all 3 settings. 
```
"original": {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "number",
    "minimum": 10,
    "exclusiveMinimum": true
},
"updated": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "number",
    "exclusiveMinimum": 10
}
```

Same applies for ExclusiveMaximum:
```
"original": {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "number",
    "maximum": 10,
    "exclusiveMaximum": true
},
"updated": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "number",
    "exclusiveMaximum": 10
}
```

Let me know what do you think.

**Comment by jsenko** [comment]
Hi, yes this looks correct - it should be full compatible.

**Comment by EricWittmann** [comment]
Marking as a bug - correct, @jsenko ?
