### ISSUE TITLE
JSON compatibility check for "contains" keyword in "array" type

### ISSUE THREAD

**Issue by hhkkxxx133** [Apicurio/apicurio-registry#1319]
Hello,

We are testing the JSON compatibility rule. For the test case below, I believe it is backward compatible right? The original schema asks for an all-integer list. And the updated schema indicates an array that contains at least a number. 
```
"original": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
         "type": "integer"
     }
},
"updated": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "contains": {
        "type": "number"
    }
}
```

I also tested with both same type. Not backward compatible. 
```
"original": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
         "type": "number"
     }
},
"updated": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "contains": {
        "type": "number"
    }
}
```

**Comment by jsenko** [comment]
Hi, yes this looks like it should be compatible, but the checker is not detailed enougt to spot that. The only counterexample I can think of is that the original should accept an empty array, but should the `updated` accept an empty array as well, or reject because there MUST be a number present?

**Comment by jsenko** [comment]
It looks like the first would indeed accept an empty array and the second would not - https://json-schema.org/understanding-json-schema/reference/array.html#list-validation . WDYT @hhkkxxx133 ?

**Comment by hhkkxxx133** [comment]
I agree with you. This should be incompatible then.
