### ISSUE TITLE
Allow String as Version ID

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-registry#1324]
Please allow specifying versionID as a String. We would like to use semantic versioning in JsonSchema like https://gist.github.com/mattyod/3608613#gistcomment-2889451:

"$id": "http://yourdomain.org/schemas/v0.0.1/example.schema.json"
"$id": "http://yourdomain.org/schemas/v0.0.2/example.schema.json"
"$id": "http://yourdomain.org/schemas/v0.1.0/example.schema.json"

**Comment by tillias** [comment]
Hi @EricWittmann thanks for the fast response. Is it possible to provide some API call to get particular version of artifact by it's metadata? As a temp. solution (without need to modify storage) we can associate some metadata like "sem-version": "v1.0.1" with particular version of artifact. This is already implemented I guess.

What would be nice is to have ability calling like http://yourdomain/api/artifacts/some-json-schema-id/metadata/sem-ver/v1.0.1 or something like this. This way we already can use it inside our $id

**Comment by EricWittmann** [comment]
Well, I think that the changes to the API to support user-provided versions is really the solution here.  I don't think it makes sense to do something else.  The new v2 API already supports providing an optional version # when creating an artifact (or when adding a new version of an artifact).  So it's just a matter of actually implementing that aspect of the API.  I think it will be exactly what you're looking for.  The API to access the content would be:

`/apis/registry/v2/groups/{groupId}/artifacts/{artifactId}/versions/{versionId}`

And the `versionId` will be (optionally) a string provided by the user when creating the version, so could be semver compatible.

This is the basis for other semver related features we have planned in the future, esp. around compatibility.

**Comment by EricWittmann** [comment]
If the version is not provided by the user when creating the content, then the server will generate a version # just like it does now.

**Comment by famartinrh** [comment]
I agree it's important to implement this feature, we already have the client and the api accepting strings, now is up to modify everything in the internals :) 

just a minor note. I guess if an artifact is created providing a string version, all next versions for that artifacts will have to provide a string version as well. I don't think we may want the user to first provide "1.0.0" and for next versions the registry figure out what new version to use. At least for the first iteration of this functionality. That will make things much harder to implement and we don't have much time between CR1 and the Final release.

**Comment by EricWittmann** [comment]
Finally have an update on this.  We've implemented this feature in 2.0.  Now whenever an artifact or artifact version is created, you can specify/override the version by sending the `X-Registry-Version` HTTP request header.  The value can be a string.  From then on, you can use that version value when executing any operation that requires it.
