### ISSUE TITLE
Implement helm-chart or operator

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-registry#1325]
Hello folks, just another idea -> allow using helm charts or even better operators. There is already operator for apicurio-studio and microcks, why not following the same path for registry?

Just make sure that operator doesn't require cluster admin role, cause in many organizations developers don't have it ;-)

Thanks for your hard work!

**Comment by EricWittmann** [comment]
@tillias It turns out that registry already has an operator!  :) 

https://github.com/Apicurio/apicurio-registry-operator/
https://operatorhub.io/operator/apicurio-registry

**Comment by EricWittmann** [comment]
@jsenko is working on upgrading the operator to support our forthcoming 2.0.0 release, and this new version of the operator will offer multi-namespace support.  And I don't think it will require cluster admin.  Can you confirm @jsenko ?

**Comment by tillias** [comment]
My bad folks, apicurio-studio was meant. Moving ticket

**Comment by EricWittmann** [comment]
Ah yes - Studio **definitely** needs an operator.  You've got me there. :)
