### ISSUE TITLE
Cannot deserialize LocalDate from Integer in Avro format by Apicurio deserializer

### ISSUE THREAD

**Issue by mzaikin** [Apicurio/apicurio-registry#1327]
My setup:
1. Strimzi Kafka
2. Apicurio Schema Registry
3. Use Avro format to produce and consume

All works fine with simple types (`String`, `long`)  until I try to use `LocalDate`.

Here is my Avro schema in Apicurio:

```
{
  "type" : "record",
  "name" : "AvroMessageBean",
  "namespace" : "com.company",
  "fields" : [ {
    "name" : "message",
    "type" : "string"
  }, {
    "name" : "time",
    "type" : "long"
  }, {        
    "name": "weekEndingDate",
    "type": {
        "type": "int",
        "logicalType": "date"
    }
  }]
}
```

In my consumer I receive `GenericRecord` with `value` like this:

```
{"message": "Hello (0)!", "time": 1615449454839, "weekEndingDate": 18697}
```

The relevant consumer code fragment is like this:
```
import io.apicurio.registry.utils.serde.AbstractKafkaSerDe;
import io.apicurio.registry.utils.serde.AvroKafkaDeserializer;
...
// set deserializer
props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, LongDeserializer.class.getName());
props.putIfAbsent(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, AvroKafkaDeserializer.class.getName());
props.putIfAbsent(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM, REGISTRY_URL);

KafkaConsumer<Long, AvroMessageBean> consumer = new KafkaConsumer<>(props);

...
// consume
while (true) {
    ConsumerRecords<Long, AvroMessageBean> records = consumer.poll(Duration.of(1L, ChronoUnit.SECONDS));
    for (ConsumerRecord<Long, AvroMessageBean> record : records) {
        GenericRecord gRec = record.value();
        AvroMessageBean aMsg = (AvroMessageBean) SpecificData.get().deepCopy(AvroMessageBean.SCHEMA$, gRec);
        System.out.println("Consumed a message: " + aMsg.getMessage() + " @ " + new Date(aMsg.getTime()));
    }
    consumer.commitSync();
}
```

The exception at runtime:
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.time.LocalDate
	at com.ibm.AvroMessageBean.put(AvroMessageBean.java:131)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:818)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:841)
	at org.apache.avro.generic.GenericData.deepCopyRaw(GenericData.java:1286)
	at org.apache.avro.generic.GenericData.deepCopy(GenericData.java:1223)
	at com.ibm.AvroMessageBeanConsumer.main(AvroMessageBeanConsumer.java:75)
```

This is the content of `AvroMessageBean.SCHEMA$`:

```
{"type":"record","name":"AvroMessageBean","namespace":"com.company","fields":[{"name":"message","type":"string"},{"name":"time","type":"long"},{"name":"weekEndingDate","type":{"type":"int","logicalType":"date"}}]}

```

Wondering why the `logicalType` is ignored?

**Comment by EricWittmann** [comment]
This seems like an Avro question to me - perhaps it's better to seek help in that forum.  I don't have any particular insight into this.  Any ideas @Apicurio/developers?  @alesj ?

**Comment by mzaikin** [comment]
Thanks @EricWittmann for looking at this. I really not sure what causes the problem. This code if I replace `AvroKafkaDeserializer` with `KafkaAvroDeserializer` (Confluent matching class) and Confluent schema registry -- works fine. So I wonder why one deserializer handles this and another not fully recognizes the `logicalType` ?

What puzzles me, with Confluent (hopefully this name allowed to write here 8-) ) the problem of cast resolved by a proprietary flag `KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG` set true :
```
props.put(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, true);
``` 
allows to bypass the `SpecificData.get().deepCopy(AvroMessageBean.SCHEMA$, gRec);` step.

Not sure why it does not work with Apicurio in my setup. First, I need to assign to `GenericRecord`:
```
GenericRecord gRec = record.value();
```
and then try to convert manually:
```
AvroMessageBean aMsg = (AvroMessageBean) SpecificData.get().deepCopy(AvroMessageBean.SCHEMA$, gRec);
```
and fail (if I not use `LocaDate` -- I succeed).

I even tried to set explicitly logical type converters, but no luck:
```
SpecificData.get().addLogicalTypeConversion(new TimeConversions.TimestampConversion());
```

**Comment by famartinrh** [comment]
we have a similar property in our serdes like the one you mentioned , https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/getting-started/assembly-using-kafka-client-serdes.html#registry-serdes-types-avro-registry
```
apicurio.registry.use-specific-avro-reader
```
@mzaikin you may want to try that
