### ISSUE TITLE
Integration with Keycloak

### ISSUE THREAD

**Issue by amalkurup89** [Apicurio/apicurio-registry#1353]
Is Apicurio registry integrated with Keycloak

**Comment by jsenko** [comment]
Yes, but it's disabled by default, see https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/resources/application.properties#L105
Could you provide more details about your issue?
CC @carlesarnal

**Comment by amalkurup89** [comment]
@jsenko Just like apicurio studio, I need a login functionality in Apicurio registry and logged in user should be entitled to view artifacts uploaded or shared with him, on registry UI

**Comment by carlesarnal** [comment]
hi @amalkurup89, you'll need to provide your own Keycloak server with a Realm properly configured with users matching the roles defined in the `application.properties` that Jakub shared with you. Let me know if you need help.

**Comment by carlesarnal** [comment]
Hi @amalkurup89, [here](https://gist.github.com/carlesarnal/04d3febad33073007c53696ffa2fe87c)'s a realm for you to import into Keycloak. 

The appropriate values for that realm are:

- name: AUTH_ENABLED
  value: 'true'
- name: KEYCLOAK_URL
  value: {KEYCLOAK_SERVER_URL}/auth
- name: KEYCLOAK_REALM
  value: registry
- name: KEYCLOAK_API_CLIENT_ID
  value: registry-api
- name: KEYCLOAK_UI_CLIENT_ID
  value: registry-ui

Let me know if you need anything else.

**Comment by EricWittmann** [comment]
@amalkurup89 What version of Apicurio Registry are you using?  Authentication via KC is new to version 2.0.x, which is just in the process of being released this month.

You would need to use e.g. 2.0.0.RC1 for this to work.

**Comment by tillias** [comment]
Is there any ticket to subscribe to? We would be also very interested in this feature

**Comment by EricWittmann** [comment]
Auth via Keycloak is part of the 2.0.x release.

**Comment by carlesarnal** [comment]
Closing this, if anyone has any objections, please reopen.
