### ISSUE TITLE
General questions about schema registry

### ISSUE THREAD

**Issue by SgtMate** [Apicurio/apicurio-registry#1360]
Hello,
I’m a student in a dual course of study at CLAAS, an agricultural machine manufacturer in Germany.
At the moment I’m working on a Kaka environment for data streaming on Kubernetes, for my first project. 
I looked into the Confluent solution but would like to deploy a more open and independent solution with Strimzi.
On GitHub, the Strimzi community recommended your Schema Registry Project, so I try to work out a solution not including the Confluent platform.

When looking into the project I tried to compare it to the Confluent solution (the Community edition) to find probable issues/differences in the feature set of both solutions.
I’ve seen that you’re working on the version 2.0 but the documentation on your website is at the time of writing not yet updated to this version.
After comparing the key points, I came across some points I didn’t find an answer to and hope you can help me with that.

These are my Questions:

Is there a possible solution to use Apicurio schema registry without using OpenShift and to what extend is OpenShift mandatory?

Confluent has the ability to use JMX for monitoring, is it possible to monitor Apicurio schema registry and how can I do it?

Can I use multiple registry nodes for load balancing (as it works at Confluents solution) or how can I load balance the systems in another way?

How does encryption, authorisation and authentication work? Is there a good security solution?

I’m happy for any answer I get and hope you’re doing well.

**Comment by EricWittmann** [comment]
Hi @SgtMate - thanks for the questions.  I'll do my best to answer inline below:

> I’ve seen that you’re working on the version 2.0 but the documentation on your website is at the time of writing not yet updated to this version.

Yes - we're working on updating the documentation prior to releasing 2.0.0.Final.  We're hoping for the end of this month or early April.

> Is there a possible solution to use Apicurio schema registry without using OpenShift and to what extend is OpenShift mandatory?

OpenShift is not mandatory.  You can run Apicurio Registry using any of these deployment strategies:

* OpenShift
* Kubernetes
* Docker
* Bare metal (download and run the application)

> Confluent has the ability to use JMX for monitoring, is it possible to monitor Apicurio schema registry and how can I do it?

We don't have any specific JMX monitoring in Apicurio Registry.  You could probably use JMX (might require a custom build) but you will only get basic JVM data.

> Can I use multiple registry nodes for load balancing (as it works at Confluents solution) or how can I load balance the systems in another way?

Yes, Apicurio Registry can be run in a cluster.  Version 2.0 will have two persistence options:

* Postgresql database  (apicurio-registry-sql docker image)
* Kafka  (apicurio-registry-kafkasql docker image)

To run in a cluster, you would need to start up multiple instances of the application (this is easy in OpenShift and kubernetes, but obviously you'll have to do that manually in some way if you use docker or bare metal) and configure all instances to point to the same Database or Kafka cluster (depending on which storage option you choose).  Then you can load balance across all instances in whatever way you choose.

> How does encryption, authorisation and authentication work? Is there a good security solution?

We integrate with Keycloak for authentication.  We dont' currently have any authorization features, although it is likely that very soon we will support optional owner-only authorization (meaning everyone can *see* all artifacts but only the owner/creator can make changes to an artifact).  Looking further out in the future, we will likely be implementing proper authorization support at either the artifact or group granularity (or perhaps both).  We do not yet have specific plans for what that will look like.

**Comment by SgtMate** [comment]
@EricWittmann Thank you for the quick response and the good explanation. That helped me a lot.
