### ISSUE TITLE
Use RFC7807 format for errors

### ISSUE THREAD

**Issue by ioggstream** [Apicurio/apicurio-registry#1361]
I suggest to use RFC7807 aka problem+json format for errors, eg.

```
{
 "status": 404,
 "detail": "No artifact with id 'Topic-1/Inbound' could be found."
}
```

This format simplifies error processing and avoid confusing HTTP status codes (eg. 404) with specific error codes or messages at the application layer that enable extending error reporting in a backward-compatible way.

a more comprehensive example of problem+json

```

{           // standard part
            "status": 403,
             "type": "https://example.com/probs/out-of-credit",
             "title": "You do not have enough credit.",
             "detail": "Your current balance is 30, but that costs 50.",

            // optional, customized part
             "instance": "/account/12345/msgs/abc",
             "balance": 30,
             "accounts": ["/account/12345",
                          "/account/67890"]
            }

```

**Comment by EricWittmann** [comment]
Interesting, thanks @ioggstream 

@Apicurio/developers what do you think?

**Comment by carlesarnal** [comment]
+1, this seems reasonable, I like it.

**Comment by EricWittmann** [comment]
It's probably too late to do this for 2.0.0 - so we'll need to think about the impact wrt client compatibility.

**Comment by ioggstream** [comment]
I understand. The custom part of rfc7807 allows to add the new properties along the old ones, as there are no conflicting names. In future we could deprecate the old ones or use them to provide further information.
In the meanwhile, thanks for your time!

**Comment by EricWittmann** [comment]
Implemented in https://github.com/Apicurio/apicurio-registry/pull/5124
