### ISSUE TITLE
Implementing max size requests on upload

### ISSUE THREAD

**Issue by tauonico** [Apicurio/apicurio-registry#1366]
Some proxy block request body by size, is possible to add a parameter to define upload by chunks?

**Comment by EricWittmann** [comment]
Interestingly we'll be implementing various limits, including max body size, pretty soon.

**Comment by carlesarnal** [comment]
This is already possible by using quarkus.http.limits.max-body-size (or the environment variable equivalent, QUARKUS_HTTP_LIMITS_MAX_BODY_SIZE).
