### ISSUE TITLE
JSON compatibility check for combined schema

### ISSUE THREAD

**Issue by hhkkxxx133** [Apicurio/apicurio-registry#1367]
Hello,

I am testing the JSON compatibility check for the combined schema. There are multiple cases when combined keyword changes that seem incorrect.

Let me know what do you think!

Test cases:
1. allOf to anyOf - backward compatible, and vice versa
```
"original": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "allOf": [
    {
      "maximum": 100
    },
    {
      "multipleOf": 6
    }
  ]
},
"updated": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "anyOf": [
    {
      "maximum": 100
    },
    {
      "multipleOf": 6
    }
  ]
}
```
This also applies when:
(a) adding additional subschema in the updated schema
(b) subschemas are backward compatible 

2. oneOf to anyOf - backward compatible, and vice versa
```
"original": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "oneOf": [
    {
      "maximum": 100
    },
    {
      "multipleOf": 6
    }
  ]
},
"updated": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "anyOf": [
    {
      "maximum": 100
    },
    {
      "multipleOf": 6
    }
  ]
}
```
This also applies when:
(a) adding additional subschema in the updated schema
(b) subschemas are backward compatible 

3. non-combined to anyOf - backward compatible, and vice versa
```
 "original": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "number",
    "maximum": 100,
    "multipleOf": 6
  },
  "updated": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "number",
    "anyOf": [
      {
        "maximum": 100
      },
      {
        "multipleOf": 6
      }
    ]
  }
```
This also applies when:
(a) adding additional subschema in the updated schema
(b) subschemas are backward compatible

**Comment by jsenko** [comment]
Hi Kexin,
1. I agree `allOf` to `anyOf` should be backwards compatible, if each schema in `allOf` is forward compatible with some schema in `anyOf`. This should satisfy both cases (a) and (b). WDYT? I'm not sure what you mean by vice versa, backwards<-->forwards or reverse `anyOf`-->`allOf`?
2. This is similar to (1)
3. I think that `simple` to `anyOf` should be backwards compatible, if `simple` is forward compatible with some schema in `anyOf` again. This could be extended to `allOf` by requiring that it's forward compatible with **all** schemas in `allOf`, but it won't work with `oneOf` because we cannot check it will be compatible with only a single one. WDYT?

**Comment by hhkkxxx133** [comment]
Hi Jakub,

1 and 2: 
My "vice versa" here means if `anyOf` -> `allOf`/`oneOf`, should be forward compatible. 
When you say each schema in `allOf`/`oneOf` is forward compatible with some schema in `anyOf`, I am a little bit confused.
For example, below case should be backward compatible.
```
"original": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "allOf": [
    {
      "maximum": 100
    },
    {
      "multipleOf": 6
    }
  ]
},
"updated": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "number",
  "anyOf": [
    {
      "maximum": 200
    },
    {
      "multipleOf": 6
    }
  ]
}
```
where `"maximum": 100` is backward compatible with `"maximum": 200`. So what do you mean "forward" here?

3. Same question for the "forward". I agree with the rest that it could be extended to `allOf` with conditions, but not `oneOf`.
