### ISSUE TITLE
A Strange ClassName Resouce

### ISSUE THREAD

**Issue by vvilerio** [Apicurio/apicurio-registry#1393]
io.apicurio.registry.storage.util.PostgresqlTestcontainerResouce.java
instead of 
io.apicurio.registry.storage.util.PostgresqlTestcontainerResource.java

,well I guess

**Comment by carlesarnal** [comment]
Hi @vvilerio, I cannot see any difference between the actual className and the proposed one, maybe a copy-paste mistake?

**Comment by vvilerio** [comment]
"Resouce" -> "Resou**r**ce"

**Comment by carlesarnal** [comment]
Ohh, thanks. Yes, you're right.

**Comment by EricWittmann** [comment]
I noticed this and have fixed it in https://github.com/Apicurio/apicurio-registry/pull/1389
