### ISSUE TITLE
Error loading Registry UI on https

### ISSUE THREAD

**Issue by johnkbarrow** [Apicurio/apicurio-registry#1442]
As per [#1120 ](https://github.com/Apicurio/apicurio-registry/issues/1120) I've used environment variables REGISTRY_UI_CONFIG_UIURL and REGISTRY_UI_CONFIG_APIURL to allow the Registry UI to work with https.
Unfortunately, when calling https://myschemareg/api I'm getting an error as that page is in turn trying to call http://myschemareg/openapi?format=JSON.
I can't find a similar environment variable to override that URL - is there one?

**Comment by EricWittmann** [comment]
For version 1.3.2.Final, which I'm assuming is what you're using, there unfortunately is not a config setting for that.  Here is the code that is giving you trouble:

https://github.com/Apicurio/apicurio-registry/blob/e3f786ab30af5412d853a4acde793c6e09584724/app/src/main/java/io/apicurio/registry/ui/servlets/SpecUrlFilter.java#L187-L195

That has been changed fairly significantly in the latest release (2.0.0.Final released last Friday).  Now we include documentation on all/most of the APIs we support, and we root them all at `/apis` which is a bit of a change from 1.3 where the APIs were rooted at `/api`.  In any case, looking at the code for 2.0 I don't think this will be a problem any longer.

https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/ui/servlets/SpecUrlFilter.java

**Comment by johnkbarrow** [comment]
Hi @EricWittmann - yes, I'm using 1.3.2.Final. It's not a big issue for me as I'm using the REST API rather than the UI.

**Comment by EricWittmann** [comment]
OK thanks.  Would it be possible for you to test 2.0.0.Final with your setup?  I'd be very interested if there are any similar issues with SSL remaining there.  In this case, hitting `/apis` and then seeing if the API docs for each API worked, that would be super helpful.  If it's not easy for you to test don't worry about it. :)

**Comment by johnkbarrow** [comment]
I'm using the docker in-memory image - is there a 2.0.0.Final release of that yet?

**Comment by johnkbarrow** [comment]
@EricWittmann - I see why I got 1.3.2.Final - I used "_apicurio/apicurio-registry-mem:latest_"

Looks like 2.0.0.Final is tagged with "_apicurio/apicurio-registry-mem:latest-release_"

**Comment by johnkbarrow** [comment]
Hi @EricWittmann - I finally got chance to do some testing with 2.0.0.Final with my setup:

The Registry UI wouldn't load properly without setting the environment variable
```
"name": "REGISTRY_UI_CONFIG_APIURL",
"value": "https://servername.com/apis/registry"
```

The /apis endpoint loads fine, apart from the link for the IBM Schema Registry `/apis/ibmcompat/v1` that returns a 404

**Comment by EricWittmann** [comment]
Great news!  Thanks for checking.  The IBM compat 404 error is unfortunate but expected (missing openapi spec for that API).
