### ISSUE TITLE
JSON schema compatibility rule bug: no change but neither forward nor backward compatible 

### ISSUE THREAD

**Issue by shionefaye** [Apicurio/apicurio-registry#1443]
It is tested with the code in at this [commit](https://github.com/Apicurio/apicurio-registry/commit/c8c510ed7fd0ca47ef27d55554d8ecfdc84252dd).

No change but validate as neither forward nor backward compatible.
```
"original": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "commercial": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "number"
        }
      }
    },
    "residential": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "number"
        },
        "line2": {
          "type": "number"
        }
      }
    }
  },
  "properties": {
    "address": {
      "anyOf": [
        {"$ref":  "#/definitions/commercial"},
        {"$ref":  "#/definitions/residential"}
      ]
    }
  }
},
"updated": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "commercial": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "number"
        }
      }
    },
    "residential": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "number"
        },
        "line2": {
          "type": "number"
        }
      }
    }
  },
  "properties": {
    "address": {
      "anyOf": [
        {"$ref":  "#/definitions/commercial"},
        {"$ref":  "#/definitions/residential"}
      ]
    }
  }
}

```
Backward diff: `[Difference(diffType=COMBINED_TYPE_SUBSCHEMA_NOT_COMPATIBLE, pathOriginal=, pathUpdated=/properties/address, subSchemaOriginal={"$ref":"#/definitions/commercial"}, subSchemaUpdated=null)]`
Forward diff: `[Difference(diffType=COMBINED_TYPE_SUBSCHEMA_NOT_COMPATIBLE, pathOriginal=, pathUpdated=/properties/address, subSchemaOriginal={"$ref":"#/definitions/commercial"}, subSchemaUpdated=null)]`

**Comment by jsenko** [comment]
Hello @shionefaye ,
I may be mistaken but `original` and `updated` schemas in you example are the same. I've tested them and they are both backward and forward compatible. Please provide a specific commit where I can reproduce the issue.

**Comment by shionefaye** [comment]
Right, it is what I was testing. You can resolve this one since the test passes with tmp1 branch.  Looks like I was testing this one with 2.0.0-SNAPSHOT.
