### ISSUE TITLE
serde security properties issues

### ISSUE THREAD

**Issue by tszappanos** [Apicurio/apicurio-registry#1455]
The following configurations do not work through client properties:
1. In case of setting apicurio.auth.username, apicurio.registry.url is taken into username and vice versa. Correction:
In the AbstractSchemaResolver class on line 82, the url and username parameters are exchanged

2. apicurio.auth.client.secret is not considered. The value from apicurio.auth.client.id is set. Correction:
In the DefaultSchemaResolverConfig class, correct the method

public String getAuthClientSecret () {
         return this.getString (AUTH_CLIENT_ID);
     }
Well thank you. Tibor

**Comment by carlesarnal** [comment]
Hi @tszappanos, 

You're right, both are wrong, thanks.

cc @famartinrh
