### ISSUE TITLE
Fix workflow for building CLI images

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1458]
We have a workflow that should be triggered (whenever a release is performed) to build our native CLI executables (one per operating system).  This workflow is not being triggered for a release build (it should).

**Comment by riprasad** [comment]
@EricWittmann is this a high priority? If not, I would look into it after the downstream release activities are complete.

**Comment by EricWittmann** [comment]
Not a high priority at all.  Very low. :)

**Comment by EricWittmann** [comment]
I have updated the workflows so that they can be triggered manually.  I'm happy to live with that for the as long as needed. :)

**Comment by riprasad** [comment]
This is interesting. I just mimicked the situation and created two workflows. one that creates a release and the other that should get triggered on the release event. It did not work. However, when I manually published a release using the Github UI, the workflow got triggered.

I will try to figure out why is this happening.

**Comment by EricWittmann** [comment]
Very interesting!  Is there a way to explicitly trigger/invoke a workflow from another workflow?  We could chain them...

**Comment by riprasad** [comment]
> Very interesting! Is there a way to explicitly trigger/invoke a workflow from another workflow? We could chain them...

@EricWittmann There is definitely a way to trigger a workflow from another workflow. For more information, please refer https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run 

However, I was more curious in knowing the reason why the release-event trigger is not working. I tried creating a release using the Github UI directly and also via Github's REST API and surprisingly the workflows were getting triggered. Finally, I found this from the documentataion:-
```
Events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. If you would like to trigger a workflow from a workflow run, you can trigger the event using a personal access token.
```

I immediately switched to using a PAT and Voila :)

**Comment by EricWittmann** [comment]
Thanks!!
