### ISSUE TITLE
Request: Support in python ?

### ISSUE THREAD

**Issue by Ycallaer** [Apicurio/apicurio-registry#1475]
Hi,
I was wondering if there are any plans to support apicurio as a library in python ?
Currently we are using Confluent schema registry , which integrates nicely with their producer, ideally we want something similar for apicurio.
I

**Comment by kilahm** [comment]
If you're asking for a client SDK to make communication of the Apicurio Registry REST api easer, you can follow the conversation in #1448 .  Once the issues with the provided OpenAPI document [are resolved](https://github.com/Apicurio/apicurio-registry/pull/1477), [`openapi-generator`](https://openapi-generator.tech/) should provide you with a library wrapping all of the HTTP requests and responses.

I'll likely be using `openapi-generator` locally until/unless the Apicurio team starts publishing language specific client SDKs.

**Comment by Ycallaer** [comment]
Ok thanks for your feedback, will check it out
