### ISSUE TITLE
Why limit "getArtifactVersionMetaDataByContent" request bodies to application/json?

### ISSUE THREAD

**Issue by kilahm** [Apicurio/apicurio-registry#1476]
In attempting to address #1448 locally until @EricWittmann is able to supply an official solution, I saw the `getArtifactVersionMetaDataByContent` operation requires a body of content type `application/json`.  I can understand this for artifacts whose content is JSON, however I'm not sure how this endpoint would be used for WSDL, GraphQL, XSD, and other artifacts that aren't typically represented with JSON.

Is there a reason to restrict that endpoint to just `application/json`?  AFAICT following the code, the content isn't ever parsed as JSON (in fact, there's [one place where the body is converted from YAML to JSON](https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java#L232-L234)).

**Comment by EricWittmann** [comment]
Yeah I noticed this while doing the updates in #1477 and fixed it there.  Thanks for reporting this!
