### ISSUE TITLE
Using ccompat creates base64 encoded protobuf schemas ?

### ISSUE THREAD

**Issue by Ycallaer** [Apicurio/apicurio-registry#1478]
Hi,
While testing with confluent-kafka 1.4 (python library) I noticed that protobuf schemas are stored in apicurio as a base64 encoded string.
The serializer gets build as follows:
```
schema_registry_conf = { 'url': 'http://localhost:8888/apis/ccompat/v6'}
schema_registry_client = SchemaRegistryClient(schema_registry_conf)

_proto_conf = {
    'auto.register.schemas': self.config['auto.register.schemas'],
}
return ProtobufSerializer(self.config['proto_msg_type'], schema_registry_client,conf=_proto_conf)
```
When I check the final result, the data is in kafka and the expected entries are in Apicurio.
However if I check the actual content in Apicurio (http://localhost:8888/ui/artifacts/default/etf_dummy_data-value/versions/latest), I get the following output:

`CglldGYucHJvdG8ibAoDZXRmEgwKBGRhdGUYASABKAkSDAoEb3BlbhgCIAEoARIMCgRoaWdoGAMgASgBEgsKA2xvdxgEIAEoARINCgVjbG9zZRgFIAEoARIOCgZ2b2x1bWUYBiABKAMSDwoHb3BlbmludBgHIAEoA2IGcHJvdG8z`

If I run this through base64 decoder I get my expected schema (sort of).

Is this normal behaviour ?
If I use the same code and produce toward Confluent Schema Registry (5.5.3) the entries are normal readable.

Thanks for any insight you can provide.

**Comment by Akhilj786** [comment]
@Ycallaer @carlesarnal @EricWittmann Is there a sample implementation for python?
https://github.com/Apicurio/apicurio-registry/issues/1491#issue-888822344

**Comment by EricWittmann** [comment]
We don't have anything python related.  I would have expected any client that works with the Confluent Schema Registry API would work fine with Apicurio Registry as well. But there may well be a feature of the former that we didn't replicate.

**Comment by carlesarnal** [comment]
Closing as stale. If anyone feels this cannot be close, please, re-open it.
