### ISSUE TITLE
Create spi for rest client implementations

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#1480]

**Comment by carlesarnal** [comment]
@Apicurio/developers I have a question regarding the rest-client spi. How do we want to manage the dependency stuff, leveraging the user to include whatever dependency they want (no, I assume)? Using profiles to include one or another (e.g. the native profile will include the vertx impl)? Thoughts?

**Comment by famartinrh** [comment]
probably worth asking Quarkus people.

but my take is marking the client dependencies as "provided" so the user provides the dependency

**Comment by EricWittmann** [comment]
Agreed - it would be optimal if the vert.x client dependencies were "provided" and the default client impl should use the jdk client.  That way if the user does nothing special, it will still work (using the built in java client) without needing any dependencies.  To use another client (e.g. the vert.x one) they will need to set some kind of config property to switch to another client, and they will need to provide the appropriate dependencies.

**Comment by famartinrh** [comment]
I think we agreed that if the user wants to use the vertx client they will need to pass a vertx instance as a parameter for creating the registry client object

**Comment by carlesarnal** [comment]
Close by #1482
