### ISSUE TITLE
CI Workflow issue: PR builds not using the right code?

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1513]
Recently I submitted a PR for removing the JDBI dependency here:  https://github.com/Apicurio/apicurio-registry/pull/1509

The build was failing with **compilation** errors, despite the build working locally for everyone who tried it.  After a bunch of changes to the PR to try and figure out what was going on, Paolo realized that the maven compile plugin was reporting that it was compiling 305 .java files (when building in GitHub), but when building the branch locally the compile plugin was reporting that it was compiling 286 .java files.  This insight, and some additional sleuthing, revealed that the PR was actually being merged with some changes from `master` and **then** being built.  This resulted in compile errors because some code on `master` was not compatible with the code changes made in the PR.

So the question is whether this is always how PR builds work, or if this is some new gremlin that somehow crept into our build system.  I don't think it's how PR builds are supposed to work, but I don't know what's going on...

**Comment by riprasad** [comment]
Closing this, since no similar case has been reported. Appears to be an intermittent issues.
