### ISSUE TITLE
[question] Does apicurio-registry-sql support mysql?

### ISSUE THREAD

**Issue by Yuutakasan** [Apicurio/apicurio-registry#1546]
I think I can handle it by changing the jdbc driver settings to mysql, but is there any way to write SQL that is not compatible with mysql?

**Comment by EricWittmann** [comment]
Registry does not currently support MySQL.  It would not be difficult to add support (most of the existing SQL will work fine against MySQL).

However, note that changing the driver is not enough.  The way Quarkus works it that DB support is determined at build time, not at runtime.  So to do this we would need another builder, where the appropriate changes are made to `application.properties`.  We'll also need another one of these for mysql:

https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java

If you track down how that is being used, you'll probably see what needs to be done.  If not, I can probably get you started by making a list of changes needed.  :)

**Comment by maver1ck** [comment]
@EricWittmann provided we will write MySQL support is there a chance for merging PR ?
We're thinking about using apicurio-registry-sql with MySQL but don't want to have own fork forever.

**Comment by carlesarnal** [comment]
@maver1ck contributions are always more than welcome. If you want to contribute MySQL support, the timing might be perfect, there's a [PR ](https://github.com/Apicurio/apicurio-registry/pull/2904) from another community member that can give you a better sense of what we expect/what needs to be added to support a new SQL flavour. Let me know if you need help to get started or any doubts!

**Comment by maver1ck** [comment]
Great. I will wait until another PR is merged.

**Comment by EricWittmann** [comment]
@maver1ck The support for SQL Server has been merged and included in 2.4.0.Final.  Have a look at that to get started!  Let us know if you need any help.
