### ISSUE TITLE
ExtJsonConverter throws NPE for null schema/value

### ISSUE THREAD

**Issue by jpechane** [Apicurio/apicurio-registry#1552]
If a message that has no schema/value is passed to the converter then a NPE is thrown. The issue is `io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(String, Headers, Schema, Object)` line `String schemaString = jsonSchema.toString()`

Original Kafka `JsonConverter` supports this scenario.

**Comment by EricWittmann** [comment]
@carlesarnal or @famartinrh - can one of you guys have a look at this?  Code freeze for 2.0 is Monday, so if this is something we can easily fix we could cherry-pick it for 2.0.x and get it into GA.
