### ISSUE TITLE
Image apicurio/apicurio-registry-streams:2.0.0.Final missing

### ISSUE THREAD

**Issue by estahn** [Apicurio/apicurio-registry#1561]
https://hub.docker.com/r/apicurio/apicurio-registry-streams/tags?page=1&ordering=last_updated&name=2.0.0.Final

**Comment by carlesarnal** [comment]
Hi @estahn,

The streams storage has been removed in `2.0.0.Final`. If you want to use Kafka as the storage for the registry you should use the [kafkasql](https://hub.docker.com/r/apicurio/apicurio-registry-kafkasql/tags?page=1&ordering=last_updated) variant.
