### ISSUE TITLE
Refactor Protobuf schema parsing utilities into separate module

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1572]
The Java classes under [serde/protobuf/schema](https://github.com/Apicurio/apicurio-registry/tree/master/serdes/protobuf-serde/src/main/java/io/apicurio/registry/serde/protobuf/schema) are useful for parsing Protobuf schema files (.proto) and can be extracted into a separate module for general reusability. Will you be willing to refactor them into separate module? I can submit a PR with module name `protobuf-schema-utilities` (please feel free to provide a better suggestion).

Future: Can they be contributed to squareup wire repository?

**Comment by EricWittmann** [comment]
I don't have any problem refactoring into a separate module.  What do you think @famartinrh ?

**Comment by blacktooth** [comment]
Created a [PR](https://github.com/Apicurio/apicurio-registry/pull/1578) for suggested refactoring.

**Comment by EricWittmann** [comment]
Thanks @blacktooth - I'm once again behind on my GH notifications.  :(  I'll have a look soon.
