### ISSUE TITLE
Add an option to the build to skip the UI

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1586]
We should have an option when building to skip the UI.  We can enable such an option only when building for MT, where we disable/hide the UI anyway.  The default should continue to be what we have today (UI is built by default).

**Comment by pawelrubin** [comment]
That would be awesome, especially in CI builds.

**Comment by riprasad** [comment]
@EricWittmann The maven front-end plugins come with options to skip executions. All the available options can be seen here https://github.com/eirslett/frontend-maven-plugin#skipping-execution 

In our case, we can use `-Dskip.yarn` and this would skip the execution of yarn commands.

![Screenshot from 2021-06-24 18-38-00](https://user-images.githubusercontent.com/61964599/123268369-983e8700-d51b-11eb-91de-c685c85d0d62.png)

**Comment by EricWittmann** [comment]
@famartinrh @riprasad - Can we update any registry build for MAS to add this option?  When building in MT mode we can safely disable the UI build.  Doing that should speed the build up a little bit.

**Comment by riprasad** [comment]
The only place that I can think of adding this option is in the build-scripts for AppSRE CI jobs.

**Comment by famartinrh** [comment]
I'm working on updating the build-scripts for AppSRE to include some more testing, I'll include this in my changes
