### ISSUE TITLE
Protobuf schema parser adds `json_name` to all the fields.

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1617]
Protobuf schema parser method, `fileDescriptorToProtoFile` in [FileDescriptorUtils](https://github.com/Apicurio/apicurio-registry/blob/master/utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java#L442) adds optional `json_name` option to all the fields in the Protobuf schema. 

For example, consider the following schema,

```
message Address {
  required string street = 1;
  optional int32 zip = 2;
  optional string city = 3;
}

message Customer {
  required string name = 1;
}
```

Descriptor for above schema is used to interpret the original schema using code below,

```
String rawSchema = FileDescriptorUtils.fileDescriptorToProtoFile(Customer.getDescriptor().getFile().toProto()).toSchema();
```

This results in following schema,

```
// Proto schema formatted by Wire, do not edit.
// Source: 

message Address {
  required string street = 1 [json_name = ""];

  optional int32 zip = 2 [json_name = ""];

  optional string city = 3 [json_name = ""];
}

message Customer {
  required string name = 1 [json_name = ""];
}

```

**Expected behavior**

`[json_name = ""]` shouldn't be added unless present in the original schema.

**Comment by blacktooth** [comment]
PR #1618 created.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1618
