### ISSUE TITLE
KafkaProducer is not getting the artifact version defined by `apicurio.registry.artifact.version` property

### ISSUE THREAD

**Issue by rmarting** [Apicurio/apicurio-registry#1620]
My application uses a defined version of artifact already registered in Apicurio Registry, however the producer fails with the following exception:

```text
Caused by: io.apicurio.registry.rest.client.exception.ArtifactNotFoundException: No artifact with ID 'Message' in group 'io.jromanmartin.kafka.schema.avro' was found.
```

To achieve it, my KakfaProducer is configured with the following property:

```java
props.putIfAbsent(SerdeConfig.AUTO_REGISTER_ARTIFACT, false);
props.putIfAbsent(SerdeConfig.EXPLICIT_ARTIFACT_VERSION, "2.0");
```

The artifact was already registered using the `apicurio-registry-maven-plugin` plug-in as:

```xml
                    <plugin>
                        <groupId>io.apicurio</groupId>
                        <artifactId>apicurio-registry-maven-plugin</artifactId>
                        <version>${apicurio.version}</version>
                        <executions>
                            <execution>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>register</goal>
                                </goals>
                                <configuration>
                                    <registryUrl>${apicurio.registry.url}</registryUrl>
                                    <artifacts>
                                        <artifact>
                                            <groupId>io.jromanmartin.kafka.schema.avro</groupId>
                                            <artifactId>Message</artifactId>
                                            <version>2.0</version>
                                            <type>AVRO</type>
                                            <file>
                                                ${project.basedir}/src/main/resources/schemas/message.avsc
                                            </file>
                                            <ifExists>RETURN_OR_UPDATE</ifExists>
                                            <canonicalize>true</canonicalize>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

It seems that the client is not using the version declared to get the schema. The issue is very strange because describes that the artifact does not exist, when in the UI you get it. I can reproduce that issue using a valid version (already registered) or a non-registered version.

However if a request a version non-registered in the UI, I got the following issue:

http://service-registry.amq-streams-demo.apps-crc.testing/ui/artifacts/io.jromanmartin.kafka.schema.avro/Message/versions/1

```text
io.apicurio.registry.storage.VersionNotFoundException: No version '1' found for artifact with ID 'Message' in group 'io.jromanmartin.kafka.schema.avro'.
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.getArtifactVersionMetaDataInternal(AbstractSqlRegistryStorage.java:1655)
```

Could be the client not using the same pattern to get the schema? Why in my application got the same error but in the UI I got the right exception?

Tested with Apicurio 2.0.1.Final.

**Comment by EricWittmann** [comment]
I should have tested this before suggesting it to you I guess.  There may be a bug in the Serializer - I'll need to reproduce again and try it myself.  The relevant code (if you wanted to debug it yourself) is here:

https://github.com/Apicurio/apicurio-registry/blob/02f0a6ece411a68377b4df4da4459d3ec6557a23/serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultSchemaResolver.java#L72-L102

The resolution of the artifact coordinates happens here:

https://github.com/Apicurio/apicurio-registry/blob/02f0a6ece411a68377b4df4da4459d3ec6557a23/serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractSchemaResolver.java#L163-L177

**Comment by EricWittmann** [comment]
OK as expected this is a bug in the schema resolver config.  The bug is here:

https://github.com/Apicurio/apicurio-registry/blob/master/serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractSchemaResolver.java#L120-L127

Simple copy/paste bug. :(

I'll fix the code now but you would need to wait for a new release or build your own locally.

CC @famartinrh

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/commit/85bd4133afa1dafd093f5189298c67f6436bdfa3

**Comment by rmarting** [comment]
Thanks @EricWittmann for fixing it so quickly. I could wait for the next release, but when is it extimated?

**Comment by EricWittmann** [comment]
I don't have a specific date for that yet.  We may release a 2.0.2.Final or we may skip that and go directly for 2.1.0.Final.  I'm leaning towards the former, in which case we could release something pretty soon (releases are cheap).
