### ISSUE TITLE
CCompat Layer the Schema dto is not fully compatible.

### ISSUE THREAD

**Issue by michaelpearce-gain** [Apicurio/apicurio-registry#1660]
Missing two fields in the dto.

  private String schemaType;
  private List<SchemaReference> references;

See:
https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java

and:
https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/ccompat/dto/Schema.java

Note this means when using apicurio and the confluent clients, if using jsonschema or protobuf, its broken as it requires the schemaType,  blocking migration to apicurio.

**Comment by michaelpearce-gain** [comment]
[apicurio-confluent.zip](https://github.com/Apicurio/apicurio-registry/files/6804713/apicurio-confluent.zip)

Please find attached a very simple test project that demonstrates issue with the missing to fields in ccompact using confluent serdes with protobuf.

**Comment by michaelpearce-gain** [comment]
looks like as well apicurio is missing handling the extra fields SchemaString - https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java

**Comment by michaelpearce-gain** [comment]
seems you can see most of the changes that were added in 2020 here https://github.com/confluentinc/schema-registry/pull/1280

**Comment by carlesarnal** [comment]
Thanks @michaelpearce-gain, I will look into that information, very helpful. As you said, it seems that we have a difference that is not documented in the API reference. For instance, if you go [here](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id) or [here](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions) you will see that the example response is not returning any `schemaType` or references.

I will revisit this and fix any issues we might have.

**Comment by carlesarnal** [comment]
I have created two new issues to split the work into two separate pull requests. #1676 and #1675. Closing this one in favour of the other two.

**Comment by michaelpearce-gain** [comment]
Can we keep this open so we get notified once resolved. Also it be good to include the sample test case we supplied in this issue to confirm resolvement.

**Comment by carlesarnal** [comment]
Hi @michaelpearce-gain, the first issue is resolved, to return the `schemaType`. The second one, as you can imagine, is a tougher nut to crack since we don't have support for references yet in Apicurio Registry. That said, there are some discussions around implementing it.

See [this](https://github.com/Apicurio/apicurio-registry/issues/865).

**Comment by michaelandrepearce** [comment]
That makes it impossible to adopt / transition to it without. As for protobuf and jsonschema its a real prerequisite, thus why exists in confluents

**Comment by michaelandrepearce** [comment]
Hi @carlesarnal is there any indication if/when this will be addressed, as its quite a major blocker, and there is clearly prior art to take inspiration from, as the confluent one is working fine and agnostically for json and proto here.

**Comment by carlesarnal** [comment]
Hi @michaelandrepearce, this is for sure in our backlog but I don't have a timeframe for the implementation.

**Comment by carlesarnal** [comment]
Hi @michaelandrepearce, just FYI, the linked PR contributes the support for artifact references. In that PR, we added support for references in both the confluent compatibility API and also in the Apicurio Registry API and also in our Serdes.
