### ISSUE TITLE
Missing features / bugs with Protobuf schema parser

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1671]
I was running some tests on canonicalizing Protobuf schemas and found the following issues. The issues are mostly with the way `FileDescriptorUtils` parses the `FileDescriptorProto` into Proto schema and vice-versa. I baselined the results against the original Proto schema. 

**Original Protobuf schema**: [link](https://github.com/blacktooth/apicurio-registry/blob/protobuf-bug-fixes/utils/protobuf-schema-utilities/src/test/proto/TestOrderingSyntax3.proto)

**Expected Original FileDescriptorProto**: [link](https://gist.github.com/blacktooth/d0ebe9e9b033b5791b01596732756ba1)

**FileDescriptorProto from parsing above Protobuf schema using below code**: [link](https://gist.github.com/blacktooth/b0f779871ed130bfa20b750f0f8f5f16)

[Code](https://github.com/blacktooth/apicurio-registry/blob/protobuf-bug-fixes/utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java#L54)
```
FileDescriptorUtils.protoFileToFileDescriptor(...)
```

**FileDescriptorProto from parsing schema generated by FileDescritptorUtils**: [link](https://gist.github.com/blacktooth/b9044e11c06c3142b772c358ca64de49)
[Code](https://github.com/blacktooth/apicurio-registry/blob/protobuf-bug-fixes/utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java#L49)

```
FileDescriptorUtils.fileDescriptorToProtoFile(...).toSchema()
```

**Summary of discrepancies** 

Feature | Syntax | Schema Text to FileDescriptorProto | FileDescriptorProto to Schema Text | Correct value
-- | -- | -- | -- | --
Internal references | Proto 2 / Proto 3 | typeName is incorrect and type is missing | type is missing | type: TYPE_ENUMtype_name: ".foo.bar.AddressType"
json_name option | Proto 2 / Proto 3 | Not present | Not present | json_name: "Address_Street"
deprecated option | Proto 2 / Proto 3 | Not present | Not present | options { deprecated: true }
groups (deprecated feature) | Proto 2 / Proto 3 (deprecated) | Not present | Present but type is missing | Should be present with type = GROUP
Maps | Proto 2 / Proto3 | Label is missing, name is not captialized | type is missing | Refer here
Reserved range Id | Proto 2 / Proto 3 | Reserved ranges are present but end values are incorrect | Reserved ranges are missing | Refer here
Extension ranges | Proto 2 / Proto 3 (deprecated) | Not present | Not present | extension_range {start: 100end: 121}
Extensions | Proto 2 / Proto 3 (deprecated) | Not present | Not present | extension {name: "isPremium"extendee: ".foo.bar.Customer"number: 101label: LABEL_OPTIONALtype: TYPE_BOOL}
Nested references | Proto 2 / Proto 3 | Incorrect type name and missing type | type and label is missing | field {name: "value"number: 2label: LABEL_OPTIONALtype: TYPE_MESSAGEtype_name: ".foo.bar.Address.Country"}
One Of | Proto 2 / Proto 3 | Correctly interpreted but should be after required fields | Correctly interpreted but should be after required fields | Refer
Name property | Proto 2 / Proto 3 | Incorrect as it's not known | Incorrect as it's not known |  
Syntax property | Proto 2 / Proto 3 / Empty | Empty is not interpreted correctly | Empty is not interpreted correctly | Empty shouldn't be interpreted.
Services | Proto 2 / Proto 3 | Not present | Not present | service {name: "AddressService"method {name: "Search"input_type: ".foo.bar.Customer"output_type: ".foo.bar.Address"}}

**Questions**

1. Are you aware of these discrepancies and working on fixing them? 
2. Do you see any concerns with making these parsers as close as possible to outputs generated by standard Protobuf library?
3. I am willing to contribute to fix some of these discrepancies. Do you have any suggestions on how to take this forward?

**Comment by carlesarnal** [comment]
Hi @blacktooth,

1. We weren't are of all of them, I will look at them and see if there's any other GH issue opened that is related to the baseline results.
2. No concerns in making this as close as possible to the standard outputs.
3. I will be more than happy to collaborate on this or to help you to go through this. Any specific questions you need help with?

**Comment by blacktooth** [comment]
Thanks! I will be posting PRs for individual bugs from above table. 

Separately, Is there a reason why the [Protobuf canonicalizer](https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/types/provider/ProtobufArtifactTypeUtilProvider.java#L50) is not implemented?

**Comment by carlesarnal** [comment]
Great, that works for me, just send the PRs and I will go through them. I don't think there are any open issues directly related to this so if you want to open new issues to keep track of what has been fixed and what not, feel free.

I don't know if there's a specific reason, perhaps @famartinrh knows better.

**Comment by famartinrh** [comment]
There is no specific reason why the Protobuf canonicalizer is not implemented

**Comment by EricWittmann** [comment]
The reason is bandwidth - we haven't gotten to it yet.  :) :)

**Comment by blacktooth** [comment]
For issues with incorrect parsing of internal / nested references, I have created an [issue](https://github.com/square/wire/issues/2024) with wire repo.

**Comment by blacktooth** [comment]
Thanks a lot for being open and supporting us in contributing these bug fixes. We have contributed all the changes. This issue can be resolved. Thanks again!

**Comment by EricWittmann** [comment]
Thank you for the contribution!
