### ISSUE TITLE
apicurio schema registry using GoLang

### ISSUE THREAD

**Issue by cjshree** [Apicurio/apicurio-registry#1731]
I need to connect to apicurio schema registry using GoLang. I tried using Confluent schema Registry GoCode package, but it does not work. How can I make it work. It integrates well with Strimzi Kafka but I am not able to find a solution for referring Schema Registry using GoLang

**Comment by cjshree** [comment]
I tried using the Confluent [Golang client for Schema Registry](https://github.com/riferrei/srclient) . It throws a panic error bcoz Confluent and Apicurio uses different link to get the schema registry. Is there a tried and tested GoLang client to connect to Apicurio Schema Registry?
Below is the error
panic: Error creating the schema Post "http://localhost:8080/subjects/myTopic-value/versions": dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by EricWittmann** [comment]
I think the only problem here is that you're using the wrong URL to access the confluent compatibility rest API.  For example when I am using the registry on localhost and I want to use the compatibility API to get a list of subjects I would use the following URL: http://localhost:8080/apis/ccompat/v6/subjects

**Comment by cjshree** [comment]
This is working to some extend..It progressing to the next level . Am I close to ensure Apicurio works with Confluent Go Code? 

panic: Error creating the schema 404 Not Found: RESTEASY003210: Could not find resource for full path: http://localhost:8080/apis/ccompat/v6/subjects/subjects/myTopic-value/versions

**Comment by carlesarnal** [comment]
That error is normal, the subjects part in the path is duplicated. You need to remove one of them.

**Comment by EricWittmann** [comment]
@carlesarnal is correct - the URL I indicated above was to the `/subjects` endpoint in the confluent compatibility API.  Useful for `curl` or Postman to do a GET.  But if you're using a Confluent compatible client, you'll want to configure that client with a URL like this:

http://localhost:8080/apis/ccompat/v6

**Comment by EricWittmann** [comment]
That should definitely work - I'm going to close this but **please** re-open it if things still don't work right!
