### ISSUE TITLE
Protobuf Dependency Management

### ISSUE THREAD

**Issue by bakjos** [Apicurio/apicurio-registry#1737]
I was trying to use a proto file with additional dependencies, the way this is being handled by the Confluent schema registry is to create a subject per external dependency and resolve it when it's being queried.  If I try to do the same using the Apicurio schema registry, the write works well, but when I try to deserialize the data, it fails because it can not resolve one type. I couldn't find a way to do write the external dependencies to the schema registry and use them when reading. This was also working fine with the previous version (1.3.1.Final) using the PROTOBUF_FD

**Comment by EricWittmann** [comment]
Dependencies/references are not currently supported in Apicurio Registry.  This is on our backlog but just not implemented yet.

**Comment by einarjohnson** [comment]
@EricWittmann , do you have a rough ETA on when this may be implemented? I am currently working on a large project where we use Protobuf to define events posted to our Kafka infrastructure. All the Protobuf schemas are using imports for code re-usability and we have been looking into adopting the Apicurio Registry. This is a must-have feature for us to proceed.

**Comment by EricWittmann** [comment]
I'm sorry to say I don't have a timeframe for this - it's high on our backlog but not yet addressed.  Other priorities are preventing this.  

@carlesarnal this is a part of the ref work. :)

**Comment by einarjohnson** [comment]
ok, thanks for getting back to me @EricWittmann
