### ISSUE TITLE
UI is trying to use keycloak as openid provider inspite of configuration to not do that

### ISSUE THREAD

**Issue by RoopGuron** [Apicurio/apicurio-registry#1801]
Hi,
    I am building and running **apicurio-registry** using the following commands: 

```
<git-cloned-location>/apicurio-registry ./mvnw clean package -DskipTests 
<git-cloned-location>/apicurio-registry ./mvnw quarkus:dev 
```

 with the **app** application properties as follows:

```
# Okta TEST
quarkus.oidc.auth-server-url=https://dev-71378222.okta.com/oauth2/default
registry.auth.token.endpoint=https://dev-71378222.okta.com/oauth2/default/v1/token
quarkus.oidc.client-id=<Client-Id>
registry.auth.client-secret=<Client-Secret>
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.oidc.authentication.redirect-path=/callback
quarkus.oidc.authentication.restore-path-after-redirect=true

```

As you can see I am not using keycloak but OKTA. 
But the UI code tries to use keycloak as can be seen from the code here:
https://github.com/Apicurio/apicurio-registry/blob/637b504cd06f39f1e96c91a78429f92ecc14bfc0/ui/src/services/config/config.service.ts#L140

How can I use OKTA and not KeyCloak as OpenID Connect Provider? 

thanks

**Comment by EricWittmann** [comment]
Hi @RoopGuron - you are right that the UI is currently implemented using KeycloakJS as the authentication framework.  We have an outstanding task around testing with a non-Keycloak idp.  We haven't completed this work yet, and so haven't fixed all the issues.  That includes this UI issue.

We will need to investigate how to secure the UI using a more generic OpenID connect UI framework.  That work is pending.  I'm open to suggestions if you have any experience in this area!

**Comment by RoopGuron** [comment]
Hi @EricWittmann, 
   Apologize for the delay in responding back. 
   Let me think...

   The architecture of the _**apicurio-registry**_ Please correct if my understanding is misplaced:

      UI is a **React App** and J**ava Quarkus Web Server**.

      You do have on the server side authentication apis with capabilities to initiate OAuth2.0/OpenID Connect Flows. 

     You need to ensure [_Authorization Code_ Grant type](https://oauth.net/2/grant-types/authorization-code/) flow initiated against **_configured_** OIDC/OAuth2.0 provider in response to a link click on the UI for instance 
`<a href="/auth/provider">Log In with OAuth 2.0 Provider</a>`.
   If the server successfully concludes the Authorization_Code flow a `cookie based Session` in the apicurio-registry server needs to be established for the authenticated user.

In the Java ecosystem the only comprehensive library for Authentication with multiple as well as generic Authentication protocols(SAML2.0, OAuth2.0 and OpenID Connect) that comes to mind is [Spring-Security](https://docs.spring.io/spring-security/site/docs/current/reference/html5/).

Regards,
Roop

**Comment by carlesarnal** [comment]
Hi @RoopGuron,

your understanding is correct. As Eric's says, right now the UI is using `keycloakjs` for the authentication so it's not possible to use anything else but Keycloak. That said, it's on our backlog to address that so users are able to use any other OIDC provider. 

In response to your last comment, Quarkus has a nice set of capabilities in the security area. They're not bundled as a single library but as a set of quarkus extensions. You have a full list [here](https://quarkus.io/guides/#security). 

Thanks for your comments.

**Comment by EricWittmann** [comment]
But the real trick is how to implement auth in the **user interface**.  There are a few ways that can be done, including handling it on the server (before actually serving the JS files) or handling it in the UI app.  We are using keycloakjs to do the latter.  I'm not aware of any other JS libraries that could provide similar functionality, or whether perhaps keycloakjs is capable of working with other OIDC providers.  These are things to research.

I'm not a Spring guy but I assume Spring-Security is a server-side library, not something we could use to replace keycloakjs.  As Carles says, if we were to use server-side auth, then we would likely use Quarkus functionality.

**Comment by RoopGuron** [comment]
@EricWittmann For some food for thought, you could take a look at how [PassportJS](http://www.passportjs.org/) is being utilized by other UI apps like [backstage.io](http://www.backstage.io/) for instance.

**Comment by EricWittmann** [comment]
@carlesarnal Can this be updated now that we have support in the UI for non-keycloak auth providers?

**Comment by carlesarnal** [comment]
This can be close. The configuration area for using different oidc providers is available in the latest release and can be configured [here](https://github.com/redhat-integration/apicurio-registry/blob/main/app/src/main/resources/application.properties#L74-L83).
