### ISSUE TITLE
Does Apicurio support Java 17

### ISSUE THREAD

**Issue by pjgg** [Apicurio/apicurio-registry#1838]
### Questions

Java 17 (LTS) will be released [soon](https://openjdk.java.net/projects/jdk/17/), do you know if apicurio-registry is supported under this JDK version.

**Comment by EricWittmann** [comment]
Apicurio Registry is untested against Java 17.

@Apicurio/developers anyone interested in giving this a try?

**Comment by carlesarnal** [comment]
I can test this.

**Comment by carlesarnal** [comment]
Now that our workflows have been using java 17 for a while (and also 11) I guess we can safely claim that java 17 is supported.
