### ISSUE TITLE
Update OpenShift template to appropriate image registry/tag

### ISSUE THREAD

**Issue by smccarthy-ie** [Apicurio/apicurio-registry#184]
RH OpenShift template points to internal registry with 1.5-6 tag
https://github.com/Apicurio/apicurio-registry/blob/1.0.x-redhat/distro/openshift-template/service-registry-template.yml

Should be registry.redhat.io/fuse7-tech-preview/fuse-service-registry-rhel7 (latest tag is 1.5-9)

**Comment by EricWittmann** [comment]
Thanks!  Fixed by https://github.com/Apicurio/apicurio-registry/commit/51ea4f666113a40e79d56ff0f4c305f2b6083e82
