### ISSUE TITLE
Time out waiting for node assignment

### ISSUE THREAD

**Issue by shrinanda** [Apicurio/apicurio-registry#1853]
Hi ,

I am trying to deploy the APICURIO registry using kafka bootstrap server on EKS. I am getting error on " time out waiting for node assignment". Please help me with resolution.
[apicurio-registry-kafka-integration-log.txt]
(https://github.com/Apicurio/apicurio-registry/files/7182559/apicurio-registry-kafka-integration-log.txt)

Added kafka bootstrap server details on values.yaml like
uncomment and adjust for kafka persistence
kafka:
bootstrapServers: "kafka-kafka-bootstrap.kafka.svc:9093"
Refer log file in the attachment .

**Comment by EricWittmann** [comment]
It looks like Registry couldn't reach your kafka cluster.  It's failing trying to create the topic it needs.  Are you sure the kafka cluster is accessible from the registry node?

**Comment by shrinanda** [comment]
When i disable the authentication using same bootstrap server, i am able to deploy without any issue which means server accessible. 
"kafka:
   # authorization:
   #   type: simple

**Comment by EricWittmann** [comment]
OK so you're saying it's an authorization issue?  You could try manually creating the required Kafka topic before starting up the server.

**Comment by carlesarnal** [comment]
We have support for authentication for the Kafka storage and [documentation](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-installing-registry-storage-openshift.html#configuring-kafka-oauth_registry) for it.
