### ISSUE TITLE
Upgrade two dependencies and release 2.0.2.Final

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1856]
The following dependencies should be upgraded:

* org.apache.commons:commons-compress
* org.keycloak:keycloak-core

The commons-compress version should be upgraded to 1.21.

The keycloak-core version should be upgraded to 13.0.0.

These changes should be made on the `2.0.x` branch.  Once done we should release `2.0.2.Final`.

**Comment by riprasad** [comment]
Project already uses `org.keycloak:keycloak-core:13.0.0`
upgraded dependency `org.apache.commons:commons-compress` to `1.21`

**Comment by EricWittmann** [comment]
@riprasad I think we have a KC 12 dependency in tests somewhere maybe?  @carlesarnal if that's true can we upgrade it to 13 for the tests or not?

**Comment by riprasad** [comment]
@EricWittmann I just checked and cannot find any dependency with version `kc-12*`, @carlesarnal can confirm as well

**Comment by EricWittmann** [comment]
OK my mistake, thanks @riprasad
