### ISSUE TITLE
Apicurio APIs for schema registry client not working.

### ISSUE THREAD

**Issue by nehasewda** [Apicurio/apicurio-registry#1871]
I want to use Apicurio's API and methods like client.listArtifacts(), client.getArtifactByGlobalId(X), createArtifact(),etc.
I have followed all the given official documents and included all the required configuration setup but still not able to use the above mentioned methods in my kafka streams application.

Please find the sample code used -
```java
streamsConfig.putIfAbsent(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM, schemaRegUrl);
streamsConfig.putIfAbsent(AbstractKafkaSerializer.REGISTRY_ARTIFACT_ID_STRATEGY_CONFIG_PARAM, SimpleTopicIdStrategy.class.getName());
streamsConfig.putIfAbsent(AbstractKafkaSerializer.REGISTRY_GLOBAL_ID_STRATEGY_CONFIG_PARAM, GetOrCreateIdStrategy.class.getName());
streamsConfig.putIfAbsent(JsonSchemaSerDeConstants.REGISTRY_JSON_SCHEMA_VALIDATION_ENABLED, Boolean.TRUE);

RegistryRestClient client = RegistryRestClientFactory.create(schemaRegUrl);
System.out.println(client.listArtifacts());
System.out.println(client.getArtifactByGlobalId(6));
System.out.println(client.getLatestArtifact("artifactId").toString());
```

In response to above statements, I am getting exception - javax.ws.rs.WebApplicationException.

I have referred to this link majorly - https://github.com/Apicurio/apicurio-registry-examples/blob/master/simple-json/src/main/java/io/apicurio/registry/examples/simple/json/SimpleJsonSchemaExample.java

Kindly help.

**Comment by EricWittmann** [comment]
Can you provide any details about the exception?  I think it should have something extra - a status code or the response object or something.  That should tell us a lot more.

**Comment by nehasewda** [comment]
Hi,

This is working fine after few changes.
