### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1896]
Looks like support for Java 8 was dropped as part of [commit](https://github.com/Apicurio/apicurio-registry/commit/5ceb8a89ae772172826b150b87ff9f1bf87263ec). Is this intentional? Some of our libraries that depend on Apicurio packages still maintain Java 8 support. Is it possible to release Java 8 JARs for modules like [protobuf-schema-utilities](https://github.com/Apicurio/apicurio-registry/tree/master/utils/protobuf-schema-utilities)?

**Comment by carlesarnal** [comment]
Hi,
Yes, we dropped the support for java 8 since it's no longer supported in Quarkus. I don't see any issue in releasing Java 8 JARs for some modules that are not Quarkus dependant. @riprasad @EricWittmann any reason to not add that?

**Comment by riprasad** [comment]
@EricWittmann would be the best person to answer this!

**Comment by EricWittmann** [comment]
I have no problem with doing this.  Presumably we could do it via a classifier.

**Comment by blacktooth** [comment]
This is merged. Thanks!
