### ISSUE TITLE
multitenancy: context is not cleared out when passing tenantId via header or via domain name

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry#1912]
When tenantId is passed with http path prefix we are cleaning the context after the request here https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/rest/RegistryApplicationServletFilter.java#L158

For the other modes we support for providing the tenantId we are not cleaning the context, and therefore leaking the context for subsequent executions of other tenants, metrics, ...

I don't know how to fix it for good, this needs some investigation. Also we have to be careful if our requests are processed asynchronously to not to clean the context too early, that could mean removing the context from requests that are being processed.. however I dont think we are async so we may be good

**Comment by carlesarnal** [comment]
This is no longer happening.
