### ISSUE TITLE
[Docs] Installing Apicurio Registry using Docker points to the wrong image version

### ISSUE THREAD

**Issue by paoloantinori** [Apicurio/apicurio-registry#1918]
https://www.apicur.io/registry/docs/apicurio-registry/2.1.0.Final/getting-started/assembly-installing-registry-docker.html

note this is a `2.x` URL

provides examples that refer to images pointing to `1.x`:

`$ docker pull apicurio/apicurio-registry-mem` 

should be 

`$ docker pull apicurio/apicurio-registry-mem:2.0.x-release`

**Comment by smccarthy-ie** [comment]
Fixed in #1996
