### ISSUE TITLE
Improve Import/Export feature

### ISSUE THREAD

**Issue by SafarMirek** [Apicurio/apicurio-registry#1922]
Currently, import into registry works fine only with new registry instance, because of the conflicts with ids. I would like to change that. 
I propose to implement these things:
1) Add header to allow users import data with do-not-preserve globalId/contentId. Usecase for that would be, if user is using contentHash to get schemas and wants to import his schemas into not new registry instance.
2) Our export utilities generating globalIds from 1 to N.. and this could cause a conflict even the exported data had not globalId at all. For that case I would like to suggest allowing omitting globalId in the exported zip file and import feature will generate that on the import.
3) The export utilities needs to contains our app module for getting cannonicalHash. I would suggest to allow omitting that too and get cannonical hash when importing the schemes.

@Apicurio/developers What do you think? Do you have any other suggestions how to improve export/import feature?

**Comment by jsenko** [comment]
huh `jsenko assigned carlesarnal 10 minutes ago` that's a mistake sorry
