### ISSUE TITLE
Implement protobuf content canonicalizer

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry#1971]
We can implement the protobuf content canonicalizer and use it in `ProtobufArtifactTypeUtilProvider`

For the implementation we should reuse some code we are currently using in our serdes, look at `ProtobufKafkaSerializer#getSchemaFromData`

A question that arises is how are we going to handle the upgrade when we have a new version that generates different canonicalHash for protobuf artifacts from previous versions. That will make, for instance, search by contentHash to fail to find protobuf artifacts create before the upgrade.

**Comment by EricWittmann** [comment]
I think the answer to @famartinrh about upgrading the DB with new contentHash values is to provide one of these:  https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/storage/impl/sql/IDbUpgrader.java

That allows us to provide a Java class that will participate in the DB upgrade process.  This is a concept brought over from Studio.  Here is an example:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/java/io/apicurio/hub/core/storage/jdbc/upgraders/ApiDesignTypeUpgrader.java

Here's how that is used:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/resources/io/apicurio/hub/core/storage/jdbc/upgrade-8_postgresql9.ddl#L10

**Comment by famartinrh** [comment]
> I think the answer to @famartinrh about upgrading the DB with new contentHash values is to provide one of these: https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/storage/impl/sql/IDbUpgrader.java
> 
> That allows us to provide a Java class that will participate in the DB upgrade process. This is a concept brought over from Studio. Here is an example:
> 
> https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/java/io/apicurio/hub/core/storage/jdbc/upgraders/ApiDesignTypeUpgrader.java
> 
> Here's how that is used:
> 
> https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/resources/io/apicurio/hub/core/storage/jdbc/upgrade-8_postgresql9.ddl#L10

thanks! I'm working on that

**Comment by famartinrh** [comment]
let's have this is WIP into account before making any new release
