### ISSUE TITLE
Kafka SQL storage contentId and globalId message keys not unique

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1993]
These messages are being compacted when they should not be.  The result is inconsistent values for these ID counters when restarting the application.

Because we cannot compact these messages, we should consider batching them instead of requiring one kafka message for each ID.  Perhaps that's a separate issue.

The solution here is to add a UUID to the `GlobalIdKey` and `ContentIdKey` messages.

**Comment by EricWittmann** [comment]
Note:  we should also try to create an automated test for this.

**Comment by jsenko** [comment]
Related to #1873
