### ISSUE TITLE
Cannot build exportV1 tool after release 2.1.0

### ISSUE THREAD

**Issue by ajborley** [Apicurio/apicurio-registry#2024]
The upgrade to quarkus in PR #1526 causes the exportV1 tool build to fail with the following error.

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.2.3.Final:build (default) on project 
apicurio-registry-utils-exportV1: Execution default of goal io.quarkus:quarkus-maven-plugin:2.2.3.Final:build 
failed: An API incompatibility was encountered while executing io.quarkus:quarkus-maven-plugin:2.2.3.Final:build: 
java.lang.AbstractMethodError: Receiver class io.apicurio.registry.services.RegistryConfigSource does not 
define or inherit an implementation of the resolved method 'abstract java.util.Set getPropertyNames()' of 
interface org.eclipse.microprofile.config.spi.ConfigSource.
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.quarkus:quarkus-maven-plugin:2.2.3.Final
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/ajborley/.m2/repository/io/quarkus/quarkus-maven-plugin/2.2.3.Final/quarkus-maven-plugin-2.2.3.Final.jar
[ERROR] urls[1] = file:/Users/ajborley/.m2/repository/io/quarkus/quarkus-bootstrap-core/2.2.3.Final/quarkus-bootstrap-core-2.2.3.Final.jar
[ERROR] urls[2] = file:/Users/ajborley/.m2/repository/io/quarkus/quarkus-bootstrap-app-model/2.2.3.Final/quarkus-bootstrap-app-model-2.2.3.Final.jar
[ERROR] urls[3] = file:/Users/ajborley/.m2/repository/org/jboss/logging/jboss-logging/3.4.2.Final/jboss-logging-3.4.2.Final.jar
[ERROR] urls[4] = file:/Users/ajborley/.m2/repository/org/jboss/logging/commons-logging-jboss-logging/1.0.0.Final/commons-logging-jboss-logging-1.0.0.Final.jar
[ERROR] urls[5] = file:/Users/ajborley/.m2/repository/io/quarkus/quarkus-bootstrap-maven-resolver/2.2.3.Final/quarkus-bootstrap-maven-r
```

The issue is that the 1.3.2.Final version of the apicurio-registry-app package is imported by the exportV1 pom, but the new quarkus level requires the changes that went into [app/src/main/java/io/apicurio/registry/services/RegistryConfigSource.java](https://github.com/Apicurio/apicurio-registry/pull/1526/files?authenticity_token=iPgvivIRLl%2FsUTiO2AY3pYTeNXi9avLtTZBuDfoTIuNCzWWrxlknlCe3XJaCIShtLl8QbTCLRumP50ZfB3M1Sg%3D%3D&file-filters%5B%5D=.java#diff-0c3b8ef97aecfdeb0ec8e30be755477f4c93a42229133693a2b9935ea258b7fa) in PR #1526 

I have attempted to get around this by various means but have had no success so far. Any advice appreciated!

**Comment by ajborley** [comment]
I have tried using the 2.1.3-SNAPSHOT versions of some of the app and common dependencies (rather than the 1.3.2 versions), but they require other changes and don't correctly use the 1.3.2 rest client (which I think is required to be able to call the v1 APIs).

**Comment by famartinrh** [comment]
I also spotted this.

yes, because we import rest client 1.3.2 , needed for rest api calls, that forces us to import registry-app 1.3.2 too. The only reason why we need registry-app dependency is to make use of `ArtifactTypeUtilProviderFactory` that's the only way to get the canonicalHash, which we have to provide it for import.

So the two solutions I can think of are:
- extract all the classes used by `ArtifactTypeUtilProviderFactory` into a separated module, so it can be imported without conflicts in the exportV1 tool. This will work for firsts and latests 2.x releases
- make the import process calculate the canonicalHash, that will require to include the ArtifactType in the content entity, as it's needed to obtain the canonicalHash. This will not work for firsts 2.x releases.

@Apicurio/developers wdyt?

**Comment by carlesarnal** [comment]
I thin that the right solution here is the first one. I spotted that situation in the past, that the only reason to import the app module is that one, and I think it’s time to extract that into a separate module.

**Comment by EricWittmann** [comment]
I think Miroslav may be already working on (2) - making canonicalHash optional.  But I'm in favor of that option if it's feasible.

**Comment by EricWittmann** [comment]
For the record, I **also** think that option (1) should be done.  :)

**Comment by ajborley** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/2027
