### ISSUE TITLE
Extract admin endpoints from the rest client to an admin client.

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#2026]

**Comment by jhughes24816** [comment]
Could someone please provide some details as to what this issue is about?

**Comment by famartinrh** [comment]
sure, it just means to separate the methods [here](https://github.com/Apicurio/apicurio-registry/blob/master/client/src/main/java/io/apicurio/registry/rest/client/RegistryClient.java) in two different interfaces, one for the `/admin` part of our API and another one for the rest

**Comment by famartinrh** [comment]
also important to mention that we should always have in mind backwards compatibility, and therefore do this kind of changes in a way that don't break user's code. We should first deprecate the methods in the old interface while creating a new Admin interface, and later on (i.e. two releases after) remove the deprecated methods

**Comment by jhughes24816** [comment]
Okay, thanks. Couple of follow up questions:

1. Currently going through the v1/openapi.json and v2/openapi.json, in v2 I found `/admin` end points. Are there any end points in v1 that would be considered admin e.g. possibly `/rules`? 
2. With the interfaces split, would it be useful to split the `RegistryClientImpl` in a similar way?

**Comment by famartinrh** [comment]
the v1 api is just kept for compatibility with old clients. the current interface `RegistryClient` and it's implementation only targets the latest version of our API, in this case v2.
