### ISSUE TITLE
Redoc not working with YAML

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry#2067]
If I upload an OpenAPI artifact with YAML instead of JSON the react UI for OpenAPI (Redoc) fails with:
`react-dom.production.min.js:209 SyntaxError: Unexpected token o in JSON at position 0`

This is caused by this line https://github.com/Apicurio/apicurio-registry/blob/a74e1995df7d59bca505395bbadbdf7941d26564/ui/src/app/pages/artifactVersion/components/tabs/documentation.tsx#L74

Maybe we could use something like https://www.npmjs.com/package/js-yaml ?

**Comment by famartinrh** [comment]
I just tested it with this example from here https://swagger.io/docs/specification/basic-structure/ and it works fine.
@dweber019 could you please share a openapi document that gives you this problem?

**Comment by famartinrh** [comment]
@dweber019 any updates on this?

**Comment by andreaTP** [comment]
Developing #2655 I took the time to verify this issue, with the latest `master` I cannot reproduce as the document is converted into `json` when uploading.

@dweber019 can you please verify?

**Comment by dweber019** [comment]
Verified with version 2.0.5 and works.
Uploaded some OpenApi version 3 spec in yaml and works.

**Comment by andreaTP** [comment]
Thanks for confirming @dweber019 !
