### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by wilvdb** [Apicurio/apicurio-registry#2106]
After configuring OpenId authentification, a redirection to keycloack should be performed, but CORS is blocking it.
I tried the below env variables:
* QUARKUS_HTTP_CORS_ORIGINS
* CORS_ALLOWED_ORIGINS
But no CORS policy is loaded by the ui.
Do you have an example on how to setup CORS origins for image apicurio-registry-mem version 2.1.4 Final ?

**Comment by EricWittmann** [comment]
I assume this is when you're trying to access the UI via a browser?

@carlesarnal any thoughts on this?

**Comment by carlesarnal** [comment]
Have you configured CORS in keycloak? If not, maybe it's actually Keycloak that's blocking your request, not Registry. You need to configure the API client allowed origins.

**Comment by EricWittmann** [comment]
@carlesarnal Do we need to update our documentation in this area?

**Comment by carlesarnal** [comment]
The `CORS_ALLOWED_ORIGINS` option is probably not documented yet since we added it recently. For other things, our current documentation along with Keycloak documentation should be sufficient.

**Comment by wilvdb** [comment]
Error was coming from a misconfiguration of keycloack.

**Comment by Storkycold** [comment]
> Error was coming from a misconfiguration of keycloack.

Would it be possible to acknowledge the example solutions? I'm stuck with the same problem.
