### ISSUE TITLE
Search by property value is not returning any results

### ISSUE THREAD

**Issue by wtrocki** [Apicurio/apicurio-registry#2125]
Acording to the docs format should be as follows:
https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm#operation/searchArtifacts

When using rhoas CLI (that uses API under the hood) we see that using `:` delimiter for map doesn't seem to work. 
It would be better to have propertyName and Value fields as well. 

![image](https://user-images.githubusercontent.com/981838/146736347-3a466c82-d2a3-4dbe-b63f-da275db5f1c5.png)

**Comment by EricWittmann** [comment]
We may not have actually implemented this feature yet.  :(  

@wtrocki what does ` It would be better to have propertyName and Value fields as well.` mean?

**Comment by wtrocki** [comment]
Ah.. this is just idea - instead of encoding property in `key:value` format we can have 2 arguments for key and value.

**Comment by famartinrh** [comment]
yep, we didn't implement that part.

indeed propertyName and Value is a good idea, but I'm afraid we cannot do it, that would mean changing the v2 API and breaking compatibility

**Comment by wtrocki** [comment]
Supporting both values will not break API but provide better alternative for future iterations.

FYI @rkpattnaik780

**Comment by wtrocki** [comment]
@famartinrh I'm happy to help with implementation, reviews etc. :)

**Comment by famartinrh** [comment]
> Supporting both values will not break API but provide better alternative for future iterations.

good suggestion, I'll implement it that way

**Comment by famartinrh** [comment]
Implemented search using `key:value` , some improvements to the API will implemented here https://github.com/Apicurio/apicurio-registry/issues/2187
