### ISSUE TITLE
There is no way to know how my JSON Schema fails the compatibility rules

### ISSUE THREAD

**Issue by craicoverflow** [Apicurio/apicurio-registry#2135]
When I upload a new JSONSchema artifact with breaking changes, it throws an error and prevents me from updating it (as expected).
However I have no way to know _why_ it fails, as the error just prints a basic error message.

<img width="1122" alt="Screenshot 2021-12-20 at 17 02 11" src="https://user-images.githubusercontent.com/11743717/146804767-a2d4b3c2-9592-44ae-a818-e1a75ce3a3cb.png">

It would be better to list out why compatibility fails.

**Comment by famartinrh** [comment]
I'm fixing this as part of other work I am doing.

How does this look?
![image](https://user-images.githubusercontent.com/46371672/147225556-bf4b6e21-f526-472d-9ac7-6436780a3cf1.png)

**Comment by craicoverflow** [comment]
That looks good! :)

**Comment by todor-kolev** [comment]
Hi, I'm actually wondering if there are known issues related to Json Schema compatibility rules? I tried to add a new version of a simple json schema with the only difference being an extra optional field that I added and got the same error as yours: 

Initial version:
```
{
  "$id": "https://example.com/geographical-location.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Longitude and Latitude Values",
  "description": "A geographical coordinate.",
  "required": [ "latitude", "longitude" ],
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    }
  }
}
```

New version (for which I got the above error):
```
{
  "$id": "https://example.com/geographical-location.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Longitude and Latitude Values",
  "description": "A geographical coordinate.",
  "required": [ "latitude", "longitude" ],
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "newOptionalField": {
      "type": "number"
    }
  }
}
```

I have Compatibility rule set to Backward and I am using Red Hat's hosted version of Apicurio Registry (https://console.redhat.com/application-services/service-registry)

Does that look like a bug or I am doing something wrong?

**Comment by jsenko** [comment]
Hi @todor-kolev The schemas you posted are not backwards compatible, even though it may seem that adding the optional property should be. Consider this counter example:
```json
{
  "latitude": 1,
  "longitude": 2,
  "newOptionalField": "not-a-number"
}
```
Which matches the first schema, but does not match the second.

**Comment by famartinrh** [comment]
well, actually if you try to update that artifact via the REST API it should return you an object describing the error.

**Comment by jsenko** [comment]
I agree that we should improve our error messages (not only displaying them, but also make them more explanatory). I'll add an issue to add explanations, because AFAIK the current diff report points out the place where the issue is, but not why.

**Comment by todor-kolev** [comment]
> Hi @todor-kolev The schemas you posted are not backwards compatible, even though it may seem that adding the optional property should be. Consider this counter example:
> 
> ```json
> {
>   "latitude": 1,
>   "longitude": 2,
>   "newOptionalField": "not-a-number"
> }
> ```
> 
> Which matches the first schema, but does not match the second.

Hey, thanks for your comment. 

You're absolutely right, I had forgotten to set `"additionalPorperties": false` in the initial version of the schema.
