### ISSUE TITLE
Add user-friendly explanations to the JSON compatibility checking

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#2160]
Consider this comment https://github.com/Apicurio/apicurio-registry/issues/2135#issuecomment-1008352289 . The output of the compatibility checker is as follows:
```
Difference(diffType=OBJECT_TYPE_PROPERTY_SCHEMAS_NARROWED, pathOriginal=, pathUpdated=/propertySchemasAdded, subSchemaOriginal=true, subSchemaUpdated=[NumberSchemaWrapper(wrapped={"type":"number"})])
```
While this may be helpful to find where the issue is, it does not explain well *why* the schemas are not compatible. Adding a user-friendly explanation would improve usability *and* would serve as a documentation for future changes in the library.

**Comment by famartinrh** [comment]
have into account the usage of the existing objects we have (RuleViolationError and a list of RuleViolationCause, with description and context). IMO it's important to do not change that object and try to make use of it as is now, that way our existing UI integration will continue working properly.

**Comment by jhughes24816** [comment]
I have been playing around with this a bit today, just starting to find my way around. Would this a be a suitable error message?
`RuleViolationException: Incompatible artifact: 3d76a98a-26d7-4afc-a2ba-60cf80a19b72 [JSON], num of incompatible diffs: {1}, list of diff types: [NUMBER_TYPE_MINIMUM_INCREASED/properties/age/minimum]`

**Comment by jsenko** [comment]
Hi, I would separate the diff type a bit from the path, i.e. `NUMBER_TYPE_MINIMUM_INCREASED at /properties/age/minimum`, but the error message looks good! Are you interested in contributing?

**Comment by jhughes24816** [comment]
Hi, Good idea to split it. I'll put a PR in later this morning.
