### ISSUE TITLE
Version deletion bug

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry#2185]
Hello 

Initially caused by Apicurio/apicurio-registry-content-sync-operator#36 moved here on request of @famartinrh 

I am using apicurio registry 2.1.5.Final with Kafka persistance.
Also I am using confluent compatibility API for my producer / consumers.

I've registered 2 versions of Avro schema via `Artifact` CRD and they displayed OK.

1. Then, I've used CC API to retrieve list of versions for my subject, list returns 2 item
2. I'm using CC API to delete latest version, deletion is OK
3. Getting list of versions now return 1 item (as expected)

But when I log in into UI - i don't see my artifact / subject at all. I've tried to restart both operator and UI - no effect.

So this is a bug I see now

* CC API returns subject and version
* UI doesn't display them at all

**Comment by EricWittmann** [comment]
@famartinrh I guess this can be closed, right?  If I'm wrong, please re-open it!  If I'm right, just ignore...

**Comment by eshepelyuk** [comment]
@EricWittmann why do you think it's closed ?
it is because [2.2.0.Final](https://github.com/Apicurio/apicurio-registry/releases/tag/2.2.0.Final) ?

**Comment by famartinrh** [comment]
well, but the commit with the fix  must be included in 2.2.0.Final, so this can be closed

**Comment by EricWittmann** [comment]
I think we're not always very good at including the stuff we've done in the changelogs.  That's something we're trying to get better at.

Could you try 2.2.0.Final and see if this issue is fixed?  If it's not, we can definitely re-open it.
