### ISSUE TITLE
Inconsistencies in ccompat/v6 layer for non-kafka schemas

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry#2191]
Hello

In Kubernetes, I am using Apicurio registry 2.5.1.Final and content sync operator with Kafka persistence.

We use the same registry instance as:
1. Confluent Schema Registry replacement by accessing `/apis/ccompat/v6` layer
1. generic schema storage for OpenAPI and GraphQL schemas

The issue can be reproduced by 

1. publish / auto publish schema for a kafka topic, named `my_topic-value`, without any version, so version is assigned automatically
1. publish OpenAPI schema, named `my-openapi` with valid semantic version e.g. `2.3.0`

When calling `/apis/ccompat/v6/subjects` - Apicurio registry returns

```json
[
    "my-openapi",
    "my_topic-value"
]
```
When calling `/apis/ccompat/v6/subjects/my_topic-value/versions` - the versions are returned
But, when calling  `/apis/ccompat/v6/subjects/my-openapi/versions`  - registry returns 404

This causes tools that are working with confluent compatible schema registries and uses `/subjects` to introspect the registry to fail.
Also the behavior is inconsistent.

I believe Apicurio registry should not return non-kafka schemas at all, when working in `/ccompat` mode.
Maybe it worth introducing mandatory field for artifacts that marks artifact to be used by Kafka, i.e. `isKafkaSchema`

Because someone could use Apicurio registry to publish Avro / JSON / Protobuf schemas that are not used by kafka topics at all, so those schemas must not be returned by `ccompat/v6` API.

**Comment by famartinrh** [comment]
sounds like our ccompat layer is not handling string versions properly, about not returning non-kafka schemas I don't know... @Apicurio/developers  wdyt?

**Comment by eshepelyuk** [comment]
Can you please for now just filter out everything that is not json/protobuf/avro from ccompat layer ?
Yes, it not a  propee sooution but it stil makes sense to do it and it probably solve many similar issues.

**Comment by carlesarnal** [comment]
The `getVersions` operation is currently filtering out those versions with a non-numeric value. I think we should also filter those artifacts in the subjects operation.

**Comment by ievgenii-shepeliuk** [comment]
> The `getVersions` operation is currently filtering out those versions with a non-numeric value. I think we should also filter those artifacts in the `subjects` operation.

please
