### ISSUE TITLE
Add operation to get ALL groups in apicurio registry rest api v2

### ISSUE THREAD

**Issue by ChenShuai1981** [Apicurio/apicurio-registry#2196]
I want to implement apicurio registry as Flink Catalog and mapping GROUP into DATABASE, there is an interfaces to implement as `List<String> getDatabases()`, but I can NOT find how to fetch ALL groups in apicurio registry rest api.

**Comment by famartinrh** [comment]
I think our REST API does not provide an operation to do this, but If I remember correctly the CNCF Schema Registry API (which we support as well) exposes an operation like that. https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/cncf/v0/openapi.json#L8

**Comment by ChenShuai1981** [comment]
Thanks for your suggestion. But I can NOT find how to use `SchemagroupsResource.getGroups` interface in apicurio-registry-app project, is there any example?

**Comment by famartinrh** [comment]
that API is exposed under i.e http://localhost:8080/apis/cncf/v0/...

So for that call it would be I think  http://localhost:8080/apis/cncf/v0/schemagroups

Btw I think if you hit http://localhost:8080/apis in your registry you will get apidocs for all the exposed APIs

**Comment by ChenShuai1981** [comment]
Oh yes it works. But I found a small display problem when hitting `http://localhost:8080/apis/cncf/v0#operation/getGroups` apidocs page, the api address shows `http://localhost:8080/schemagroups` after clicked "GET /schemaGroups" in the right panel. It is incorrect, the correct one is `http://localhost:8080/apis/cncf/v0/schemagroups`. The same issue happens on the other api addresses.

**Comment by EricWittmann** [comment]
This might be done now in the V2 API - we should verify.

**Comment by EricWittmann** [comment]
I realize this is an old issue, but I've been doing a bunch of work on the v3 API and listing groups is definitely possible in v3.  Full group management exists now - with metadata and everything.  :)
