### ISSUE TITLE
Need for thread pool for consumers/producers calls

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#2199]
Thanks for the answer Carles. I understand, my concern is that going from 1 on-demand rest call to 1 thread per consumer/producer is a huge change on services consuming many topics/partitions. To give you an example, our service had ~1500 threads consuming/producing, and now it got doubled and our stress tests started failing with the cpu spiking with ~3k threads. 
My main question is, being that is a plain REST call, do we need such a thread pool to do them? I can start an issue with this to formalize the question.

_Originally posted by @tomasAlabes in https://github.com/Apicurio/apicurio-registry/discussions/2154#discussioncomment-2041420_

**Comment by tomasAlabes** [comment]
@famartinrh any idea when this is going to be discussed? At this point we're considering stop using Apicurio.

**Comment by carlesarnal** [comment]
Hi @tomasAlabes,

You can already re-use the rest-client across producers/consumers. When creating your serializers/deserializers, you can pass the Registry Client to be used with one of this options (example with avro, but the same constructors are available for protobuf and json):

- https://github.com/Apicurio/apicurio-registry/blob/master/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroKafkaDeserializer.java#L56
- https://github.com/Apicurio/apicurio-registry/blob/master/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroKafkaSerializer.java#L67

By using those constructors the client can be re-used across serializers/deserializers.

**Comment by carlesarnal** [comment]
Closing as I provided what should be a viable solution to this problem. If you feel that is not the case, please, re-open.
