### ISSUE TITLE
Add UI support for managing dynamic config properties

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#2217]
We are adding the ability to turn some of the application configuration properties (which are typically set during deployment of the app) into dynamic properties.  Dynamic properties are simply existing configuration properties that can be changed at runtime by an admin level user via the REST API.

This task is about adding support for managing the values of these properties in the UI.

**Comment by KarolisCibulskis** [comment]
Hello, ticket title sounds very promising, will it solve UI authorization with any OIDC issue?
https://github.com/Apicurio/apicurio-registry/discussions/1590#discussioncomment-1611002
