### ISSUE TITLE
UI tweaks for metadata labels

### ISSUE THREAD

**Issue by smccarthy-ie** [Apicurio/apicurio-registry#2231]
Hi, 
Some minor tweaks to the UI labels for metadata:

-  Can we use "metadata" in all UI labels?  :) 
 From the IBM Style Guide: 
-- _Do not use meta data, meta-data  noun_  
-- _Use "metadata". Write as shown: one word, unhyphenated_
   For example, the  **Edit Artifact Meta-Data** modal should be **Edit artifact metadata**.
   
![Screenshot from 2022-02-02 18-29-37](https://user-images.githubusercontent.com/29098561/152219753-382bb78e-4ea3-4a6b-97a0-fafc5c1ed215.png)

- Can we uses sentence case for all modals (i.e., **Edit Artifact Metadata** should be **Edit artifact metadata**)? 

- Should the point size for **Version Metadata**  and **Content Rules** labels be the same? **Version Metadata** looks bigger.
![Screenshot from 2022-02-02 18-29-42](https://user-images.githubusercontent.com/29098561/152220073-d323021e-bd1e-4429-be13-6df857325493.png)

Thanks!

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/2235
