### ISSUE TITLE
JSON schema validity checking inconsistent with compatibility checking

### ISSUE THREAD

**Issue by bobmorley** [Apicurio/apicurio-registry#2236]
Playing around with the in-memory version of the registry. Using some sample json I found online, I create an artifact for the schema without issue. However, when I adjust it to upload a new version it fails validating some untouched portion.

`            "warehouseLocation": {
                "description": "Coordinates of the warehouse with the product",
                "$ref": "http://json-schema.org/geo"
            },
`

The failure details:
`FileNotFoundException: http://json-schema.org/geo`

It appears the schema validation on the `upload artifact` is inconsistent with the `upload new version`. (Note the reference here does indeed result in a 404).

Expectation: `upload artifact` should fail when the version of the schema provided is not valid.

**Comment by bobmorley** [comment]
Note: Removing this and attempting another "new version" results in more validation that isn't occurring on the initial creation of the artifact.

`SchemaException: #/items/properties/price/exclusiveMinimum: expected type: Number, found: Boolean`

**Comment by EricWittmann** [comment]
What rules do you have enabled and at what level (global or per-artifact rules).

**Comment by bobmorley** [comment]
I had global rules enabled and set to "Full" and "Full Transitive" respectively for Global rules (although I might have had it set to Backwards at one point). Once I had the artifact uploaded, I did enable and override there (but likely had the same values set).

**Comment by EricWittmann** [comment]
Well I'm wondering which rule (if any) is causing the issue to be caught on update vs. create.  The Compatibility rule doesn't run for create operations I don't think (there's no previous version to compare to).  The Validity rule definitely will run.  Do you have that enabled at either level?

**Comment by bobmorley** [comment]
Yes, both were enabled globally.
I have attached a zip with two json schemas. I created a new artifact with the "v1" file, using the settings I show below, and it created properly. When I attempted to "Upload new version" and use "v2" it resulted in this error:

`SchemaException: #/items/properties/price/exclusiveMinimum: expected type: Number, found: Boolean`

Now, if I then go into `Global Settings` and disable the Compatibility rule, it will upload properly. Even though Validity rule remains set to "Full".

My expectation, is this bad schema should be caught through validation (as exclusiveMinimum changed from a Boolean to a Number as of draft-07). Once you have it saved this way, with Compatibility rule on, you can never fix it as the "bad" schema is in a previous version.

<img width="1646" alt="CleanShot 2022-02-04 at 14 40 34@2x" src="https://user-images.githubusercontent.com/30734141/152592739-8e71471d-6a21-4dfe-8f45-467be20b146a.png">

[schemas.zip](https://github.com/Apicurio/apicurio-registry/files/8005801/schemas.zip)

**Comment by EricWittmann** [comment]
Thank you for this information!  It's extremely helpful and very clear.  We will need to investigate our implementation for Validity of JSON Schema.  My suspicion (without looking at the code) is that we have not yet implemented "FULL" validity for JSON Schema, but instead only "SYNTAX" validity exists.

**Comment by EricWittmann** [comment]
Note: I have a PR that fixes this here:  https://github.com/Apicurio/apicurio-registry/pull/2353

When I try to register your example schema, I get this result (when global validity rule is set to FULL):

![image](https://user-images.githubusercontent.com/1890703/159054459-319be88b-9851-4b02-a550-a1dd7c24e70a.png)
