### ISSUE TITLE
Maintenance: Maven build checkup

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#226]
Go over the POM files, profiles, tests etc. in case there is some maintenance work needed.  At the very least, we need to make sure that `mvn clean install` will build, test, and package all of the supported storage variants.  Right now the variants are all separated out into profiles, because the tests for "streams", "kafka", and "infinispan" will all fail because they all depend on external systems to function.  We need to work on standing up those systems automatically so that tests can be run successfully.

**Comment by EricWittmann** [comment]
I think this epic is no longer needed.  Improvements have been made and we have at least one pending PR to address the issue of building/testing the other profiles without separately standing up the external systems they rely on.
