### ISSUE TITLE
Duplicate update in JPA?

### ISSUE THREAD

**Issue by alesj** [Apicurio/apicurio-registry#227]
@jsenko why do we do duplicate persist here?
First with nextVersion, then with null as version ... ?!

https://github.com/Apicurio/apicurio-registry/blob/e74d5fa517d0889890fdc34e8bd30e500190687b/storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java#L215

**Comment by jsenko** [comment]
The first metadata entity represents metadata for the `artifact version`, the second metadata that is persisted is for `artifact` (i.e. all the versions).

**Comment by alesj** [comment]
OK, I see ... this should be a lot more optimised ... less inserts/updates ... I'll see what can be done.

**Comment by EricWittmann** [comment]
@alesj this was fixed in a recent PR, was it not?

**Comment by alesj** [comment]
@EricWittmann yes, this is fixed
