### ISSUE TITLE
Canonical schemas in ccompat/v6 API

### ISSUE THREAD

**Issue by janvyhnanek** [Apicurio/apicurio-registry#2279]
Hello,
if an avro schema is registered with canonicalize=true, it can contain new lines and other white spaces and can be later retrieved via POST API apis/registry/v2/groups/default/artifacts/{artifactId}/meta?canonical=true, if you put schema from generated java into the body. No problem in this case.

But it seems to me that the behaviour is different in ccompat API - schema registered with white spaces cannot be found via ccompat/v6/subjects/{artifactId} when you put schema from java class into the body. Is there a way to make canonization working for ccompat API or is it necessary to register schema exactly as it is in generated java class? If it is really necessary to register schema in the same format as in java class, it could become a bit complicated for registration via maven plugin - you define your schema in a json file with newlines then you have to transform it (ideally run avro java generator to be sure) and copy the transformed schema into the file from which the schema will be registered via maven plugin. Is there a better way to register schema compatible with ccompat API?

This issue is somehow related to https://github.com/Apicurio/apicurio-registry/issues/300, but I believe this issue is more specific, the canonization of avro itself implemented in apicurio (in registry/v2 API) is sufficient for our needs. 

Thanks

**Comment by janvyhnanek** [comment]
We have found another issue with normalization which is very unpleasant when working with java and .net. Very popular among java developers is to use <stringType>String</stringType> in java avro generator which generates String instead of CharSequence. But this generates a construction "avro.java.string" : "String" into the $SCHEMA variable used for schema lookup so the schema must be registered with this construction - this behaviour is both in apicurio and  java confluent serializator. The problem is that confluent serializator for .net works differently - it removes all java annotations before schema lookup and such schema cannot be matched with the schema registered. 

Would it be possible to match schema without java specific constructions with schema registered with such construction? Besides "avro.java.string" I am thinking of "javaAnnotation" field in avro (though I have not tested this one in .net yet).

**Comment by vsevel** [comment]
this is an issue for us as well. we have SB applications trying to fetch the schema registered through the synch operator, and failing with `{"message":"No artifact with ID 'X' in group 'null' was found.","error_code":40401}` when doing the `/apis/ccompat/v6/subjects/<subject>` even with `normalize=true`.
what options do we have @EricWittmann ?
thanks

**Comment by carlesarnal** [comment]
First of all, sorry for the late reply; many things are happening on our side. As of today, there is no way to address this behaviour in the ccompat api other than to register the schema without the spaces and then it will be retrieved with no issues. Then, we have two alternatives:

1. Switch to Apicurio tooling. We offer a set of tooling (serdes utilities, maven plugin etc) that use our api and thus there should be no problem using them.
2. As you may have noticed, we implement, for now, version 6 of the confluent schema registry api, thus why the normalize option is not working in the ccompat api, since that parameter does not exist in that version. That said, we're planning to upgrade to the new version, so that should solve this problem as well.

Thanks

**Comment by carlesarnal** [comment]
> We have found another issue with normalization which is very unpleasant when working with java and .net. Very popular among java developers is to use String in java avro generator which generates String instead of CharSequence. But this generates a construction "avro.java.string" : "String" into the $SCHEMA variable used for schema lookup so the schema must be registered with this construction - this behaviour is both in apicurio and java confluent serializator. The problem is that confluent serializator for .net works differently - it removes all java annotations before schema lookup and such schema cannot be matched with the schema registered.
> 
> Would it be possible to match schema without java specific constructions with schema registered with such construction? Besides "avro.java.string" I am thinking of "javaAnnotation" field in avro (though I have not tested this one in .net yet).

This sounds to me like a completely unrelated issue so please, open a new GH issue and we will take a look, thanks!

**Comment by janvyhnanek** [comment]
> First of all, sorry for the late reply; many things are happening on our side. As of today, there is no way to address this behaviour in the ccompat api other than to register the schema without the spaces and then it will be retrieved with no issues. Then, we have two alternatives:
> 
> 1. Switch to Apicurio tooling. We offer a set of tooling (serdes utilities, maven plugin etc) that use our api and thus there should be no problem using them.
> 2. As you may have noticed, we implement, for now, version 6 of the confluent schema registry api, thus why the normalize option is not working in the ccompat api, since that parameter does not exist in that version. That said, we're planning to upgrade to the new version, so that should solve this problem as well.
> 
> Thanks

Thanks for reply. 
Ad 1) it is not really an option for us since Apicurio provides tooling only for java greater than 8 and we use many other technologies in our systems.
Ad 2) is really confluent 6 API implementation working in a way that it does not match schema without whitespaces with schema registered with a whitespace? I would expect it should work by default without need of a switching parameter in API, but I have not tested confluent implementation though.

**Comment by EricWittmann** [comment]
Some good news here might be that @carlesarnal has opened a PR to support v7 of the confluent api.  I think that helps with this issue, no?

**Comment by carlesarnal** [comment]
There are now two options here. One is to use the new v7 api, which implements the normalize parameter in the ccompat api. The second option is to use the feature introduced [here](https://github.com/Apicurio/apicurio-registry/pull/2791). Both possibilities should solve this issue so I'm closing it as completed.

**Comment by janvyhnanek** [comment]
Just one more question, do you think v7 confluent API might help with the problem with java annotations in avro or should I create a separate topic? I could not find much about changes confluent API specification. (The problem is that e.g. C# clients are trying to look up the schema without java annotations which have been registered with the java annotations, so the lookup fails)
