### ISSUE TITLE
Document: content-types for supported formats

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#23]
We're going to be storing artifacts of the following formats in the registry:

* JSON Schema
* Avro
* Protobuff
* OpenAPI
* AsyncAPI

Most of these are in JSON format (or YAML which can easily be converted).  But at least Protobuff is not.  So there is an open question about how to handle the different content types when pushing content into the registry via the API and then returning it later.

The first step is to identify the actual content types for each format.  And then additionally how to handle that in the API itself.  In order to make it as simple as possible, we could try to figure out the type based on the following (in order):

* custom Request header e.g. `X-Registry-Type`
* check the Request's Content-Type for something that disambiguates the content.  For example the request `Content-Type` might be `application/json+openapi`
* try to figure out the type from the content itself.  This will work well for OpenAPI and AsyncAPI and probably Protobuff, but I'm not sure what else.

**Comment by EricWittmann** [comment]
I can't seem to find a mime-type for `*.proto` files - does anyone know what that would be?  Not the mime-type of data encoded using protobuff, but rather the content-type of a Protobuff definition file.

**Comment by EricWittmann** [comment]
@alesj and @jsenko can you guys have a look at this issue?  Any thoughts on the mime-type for protobuff's `.proto` files would be quite helpful.

**Comment by alesj** [comment]
application/x-protobuf

**Comment by EricWittmann** [comment]
`application/x-protobuf` with just one "f"?

**Comment by EricWittmann** [comment]
Yep - confirmed, thanks.  There's an ALT as well apparently:

https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/protobuf/ProtocolBuffers

**Comment by alesj** [comment]
https://stackoverflow.com/questions/30505408/what-is-the-correct-protobuf-content-type
