### ISSUE TITLE
Disable integration tests for changes that don't need them

### ISSUE THREAD

**Issue by craicoverflow** [Apicurio/apicurio-registry#2313]
I noticed when adding #2265 that the full suite of integration tests and other jobs executed when a file which would not affect these was changed.

These jobs can be resource intensive, and I think we should consider disabling workflows when they are not required to reduce carbon footprint.

**Comment by EricWittmann** [comment]
@riprasad Low priority task.  This probably requires some collaboration with @Apicurio/developers and Ondrej to accomplish.  We need to figure out how we can choose which tests to run based on the changeset in a PR.
