### ISSUE TITLE
Build multi-arch docker images

### ISSUE THREAD

**Issue by rtimush** [Apicurio/apicurio-registry#2334]
Hello,

It would be nice to have registry images built for multiple platforms, particularly `linux/arm64`.

The base `ubi8/openjdk-11` is already multi-platform, so it seems to be mostly about the CI configuration. I tested building `linux/arm64` images locally and they were built without any issues.

**Comment by riprasad** [comment]
With this change, Service Registry Images will be available for multiple linux platforms i.e. `linux/amd64`,`linux/arm64`,`linux/s390x`,`linux/ppc64le`
