### ISSUE TITLE
Provide installation package for Kafka Connect connectors

### ISSUE THREAD

**Issue by jpechane** [Apicurio/apicurio-registry#242]
If apicuro converte is going to be used by Kfka Connect it needs manual assembling of JARs and placing them to the connector directory. It would be thus useful to publish `tar.gz`/`zip` artefact that will contain all the necessary files to it can be just extracted in a connecotr library.

The package should contain
- convertor module JAR file
- convertor module dependencies (inclding transtiitve) with the following list (and transaitive excluded)
-- `org.apache.kafka:kafka-clients`
-- `org.apache.kafka:connect-api`
-- `org.apache.kafka:connect-json:jar`

Right now it is probably unfeasible to provide convertor for any plugin by [placing it into the Kafka's lib directory so we can exclude the scenario.

**Comment by jpechane** [comment]
Added PR - https://github.com/Apicurio/apicurio-registry/pull/243

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/243
