### ISSUE TITLE
Investigate skipping GH Actions workflow (or workflow steps) for PRs when labeled

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#2432]
It would be really useful if we could add a label to a PR (we currently use `DO NOT MERGE`) to indicate that a PR should be ignored.  It would be nice if the GH actions would **not** run (be skipped) if a PR is labeled as such.

**Comment by riprasad** [comment]
@EricWittmann Do we add `DO NOT MERGE` label after the PR is opened?
