### ISSUE TITLE
Change the compatibility REST endpoint name

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#246]
Currently we have a compatibility layer with the confluent schema registry that lives at the endpoint `/confluent` - we should rename that to `/ccompat`.

FHI to @smccarthy-ie in case this is documented.

**Comment by alesj** [comment]
Why rather criptic "ccompat" then self-explanatory "confluent" ?

**Comment by EricWittmann** [comment]
I'm open to other names, but PMs have strongly suggested we avoid potential copyright/trademark issues.  Which seems reasonable.

**Comment by smccarthy-ie** [comment]
Thanks Eric. That endpoint not called out explicitly in the doc (but it does link to a developer blog post on this topic which mentions it).

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/249
