### ISSUE TITLE
Registry crashed with "An illegal reflective access operation has occurred"`

### ISSUE THREAD

**Issue by PlugaruT** [Apicurio/apicurio-registry#2470]
Running the latest version `2.2.3` with SQL storage and it seems that from time to time the application crashed with this exception:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
```
Not sure how to debug this further.
Note that it was also happening with older version, like `2.0.1`

**Comment by EricWittmann** [comment]
These are warnings only, which I would not expect to result in a crash.  Do you have a full server log you can attach?  And could you enable debug logging?  If none of that helps we may need to figure out how to configure the app to generate a thread/heap dump when the jvm crashes.

WDYT @jsenko and @carlesarnal ?

**Comment by PlugaruT** [comment]
@EricWittmann yes, you are right. It's indeed not crashing because of this, it was something else, but because this were the only logs before the app was killed, I assumed that this was the reason.

**Comment by EricWittmann** [comment]
OK that's good news (although we should still investigate that warning).  What was the actual cause of the crash??  Now I'm super curious. :)

**Comment by jsenko** [comment]
From a quick search, it seems that the error is related to the Java module system. The target of reflection must be exposed by the module. Found this issue https://github.com/rhuss/jolokia/issues/394
> Tbh, Jolokia has not yet been ported to Java 11 (nor really tested). This is on the todo list, but currently, I'm buried under work so that this has no high priority for me at the moment.
