### ISSUE TITLE
Backup/Restore kafkasql based Apicurio-Registry installation

### ISSUE THREAD

**Issue by christofluethi** [Apicurio/apicurio-registry#2491]
Hi There

Is there a recommendation/guideline for backup/restore of an existing apicurio registry? 

I'm thinking about the following:
- backup using an import/export utility (i think there was one for V1?) Is there any documentation about such a tool in V2?
- backup underlying kafkasql-journal topic

In our case mirroring the topic is not an option.

Thanks

**Comment by carlesarnal** [comment]
Hi @christofluethi,

As you correctly pointed out, for migrating from V1 to V2 we have a standalone tool that creates a zip file that can then be used to import schemas into V2.

In latest versions, there's no tool but more a feature in the UI (and, of course, the api) where you have the option to download all the artifacts in a particular installation and also the option to import them (screenshot attached). Those feature are also supported in the registry client, in case that helps.

![imagen](https://user-images.githubusercontent.com/12640103/167839146-d122b2cd-714f-44f1-b440-c1d501e209ba.png)

**Comment by EricWittmann** [comment]
+1 to the info Carles provided.  In addition, you can use the REST API if you want to automate the backup of the registry content.  The REST API endpoint is here:

https://www.apicur.io/registry/docs/apicurio-registry/2.0.x/assets-attachments/registry-rest-api.htm#operation/exportData

You will need an admin level user to perform that REST API call successfully.

As for backing up the topic, that's sadly outside my area of knowledge.  I'm not sure what the equivalent of a DB backup is in the Kafka world.  But whatever that might be is what you could do.  If Mirroring is the equivalent of a DB backup for Kafka, and if you cannot do that, then using the export API is your best bet.

**Comment by EricWittmann** [comment]
(Closing this as "answered" but feel free to keep the conversation going or re-open if needed)
