### ISSUE TITLE
Unable to upload GraphQL  artifact

### ISSUE THREAD

**Issue by mani-nandipaati** [Apicurio/apicurio-registry#2517]
Dear Team,

I am getting the below exception while uploading below GraphQL

```
{
  name
  age
}
```

**Error**:
`SchemaProblem: errors=[The schema definition text contains a non schema definition language (SDL) element 'OperationDefinition']`

Could you please help us here?

Thank you

**Comment by EricWittmann** [comment]
@wtrocki - do you know what this means?  I'm not really a GraphQL guy but maybe you will know! :)

Note: I was able to reproduce this but only once I enabled the Validity rule in Registry (obviously).

**Comment by wtrocki** [comment]
hi @mani-nandipaati 

Apicurio registry is designed to store GraphQL schema. Schema to be valid must consist of:

- Valid types (type User etc.)
- Query Object (Mutations are required in old versions of spec)

Input that have been provided represent valid GraphQL Document which is client side query. Apicurio registry in current form cannot be used to store client side queries.
