### ISSUE TITLE
JSONObject["refrencedJsonObject"] not found. 

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#2550]
On running the below provided example after commenting line number 86  //citizen.setCity(city); I got below error.
This is scenario where refrence schema is optional in main schema as in case of Citizon.json schema in below example.
https://github.com/Apicurio/apicurio-registry-examples/blob/292a17cee4da822b26f463b4da93174e2674c45e/serdes-with-references/src/main/java/io/apicurio/registry/examples/references/JsonSerdeReferencesExample.java

Looks like issue lies in below code always expect reference schema object to be present in the JSON data.

https://github.com/Apicurio/apicurio-registry/blob/d2831fa03d7054164a27a5d70c71b9567fa6c298/serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchema.java#L242

**Comment by carlesarnal** [comment]
I have confirmed this, the attached PR should fix the issue. Thanks!

**Comment by Gourav2912** [comment]
Thank you @carlesarnal . Hoping for merge with Master soon...
