### ISSUE TITLE
apicurio-registry keycloak login continue relogin

### ISSUE THREAD

**Issue by ly123-liu** [Apicurio/apicurio-registry#2558]
apicurio-registry version: apicurio-registry-sql-2.2.3

apicurio-registry use keycloak to login , configured with docs: https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/getting-started/assembly-configuring-the-registry.html

our apicurio-registry config:
env:
  REGISTRY_DATASOURCE_URL: jdbc:postgresql://localhost:15435/apicurio
  REGISTRY_DATASOURCE_USERNAME: xxxx
  REGISTRY_DATASOURCE_PASSWORD: xxxx
  AUTH_ENABLED: 'true'
  KEYCLOAK_URL: https://kc-dq.frontnode.net/auth
  KEYCLOAK_REALM: yingmi.cn
  KEYCLOAK_UI_CLIENT_ID: 'apicurio-ui'
  KEYCLOAK_API_CLIENT_ID: 'apicurio'
  KEYCLOAK_API_CLIENT_SECRET: '22c9560d-7bcd-48b2-9bf7-7c2282c4e730'
  REGISTRY_AUTH_ADMIN_OVERRIDE_TYPE: 'role'
  REGISTRY_AUTH_AUTHENTICATED_READS_ENABLED: 'true'
  CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED: 'true'
  REGISTRY_PROXY_ADDRESS_FORWARDING: 'true'
  REGISTRY_UI_CONFIG_APIURL: 'https://localhost/apis/'
  ROLE_BASED_AUTHZ_ENABLED: 'true'
  REGISTRY_LOG_LEVEL: DEBUG
  ENABLE_ACCESS_LOG: 'true'

when open apicurio-regsitry  , redirect to keycloak login page, and when we submit user/pass , we can see redirect to apicurio-registry successful ,and then start to redirect to keycloak login again, seems apicurio-regsitry not set its self token.

image: 
![WeChatWorkScreenshot_10aeb07e-84ea-4326-a4e6-3048f9f93622](https://user-images.githubusercontent.com/57338370/172598098-9111a15d-79bb-4955-85d0-ff2ff2c6d774.png)

**Comment by carlesarnal** [comment]
Hi,

The keycloak support is a well tested feature. To first confirm that the integration with the API is working, I would recommend testing it with a tool like postman or curl. Once that is confirmed, please, check the clients configuration in Keycloak. The Keycloak version is also important, specially depending on your configuration.

**Comment by ly123-liu** [comment]
apicurio login with keycloak seems ok, seems our web origin is not set to + , thanks
