### ISSUE TITLE
Validate references in serdes only if subschema is present

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#2583]
implementation should be if optional complex object is present it should be validated if not present ignore for validation.

**Comment by Gourav2912** [comment]
@carlesarnal @EricWittmann Do you know if this can be fixed soon?

**Comment by carlesarnal** [comment]
@Gourav2912 I'm planning to work on this today and we will cut a release this week.

**Comment by Gourav2912** [comment]
@EricWittmann @carlesarnal Thanks for the solution, but i feel this is not complete solution yet as subschema validation is still not completely correct if subschema is ARRAY property, it is working only for type object.

**Comment by carlesarnal** [comment]
@Gourav2912 I have created a separated issue and opened a PR for solving that as well. If you have any other problems, please, open a new GH issue. Thanks!
