### ISSUE TITLE
APICurio Logs

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#2590]
Hello,

I want to know how can i enable logs for APICurio in a file or via log4j2 for debugging purpose ?

Thanks in advance.

Regards,
Gourav

**Comment by jsenko** [comment]
Hi,
Registry is a Quarkus application, so the general rules for Quarkus apply. This is a general guide for how to pass configuration options https://quarkus.io/guides/config-reference#configuration-sources and this guide is specifically for logging https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus.log.file-file-logging . So you should be able to pass options like `QUARKUS_LOG_FILE_ENABLE="true"` and `QUARKUS_LOG_FILE_PATH="path/to/my/file"`.

**Comment by EricWittmann** [comment]
I am closing this as "answered".  :)  Please feel free to re-open if the above does not work!
