### ISSUE TITLE
Implement reference-related rules

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#2594]
As an improvement to the *Artifact References* feature, we could create a new set of rules:
- *Reference Validity Rule* - Ensure that there are no references in the content that are not mapped, and/or there are no mappings that do not correspond to any references in the content.
- *Reference Integrity Rule* - which would prevent a dependency to be deleted if there is a reference pointing to it.

**Comment by EricWittmann** [comment]
This is now done.
