### ISSUE TITLE
Apicurio-Registry: Compatibility Rules are not applied on OpenAPI schemas

### ISSUE THREAD

**Issue by marcin-brzozowski** [Apicurio/apicurio-registry#2654]
Hi,

The compatibility rules for OpenAPI seem not to be working. No validation errors are raised when uploading a new schema version that introduces a breaking change.

I tried introducing different breaking changes, removing whole paths, removing required properties etc. In any case was I able to lead to a failure in validation during an artifact update.

### Steps to reproduce:
1. Setup Apicurio Registry (I use the https://www.apicur.io/registry/try-live/)

2. Upload a new artifact (I used the Pet Inventory sample: https://petstore.swagger.io/v2/swagger.json)
![image](https://user-images.githubusercontent.com/10519477/180972391-8ff83e91-bffa-488e-969e-54a700bb9231.png)

    
3. Enable Compatibility Rules: Backward
![image](https://user-images.githubusercontent.com/10519477/180973813-ca15a9d6-3dee-45db-a170-0a34ae88178d.png)

4. Introduce a breaking change. I removed on of the required properties: **name** from the definition of the **Pet** response resource.

    ```json
    {
    ...
    "Pet": {
        "type": "object",
        "required": [
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int64"
            },
            "category": {
                "$ref": "#/definitions/Category"
            },
            "tags": {
                "type": "array",
                "xml": {
                    "wrapped": true
                },
                "items": {
                    "xml": {
                        "name": "tag"
                    },
                    "$ref": "#/definitions/Tag"
                }
            },
            "status": {
                "type": "string",
                "description": "pet status in the store",
                "enum": [
                    "available",
                    "pending",
                    "sold"
                ]
            }
        },
        "xml": {
            "name": "Pet"
        }
    },
    ...
    }
    ```
    </details>
5. Upload the new version
![image](https://user-images.githubusercontent.com/10519477/180972542-edea6d1a-c0e0-43a7-b1bc-a43fe5da4fea.png)

### Expected Result

Upload fails due to validation error (missing required **name** property)

### Actual Result

Upload succeeds

### Apicurio Registry Version
```json
{
    "name": "apicurio-registry",
    "description": "High performance, runtime registry for schemas and API designs.",
    "version": "2.2.6-SNAPSHOT",
    "builtOn": "2022-07-22T16:37:58Z",
    "buildNumber": "46"
}
```

**Comment by jsenko** [comment]
Hi @marcin-brzozowski, unfortunately, Registry does not yet support compatibility rules for OpenAPI. See this [documentation page](https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-registry-reference.html#registry-rule-maturity-matrix_registry) for more details. We're tracking this issue as https://github.com/Apicurio/apicurio-registry/issues/15 , and we would welcome a community contribution in this area if you are interested.
