### ISSUE TITLE
Not respected References order causes schemaParser failure

### ISSUE THREAD

**Issue by merlor** [Apicurio/apicurio-registry#2676]
In class AbstractSchemaResolver there is the resolveReferences method:
```
    protected Map<String, ParsedSchema<S>> resolveReferences(List<io.apicurio.registry.rest.v2.beans.ArtifactReference> artifactReferences) {
        Map<String, ParsedSchema<S>> resolvedReferences = new HashMap<>();
        artifactReferences.forEach(reference -> {
            final InputStream referenceContent = client.getArtifactVersion(reference.getGroupId(), reference.getArtifactId(), reference.getVersion());
            final List<io.apicurio.registry.rest.v2.beans.ArtifactReference> referenceReferences = client.getArtifactReferencesByCoordinates(reference.getGroupId(), reference.getArtifactId(), reference.getVersion());
            if (!referenceReferences.isEmpty()) {
                final Map<String, ParsedSchema<S>> nestedReferences = resolveReferences(referenceReferences);
                resolvedReferences.putAll(nestedReferences);
                resolvedReferences.put(reference.getName(), parseSchemaFromStream(reference.getName(), referenceContent, resolveReferences(referenceReferences)));
            } else {
                resolvedReferences.put(reference.getName(), parseSchemaFromStream(reference.getName(), referenceContent, Collections.emptyMap()));
            }
        });
        return resolvedReferences;
    }
```

Here it's really important that the records in resolvedReferences are in the correct order (nestedRefences must be before the initial reference in order to avoid parser failure) and that the order will be maintained.

The problem here is that an HashMap is used but, according with Java documentation, it doesn't guarantee a predictable order:
https://docs.oracle.com/javase/6/docs/api/java/util/HashMap.html

In fact, in our projects, the schemaParser fails because It tries to parse a schema before his references.

A possible solution might be to use LinkedHashMap that, again according to Java documentation, keep the correct order:
https://docs.oracle.com/javase/10/docs/api/java/util/LinkedHashMap.html

**Comment by fabiobrz** [comment]
Hi @merlor - sorry for chiming in here, but I found this issue intresting and played a bit around it.

I noticed an integration test that is expected to verify serializing/deserializing object instances that have references, i.e.: https://github.com/Apicurio/apicurio-registry/blob/master/app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java#L204

So basically I decided to give it a try in order to have a reproducer that would support your analysis (HashMap vs. LinkedHashMap) and came up with a modified version of such tests, that creates a 4-level references chain, see https://github.com/fabiobrz/apicurio-registry/commit/b7fe132d5d327407ca3a0dde562e1bf2e6976153

That being said, though, I keep getting a green bar whren executing the test. Do you have or can provide a minimum viable case that could be used as a reproducer?
Or did I miss your point altogether and shpould focus on some different test case?

**Comment by merlor** [comment]
@fabiobrz thank you for your quick response, I took a look at the test and it seems legit (it fit with what I meant), the only difference is that we use avro schema but I think that there is no difference in the "code-flow". 
Unlucky I didn't have enough time to make this test runnable on my machine in order to be able to experiment with it and provide you the right scenario that will fail, also because hashmap behavior is unpredictable so I'd have to try and try till I found the "right scenario" 

Another misfortune is that I will be out of the office for a couple of weeks so the only things that i can provide you are a couple of screenshots about hashmap misbehavior

Here we are trying to insert Edid that have a reference (already in map) SupportedResolutions

![before](https://user-images.githubusercontent.com/89571393/183281841-6c740d13-bfe8-405a-a7a4-682aff5803ba.png)


Now we will now expect that Edid will be inserted at the end of the list but:
![after](https://user-images.githubusercontent.com/89571393/183281856-c832f8aa-0c42-4b30-93cb-102d9c1a7068.png)

Edid and SupportedResolutions have switched position and the list that will be generated will cause an exception (because the parser will try to parse Edid schema before SupportedResolutions)

This is the most I can provide you now, if you need more I'll try to find the right scenario when I'll came back to office.

**Comment by EricWittmann** [comment]
Thanks for the bug report and the analysis and also the attempt at a reproducer!  It's much appreciated.  When @carlesarnal returns from PTO he should be able to take a look at this.

**Comment by fabiobrz** [comment]
> Thanks for the bug report and the analysis and also the attempt at a reproducer! It's much appreciated. When @carlesarnal returns from PTO he should be able to take a look at this.

Hi @EricWittmann - that sounds good, I hadn't time to look into this since I was OOO for a couple of weeks and just got back.

BTW - just my 2 cents, but last time I checked the sources it seemed to me that we cannot just replace the `HashMap` with a `LinkedHashMap`, since the instance is then passed to differnet schema parsers (Avro, JSON, etc.) which eventually [manipulate it again](https://github.com/Apicurio/apicurio-registry/blob/main/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java#L59).

**Comment by carlesarnal** [comment]
Hi all, sorry for being late to the party, as Eric pointed out, I was on PTO. There is indeed a problem when handling nested and complex references in Avro but, according to my testing, it is not related to the data structure being used in this particular case but more about how Avro references are handled in the Avro schema parser (the nested references and some complex scenarios were not being properly handled). The order is of course important, but the important part resides in the schema parser and the order to parse the schemas there. I've created PR #2716 addressing some of those issues and also improving our testing to cover those scenarios.

Thanks!

**Comment by fabiobrz** [comment]
> Hi all, sorry for being late to the party...

:)

> There is indeed a problem when handling nested and complex references in Avro but, according to my testing, it is not related to the data structure being used in this particular case but more about how Avro references are handled in the Avro schema parser (the nested references and some complex scenarios were not being properly handled). The order is of course important, but the important part resides in the schema parser and the order to parse the schemas there. I've created PR #2716 addressing some of those issues and also improving our testing to cover those scenarios.

Exactly what I meant, thanks @carlesarnal - BTW I tried to wrap a reproducer up with Avro (similar to what you've done) but the [test](https://github.com/fabiobrz/apicurio-registry/commit/7e524f56568f90c4319be7eacc430e9d9acc1dcd) still passes in my case.

Out of curiosity, were you able to reproduce it?

**Comment by carlesarnal** [comment]
> > Hi all, sorry for being late to the party...
> 
> :)
> 
> > There is indeed a problem when handling nested and complex references in Avro but, according to my testing, it is not related to the data structure being used in this particular case but more about how Avro references are handled in the Avro schema parser (the nested references and some complex scenarios were not being properly handled). The order is of course important, but the important part resides in the schema parser and the order to parse the schemas there. I've created PR #2716 addressing some of those issues and also improving our testing to cover those scenarios.
> 
> Exactly what I meant, thanks @carlesarnal - BTW I tried to wrap a reproducer up with Avro (similar to what you've done) but the [test](https://github.com/fabiobrz/apicurio-registry/commit/7e524f56568f90c4319be7eacc430e9d9acc1dcd) still passes in my case.
> 
> Out of curiosity, were you able to reproduce it?

Yes, if I remove the code changes and just leave the test changes, the modified test fails for me.
