### ISSUE TITLE
Maven-plugin references management

### ISSUE THREAD

**Issue by merlor** [Apicurio/apicurio-registry#2678]
I found a couple of limitation about how apicurio-registry-maven-plugin manage the references:
Currently there is no way to update the reference of an artifact without changing some field in artifact itself and, more generally, you can't specify the version of a reference (it will be always updated to the last version).

Trying to find a possible solution to the aforementioned problems i tried to debug the maven-plugin, to better understand its behavior, and I think that the biggest problem is that the plugin tries to register every reference every time; yes it  seems simpler for the simplest scenario but when the complexity grows up it become really tricky to manage:

- if there are more artifact with the same reference, the same reference could be registered many times (if you set idExist to update)

- if you define a "complex" artifact (an artifact with reference) after another artifact that use it as a reference, the second artifact will register the "complex" artifact without any reference (an it will become impossible to update without applying concrete changes to its fields)

- if you try to update an artifact with a reference with a previous version (not the latest) setting the <version> field, an error occurs because it seems that the plugin tries to register an artifact with an already present version, breaking the unique key constraint

I think that the best way to handle all these problems could be to remove the registration from the references and handle them in a different way:
- the maven-plugin should register only the <artifact> elements as always (as a "primitive" element)
- a <reference> element only needs the fields that can identify it's globalId (groupId,artifactId,version, if version is blank you can use the latest version) and the maven-plugin should only add this reference to the artifact,obviously after checking that it exists (it adds the just the "links" between the artifact and the already registered artifact)

In this way it's true that you are obligated to define every artifact before, but you are sure you only do it once (avoiding the Empty reference" registration), separate the 2 logic (that could lead to ambiguity or unpredictable behavior) and handle the references with greater granularity (I can update only the artifact's references without adding fields and i can set manually the version that i need) even in the most complex scenarios.

I know this could be really messy and disruptive but I think that it could really improve the maven-plugin usability

**Comment by EricWittmann** [comment]
This is great feedback, thank you.  Our perspective on references has been that they are immutable in the same way that content is immutable - and that the references are stored with/live with the content.  More simply put, the references **are** part of the content.  This is important from the perspective of a consumer of a schema.  The consumer needs to be assured that the content of a specific version of an artifact will not change from one GET to the next.  Aggressive caching is therefore encouraged.

If I'm reading your suggestion correctly, you propose to separate management of the content from the references, which I think violates the principle above.

That said, we absolutely need improvements to the maven plugin with respect to references.  Ultimately my goal is to allow users to just point the maven plugin at a directory full of schema files and have the maven plugin figure out all of the registration details, including any references it might find in each.

_Note: our support for references is still very early_.

Thoughts from @Apicurio/developers ?

**Comment by merlor** [comment]
@EricWittmann first of all thank you for your response, I think that Apicurio Registry has a great potential so I would be glad to give some feedback about the project.

I totally agree with these assumptions:
> Our perspective on references has been that they are immutable in the same way that content is immutable

> The consumer needs to be assured that the content of a specific version of an artifact will not change from one GET to the next


> you propose to separate management of the content from the references

Exactly

> which I think violates the principle above

Are you sure? Because my idea was that if I change the reference of a complex artifact (because It points to a newer version) the plugin should generate a new version of the artifact that contains that reference, in this way the specific artifact version will be immutable and every GET (with the same version) will return the same item

> Ultimately my goal is to allow users to just point the maven plugin at a directory full of schema files and have the maven plugin figure out all of the registration details

You mean without properly filling the pom file (a very tedious and error-prone operation)? This would be a great feature, especially if an update of one artifact will update all artifacts that use it as a reference (this would certainly absolve my initial concern).

**Comment by EricWittmann** [comment]
> > you propose to separate management of the content from the references
> 
> Exactly
> 
> > which I think violates the principle above
> 
> Are you sure? Because my idea was that if I change the reference of a complex artifact (because It points to a newer version) the plugin should generate a new version of the artifact that contains that reference, in this way the specific artifact version will be immutable and every GET (with the same version) will return the same item

When you describe it this way, then I agree with it.  :)  As long as reference mappings for an artifact version in Registry cannot be changed after that version has been registered, we're on the same page.  :)

> > Ultimately my goal is to allow users to just point the maven plugin at a directory full of schema files and have the maven plugin figure out all of the registration details
> 
> You mean without properly filling the pom file (a very tedious and error-prone operation)? This would be a great feature, especially if an update of one artifact will update all artifacts that use it as a reference (this would certainly absolve my initial concern).

Yes exactly!  As you say, the current manual configuration is tedious and error prone.  The plugin should just figure it all out for you.  It should be fairly straightforward, if a bit tricky.  The most worrisome edge case is going to be circular dependencies.  But we would probably just want to fail if we detect any, at least to start off with.

**Comment by jjones-employers** [comment]
> > Ultimately my goal is to allow users to just point the maven plugin at a directory full of schema files and have the maven plugin figure out all of the registration details
> 
> You mean without properly filling the pom file (a very tedious and error-prone operation)? This would be a great feature, especially if an update of one artifact will update all artifacts that use it as a reference (this would certainly absolve my initial concern).

@EricWittmann Is there an ETA on when this feature might be available for us to test?

**Comment by EricWittmann** [comment]
I have a PR that could use some testing if anyone is interested:

https://github.com/Apicurio/apicurio-registry/pull/3439

It adds a new "autoRefs" feature to the maven plugin that is a proposal to evolve the existing analyzeDirectory feature.

Usage example is here:  

https://github.com/Apicurio/apicurio-registry-examples/pull/44

**Comment by EricWittmann** [comment]
That work has been merged and can be tested if you do a local build of registry `main`.

**Comment by carlesarnal** [comment]
Closing as this has been implemented (if someone is not happy with the implementation a discussion can be opened instead).
