### ISSUE TITLE
Question: Loss of data after one week (retention.ms)

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry#2684]
**Expected behavior**
If I follow the documentation for a kafkasql setup at https://www.apicur.io/registry/docs/apicurio-registry-operator/1.0.0/assembly-registry-storage.html#registry-persistence-kafkasql-plain I would expected that data is stored longer than 1 week.

**Current behavior**
If the data doesn't change for >= 1 week and the registry is restarted after one week, we don't have anymore data in the registry.

**Question**
As one can see in the kafkasql setup documentation the `retention.ms` is set to 1 week. This means after 1 week data will be cleaned up completely as the default value for `cleanup.policy` in a Kafka broker is `delete` (https://kafka.apache.org/documentation/#topicconfigs_cleanup.policy).  
What would be the right way to store data longer than 1 week? Set the retention.ms to -1 (storing for ever) or use `cleanup.policy=compact` or do I miss something?

**Comment by dweber019** [comment]
Addtionally I found https://github.com/Apicurio/apicurio-registry/pull/2030 where the topic is created with `cleanup.policy=compact`.

**Comment by dweber019** [comment]
And found in the auto create source code handling in the registry, which says we should use `cleanup.policy=compact` by default.
https://github.com/Apicurio/apicurio-registry/blob/2.2.5.Final/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java#L225

I think the documentation should be changed. Here the PR for this https://github.com/Apicurio/apicurio-registry-operator/pull/183

**Comment by EricWittmann** [comment]
You have gone on a journey here and arrived at the correct conclusion!  :)

The kafka storage support is designed to use `cleanup.policy=compact` so we recommend doing that.  We did have a bug in our implementation previously that caused log compaction to not work properly but that has been fixed.

I agree that the docs should be updated - so thank you for the PR!

We will also need to update the Apicurio Registry docs.  Pinging @smccarthy-ie on that.

**Comment by dweber019** [comment]
Yes was quite a ride 😅 but anyway had a feeling.

If you point me to location your talking about, I can do it.

**Comment by EricWittmann** [comment]
Registry docs are located here:  https://github.com/Apicurio/apicurio-registry/tree/main/docs

But @smccarthy-ie could perhaps point us at exactly where we might want to add this info...

**Comment by smccarthy-ie** [comment]
Thanks @dweber019 Great to get doc contributions! :) 

@EricWittmann  The Apicurio Registry Operator docs on installing Kafka storage are much more detailed than the Apicurio Registry docs, which are not very comprehensive and really only to help get started: 
https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-installing-registry-storage-openshift.html#setting-up-kafka-streams-storage_registry

If you also want to mention this in the Registry docs, the appropriate source file is: https://github.com/Apicurio/apicurio-registry/blob/main/docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
