### ISSUE TITLE
[tech-debt] UI linting rules

### ISSUE THREAD

**Issue by andreaTP** [Apicurio/apicurio-registry#2696]
We should agree on a set of linting rules and apply those rules to `apicurio-registry` and all our UI projects.

Initial exploration work:
https://github.com/Apicurio/apicurio-configs/tree/main/eslint-config

Also checking the results of linting in CI makes sense once we agree on the rules.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/2706
