### ISSUE TITLE
References are not passed into rulesService when applying rules for artifact updates.

### ISSUE THREAD

**Issue by kthakker-hbo** [Apicurio/apicurio-registry#2703]
Hi,

We have a scenario where we are trying to upload json schemas that contain references to json schemas of a different artifact, with the validity check enabled and set to FULL. I noticed the upload was succeeding for the initial create artifact request. However, on subsequent requests to the create artifact endpoint for a given artifact with a new version, with ifExists=UPDATE, we would get back 409 FileNotFoundException errors, with the file not found being the referenced schema, preventing us from using the validity checks.

After digging into the code with the debugger, I tracked down what I believe to be the issue to the updateArtifactInternal function in io.apicurio.registry.rest.v2.GroupsResourceImpl.java. Specifically this line: https://github.com/Apicurio/apicurio-registry/blob/575ea78374f718e9a4fc1a39e45b2999bd92a765/app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java#L883

In this function a hardcoded empty map is passed in as the resolvedReferences parameter when the ruleseService.applyRules function is called, rather than the actual resolved references as the createArtifactVersionWithRefs function does: https://github.com/Apicurio/apicurio-registry/blob/575ea78374f718e9a4fc1a39e45b2999bd92a765/app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java#L676

I think this may be a bug. Simply updating the updateArtifactInternal function from:
```
rulesService.applyRules(gidOrNull(groupId), artifactId, artifactType, content, RuleApplicationType.UPDATE, Collections.emptyMap());
```

 to:
```
final Map<String, ContentHandle> resolvedReferences = storage.resolveReferences(referencesAsDtos);

rulesService.applyRules(gidOrNull(groupId), artifactId, artifactType, content, RuleApplicationType.UPDATE, resolvedReferences);
```

solved our issues. 

Was it intentional to not pass in references to the rulesService for artifact updates? If not, we would greatly appreciate a PR to update this function so we can make use of the validity checks.

**Comment by carlesarnal** [comment]
Thanks for finding this problem, this is indeed a bug, pr created.
