### ISSUE TITLE
SAML support?

### ISSUE THREAD

**Issue by robertboxall** [Apicurio/apicurio-registry#2729]
Has anyone managed to get their own setup working against corporate security with SAML? We're trying to have SAML for all applications and have an in house version of apicurio for our development teams to use. 

I attempted to wire the code directly to SAML and bypass keycloak but was unable to figure out how JBOSS security is wired up in this area as its inside the server and no matter how many google searches I took no luck finding anyone else doing this either.

Seeing the code is setup for Keycloak now wondering if keycloak can use saml as an identify provider but maybe someone else has done this before.

**Comment by carlesarnal** [comment]
Closing as this has been implemented and the Registry standalone UI now supports using any other OIDC server.
