### ISSUE TITLE
GroupMetadata not created when a new artifact is created

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#2741]
Whenever an artifact is created, the group metadata must be created if it does not exist yet.

**Comment by jsenko** [comment]
Discussion https://chat.google.com/room/AAAAyw20bSc/twzuVc6O6JA

**Comment by EricWittmann** [comment]
We should consider also adding new REST API endpoints to manage the groups.  In particular we will need a way to change group ownership like we now have for artifacts.

**Comment by rkubis** [comment]
> We should consider also adding new REST API endpoints to manage the groups. In particular we will need a way to change group ownership like we now have for artifacts.

I like this 👍
