### ISSUE TITLE
Authenticated Read Access feature only makes sense if Role Based Authorization is enabled

### ISSUE THREAD

**Issue by rkubis** [Apicurio/apicurio-registry#2743]
Authentication/authorization configuration (https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/auth/AuthConfig.java#L60) mentions that **Authenticated Read Access** feature, `registry.auth.authenticated-read-access.enabled` (`REGISTRY_AUTH_AUTHENTICATED_READS_ENABLED`), requires **Authentication** option enabled only, `registry.auth.enabled=true` (`AUTH_ENABLED` environment variable).

But **Authenticated Read Access** feature does not make sense without **Role Based Authorization** option enabled, `registry.auth.role-based-authorization` (`ROLE_BASED_AUTHZ_ENABLED` environment variable).

It looks that **Authenticated Read Access** feature works fine when **Authentication** and **Role Based Authorization** are enabled, the issue is more about documentation than implementation.

**Comment by smccarthy-ie** [comment]
@rkubis @EricWittmann Does this issue also affect the UI implementation? There is no setting for **Role Based Authorization**  currently in the UI, so a user cannot set it there. For example, a downstream RHOSR user cannot set the env variable, or is this already set by default for RHOSR?

**Comment by EricWittmann** [comment]
There's no setting for Role Based Auth because it's not a dynamic property.  The authenticated read access feature **is** dynamic.

I think the only thing to do here is a minor change to add the appropriate rbac property as a dependency of the read-access dynamic property.  That way the latter will only appear and be an option if the former is set to true.

**Comment by EricWittmann** [comment]
Also maybe update the documentation to indicate the same:  this option is only available when RBAC is enabled.
