### ISSUE TITLE
Update change owner UI to only display accounts with access to the instance 

### ISSUE THREAD

**Issue by smccarthy-ie** [Apicurio/apicurio-registry#2769]
Suggest updating the change owner modal to only display user accounts (and service accounts) that have been granted access to the registry instance in the **New owner** field? 

The help text in this field should say "Select or enter an account" instead of only "Select an account"?

For more details, see:  
 - https://github.com/Apicurio/apicurio-registry/pull/2731
 - https://github.com/Apicurio/apicurio-registry/pull/2738

**Comment by EricWittmann** [comment]
Deferring to after 2.3 because it's not relevant for on-prem deployments.

**Comment by EricWittmann** [comment]
It would better if we knew what the format restrictions might be.  In some cases maybe we might... or maybe we could make it configurable.  When we have a list of principals to populate the dropdown with, I think we could limit the allowed value to items in that list.

**Comment by EricWittmann** [comment]
Closing as no longer relevant.
