### ISSUE TITLE
UI fails when RBAC is on  (500 / e.method is undefined)

### ISSUE THREAD

**Issue by udinnet** [Apicurio/apicurio-registry#2805]
Hi Everyone, 

I'm facing an issue in the UI when Apcurio is configured to use Keycloak. The API works nicely with RBAC enabled. Following is the current configuration. 
```
Version : 2.2.5.Final KafkaSQL
QUARKUS_PROFILE = prod
AUTH_ENABLED = true
CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED = true
REGISTRY_UI_CONFIG_APIURL = https://<host>:<port>/apis/registry
REGISTRY_UI_CONFIG_UIURL = https://<host>:<port>/ui
REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED=true
ROLE_BASED_AUTHZ_ENABLED=true
KEYCLOAK_URL= <url for KC>
KEYCLOAK_REALM = <realm for KC>
KEYCLOAK_API_CLIENT_ID = <KC api client ID>
KEYCLOAK_UI_CLIENT_ID = <KC UI client ID>
```

Following are some screenshots of the issue. 

**UI login flow**

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/2894476/190615168-97a4c38b-ad55-42ef-bd4c-72164aaa9c3d.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/2894476/190615274-b8bf1eb8-9c5d-42bd-a0b6-efe4b56be24a.png">
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/2894476/190615364-77785b04-4613-4b64-a02e-8aab8deff371.png">
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/2894476/190615555-4e991728-ba1a-4700-bf25-5f8c687d9aaf.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/2894476/190615808-df212b62-3210-49da-917a-78e8650ead98.png">
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/2894476/190615863-3b31a97f-4dc7-4b79-995b-3af3551213af.png">
<img width="171" alt="image" src="https://user-images.githubusercontent.com/2894476/190616174-8eaabc63-7c2a-46d5-8852-0a5f8f3238c5.png">

**Inside KC**

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/2894476/190616439-dd01f8f9-34a0-4404-a4a0-b92389b8ffdf.png">
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/2894476/190616638-d5d86ce8-b0f0-4e03-879e-b50a95a35280.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/2894476/190616712-a2511d26-f7e0-4ab7-8386-b0dd344e488d.png">
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/2894476/190616747-39f4d5e2-6985-461f-b637-2e14fa6e176f.png">

**Login User to Apicurio UI**

This user works without any issue in APIs

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2894476/190616904-b3e6b890-4973-49dc-af55-776c5bb59dac.png">

As far as I see, it is an issue in the UI when it reads the userinfo response from KC. But I didn't dig deeper into the UI code.

Thanks in advance.

**Comment by udinnet** [comment]
API Call from the same user token
![image](https://user-images.githubusercontent.com/2894476/190619692-cc831e00-07f6-4704-88d2-65574ef1e7d1.png)

**Comment by carlesarnal** [comment]
Note that you're missing REGISTRY_UI_AUTH_TYPE in your configuration. I just tested the setup and is working with no issues.

**Comment by udinnet** [comment]
Hi @carlesarnal 
Thanks for the reply. 
From the code I can see this config property introduced in 2.2.6 version. I'm using 2.2.5.Final. 

https://github.com/Apicurio/apicurio-registry/blob/5ff3d039853cfe6ee02659d5dc4096f104261728/app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java#L71-L74

**Comment by carlesarnal** [comment]
Yes, that property is mandatory only in 2.2.6.Final. I just tested 2.2.5.Final and RBAC in the UI works with no issues. How are you starting the UI?

**Comment by udinnet** [comment]
I use the 2.2.5.Final docker container and point the browser to configured kubernetes service. In my case it is 
`http://localhost:20500/ui` or `http://platform.local:20500/ui` (host alias). If `REGISTRY_UI_AUTH_TYPE` needs to be set, what are the possible values for it?

**Comment by carlesarnal** [comment]
I'm sorry, but I just started the application using the following command and it's working with no issues. `docker run -it -p 8080:8080 -e AUTH_ENABLED=true -e ROLE_BASED_AUTHZ_ENABLED=true -e KEYCLOAK_URL=$KEYCLOAK_URL -e KEYCLOAK_REALM=$KEYCLOAK_REALM quay.io/apicurio/apicurio-registry-mem:2.2.5.Final`. `REGISTRY_UI_AUTH_TYPE` is only required starting in `2.2.5.Final.` From your configuration, I have noticed that you're creating client-level roles instead of realm roles, the UI expect the roles to be realm roles, so maybe try changing that.

**Comment by udinnet** [comment]
I could not get it working in 2.2.5.Final for some reason. Then I moved to 2.3.0.Final and enabled `oidc` flow for UI. In fact I was able to use client specific roles for the UI. I'll share the setup in KC and configuration later today. Probably then we can close this ticket. Thanks for the help so far.

**Comment by carlesarnal** [comment]
hi @udinnet do you think we can consider this as solved?

Thanks

**Comment by udinnet** [comment]
Hi @carlesarnal yes. As mentioned in my last comment, following is the configuration that I'm using. 
```
Version : 2.3.0.Final KafkaSQL
QUARKUS_PROFILE = prod
AUTH_ENABLED = true
CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED = true
REGISTRY_UI_CONFIG_APIURL = https://<host>:<port>/apis/registry
REGISTRY_UI_CONFIG_UIURL = https://<host>:<port>/ui
REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED=true
ROLE_BASED_AUTHZ_ENABLED=true
KEYCLOAK_URL= <url for KC>
KEYCLOAK_REALM = <realm for KC>
KEYCLOAK_API_CLIENT_ID = <KC api client ID>
KEYCLOAK_UI_CLIENT_ID = <KC UI client ID>
REGISTRY_UI_AUTH_TYPE=oidc
REGISTRY_AUTH_URL_CONFIGURED=https://<KC host>/auth/realms/<realm name>
KEYCLOAK_REALM=<realm name>
REGISTRY_OIDC_UI_REDIRECT_URL=REGISTRY_UI_CONFIG_UIURL
REGISTRY_OIDC_UI_CLIENT_ID=KEYCLOAK_UI_CLIENT_ID
```

KC Setup 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2894476/193247934-9ae0a69f-7e58-4c7a-be5b-afc09825deb5.png">
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/2894476/193248006-80af79d0-c5b0-4264-8ed9-4c55c4b66001.png">
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/2894476/193248104-31f03920-a8c6-41fb-a7eb-93027562ef1c.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2894476/193248158-588fba95-a207-4f84-9c6e-5d9e858c0504.png">
