### ISSUE TITLE
Bug with Registry artifact creation API - ignoring name and description from header param

### ISSUE THREAD

**Issue by ozarkblue** [Apicurio/apicurio-registry#2826]
Using this artifact creation endpoint:
apis/registry/v2/groups/:groupid/artifacts?ifExists=RETURN_OR_UPDATE

For first time its taking name and description as per header perm X-Registry-Name and X-Registry-description.
But for any subsequent changes in content it's creating new version correctly.But during this version-creation its taking input from body attributes and updating in artifacts new version name and description 
and  ignoring parm X-Registry-Name and X-Registry-description.

Should this not take name and description always from perm X-Registry-Name and X-Registry-description when that is provided in header for this endpoint?

Header:
![image](https://user-images.githubusercontent.com/109760446/191596828-9b53b125-e116-4507-abf2-b5404429b349.png)

Top part of body JSON content:
![image](https://user-images.githubusercontent.com/109760446/191596903-aaad56ec-3967-4b15-93e0-7f9f15786ccb.png)

After initial create :
![image](https://user-images.githubusercontent.com/109760446/191596960-b8b243e3-c3f5-431b-85b5-64d9ea50fc88.png)

After subsequent run (changed a field in body to create a new version) but it updated name and description taking input from body instead.

![image](https://user-images.githubusercontent.com/109760446/191597037-08c43b80-1cf7-43d0-9d9d-aeeef02f63e8.png)

@EricWittmann  pls check

**Comment by EricWittmann** [comment]
Thanks @ozarkblue  - this sounds like a straightforward bug and should be easy enough to fix.

**Comment by ozarkblue** [comment]
@EricWittmann is this issue fixed? Would you pls check once and update pls
