### ISSUE TITLE
Upgrade to apicuro from 2.2.5.Final to 2.3.0.Final breaks keycloak Auth (needs documentation)

### ISSUE THREAD

**Issue by jfreeman-hbo** [Apicurio/apicurio-registry#2828]
When upgrading to the recent 2.3.0, our keycloak OIDC authentication broke, resulting in a 401 on the UI.

We fixed this by adding this environment variable to our helm chart:
    - name: REGISTRY_UI_AUTH_TYPE
      value: "keycloakjs"

Please update the documentation at: https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-configuring-the-registry.html#registry-security_registry

denoting that this ENV var is now required. 

it would also be helpful if there was better documention on securing Apicurio behind any OIDC provider, which I think now is an option?

**Comment by EricWittmann** [comment]
@carlesarnal If this is true, can we have `keycloakjs` as the default value for that env var?

**Comment by carlesarnal** [comment]
This is true for 2.3.0.Final but I have created [this](https://github.com/Apicurio/apicurio-registry/commit/e59e0e52f32a5f0bf2b15974c454a5e9568976db) to make keycloakjs the default value for this when auth is enabled and none is set as the value (since does not makes any sense to have none and auth enabled).

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/2832 - I think we can leave this out of the documentation as long as we release 2.3.1.Final soon.

**Comment by EricWittmann** [comment]
Thank you @jfreeman-hbo for reporting this!
