### ISSUE TITLE
Json backward compatability bug with type-keyword from string to array in properties

### ISSUE THREAD

**Issue by YangSan0622** [Apicurio/apicurio-registry#2835]
Hello,

We have noticed that there are some unexpected behavior for `JsonSchemaCompatibilityChecker`. Here is an example to illustrate the issue we discovered.

Consider these 3 schemas:

 **Version 1**
```
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "test": {
      "type": "string"
    }
  }
}
```

**Version 2**
```
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "test": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    }
  }
}
```

**Version 3**
```
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "test": {
      "type": [
        "string",
        "number"
      ]
    }
  }
}
```
The above version 2 and version 3 should be compatible to the version 1 , but `testCompatibility` method in `JsonSchemaCompatibilityChecker` will return a `CompatibilityExecutionResult` says they are incompatible.

The version of Apicurio-registry I am working with is 2.3.1-SNAPSHOT

**Comment by jsenko** [comment]
Thank you for the PR!

**Comment by YangSan0622** [comment]
Hello,
I am just wondering when will there be a release that includes this fix?
