### ISSUE TITLE
Confluent Compatibility Issue with subject version

### ISSUE THREAD

**Issue by mouadk** [Apicurio/apicurio-registry#2851]
Hello, Looks like Apicurio registry is not fully compatible with Confluent. Confluent API schema registry uses[ the version -1 ](https://github.com/confluentinc/schema-registry/blob/9ffc7f6cc40b19c80fd76878e6e732611816bcbe/core/src/main/java/io/confluent/kafka/schemaregistry/rest/VersionId.java) as a special id for the latest version. 
When using the Confluent Schema Registry plugin and a version is not provided, it fallback on -1 and sends a request similar the one below to Apicurio: 
`https://apicurio-service/apis/ccompat/v6/subjects/my-subject-value/versions/-1`

The following error is observed: 

```
{
    "message": "Illegal version format: -1",
    "error_code": 0
}
```
I was expecting that Apicurio handle the -1 similarly. 

I have also noticed that there is no Maven plugin allowing to register/test compatibility ect.. of schemas. 

Best, 

Mouad

**Comment by jsenko** [comment]
The [Confluent API documentation says](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)):
```
version (versionId) – Version of the schema to be deleted. 
Valid values for versionId are between [1,2^31-1] or the string “latest”, 
which deletes the last registered schema under the specified subject.
```
This looks like an undocumented Confluent behavior, can you give me a link to some official information about this? Which version of the Confluent plugin shows this behavior? It should use `latest` instead of `-1`, so maybe it's a bug on their side.

**Comment by mouadk** [comment]
I have tried to open this ticket https://github.com/confluentinc/schema-registry/issues/2394, it explains the behaviour, however I wasn't sure if it was expected on their side and I closed it and opened this one. 

What do you think ?

**Comment by jsenko** [comment]
Wait, but they didn't reply, so how can you be sure it's not an issue on their side?

**Comment by mouadk** [comment]
Ok I have reopened it

**Comment by jsenko** [comment]
Thank you!

**Comment by mouadk** [comment]
Hello @jsenko, the ticket was closed as I would have expected, looks like its a normal behavior on their side ( at least internally)

**Comment by jsenko** [comment]
Sorry, getting back to this, I'll create a fix to match the behavior of Confluent.

**Comment by jsenko** [comment]
@mouadk Please check if the PR fixes your issue

**Comment by mouadk** [comment]
Hello @jsenko, I just tested your PR and it looks all good on my side. 
Thanks
