### ISSUE TITLE
Derefence parameter not working

### ISSUE THREAD

**Issue by merlor** [Apicurio/apicurio-registry#2863]
## Description

**Registry
Version**: 2.3.1.Final
**Persistence type**: 

### Environment

Apicurio Registry v2.3.1.final running on docker

### Steps to Reproduce

Having an artifact with gloablId=1 and some references

1. launch this request with Postman: http://localhost:8080/apis/registry/v2/ids/globalIds/1
2. launch this request with Postman: http://localhost:8080/apis/registry/v2/ids/globalIds/1?dereference=true
3. Both schemas returned have inner fields like references

-->

### Expected vs Actual Behaviour

I expect that adding "deference=true" Apicurio Registry should return the schema with dereferenced ("explosed") fields as stated in the documentation.

Additional Tip:
In class v2/IdsResourceImpl at the line 109-111 in the method getContentByGlobalId, its seems that "dereference" flag is totally ignored

Am I doing something wrong or this feature isn't yet available?

**Comment by carlesarnal** [comment]
Hello @merlor,

Thanks for opening this. You get to the point in your last comment, this feature is just not available yet in the API.

I have created [this](https://github.com/Apicurio/apicurio-registry/issues/2865), where the work to implement the functionality will be tracked. I'm closing this one in favour of the other one.

Thanks!
