### ISSUE TITLE
JSON backward compatibility check for adding non-required fields

### ISSUE THREAD

**Issue by arturkandur** [Apicurio/apicurio-registry#2882]
JSON backward compatibility check for adding non-required fields

Hello,

I am testing the JSON compatibility for adding non-required fields. There are multiple cases when adding fields in JSON Schema that seem incorrect. This cases should be work without **"additionalItems": false** but when I remove it the check compatibility update is failed.

For example,

1. Should be backward compatible without "additionalItems": false

```
"original": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": [
    {
      "type": "string"
    },
    {
      "type": "number"
    }
  ]
},
"updated": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": [
    {
      "type": "string"
    },
    {
      "type": "number"
    },
    {
      "type": "boolean"
    }
  ]
}
```

2. Should be backward compatible without "additionalItems": false

```
"original": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "postal_code": {
            "type": "number"
          },
          "street": {
            "type": "string"
          }
        }
      },
      "updated": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "postal_code": {
            "type": "number"
          },
          "street": {
            "type": "string"
          },
          "country": {
            "type": "string"
          }
        },
        "additionalProperties": {
          "type": "string"
        }
      }

```

3. Also the case should be failed because in updated schema should be only "type": "string" properties

```
"original": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "postal_code": {
            "type": "number"
          },
          "street": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "updated": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "postal_code": {
            "type": "number"
          },
          "street": {
            "type": "string"
          },
          "country": {
            "type": "string"
          }
        },
        "additionalProperties": {
          "type": "string"
        }
      }
```   

What do you think about it?

**Comment by jsenko** [comment]
Hello @arturkandur sorry for the delay.

We've defined the backwards compatibility relation in the following way: Schema `S2` is backwards compatible with schema `S1`, iff all messages that are accepted by `S1` are also accepted by `S2`.
```
S1 <c S2 <=> \/m: S1 accepts m => S2 accepts m
```
i.e. `S2` cannot restrict the set of messages that are accepted, but can accept additional messages. 
Let's look at your cases and look for counter-examples:

### 1. 
Original accepts arrays starting with number and then a string, but then does not prevent any other types of items from following. The updated schema restricts a type of the third item, which gives us a counter-example:
```
[1, "two", "three"]
```
 is accepted by `S1`, but not by `S2`. In case of `additionalItems: false`, the situation is different, because all messages are forced to have exactly 2 items by `S1`, which `S2` accepts.

### 2. 
Suffers from a similar issue. A counter-example would be:
```
{"postal_code": 123, "street": "Main", "country": true}
```
Moreover, adding `additionalProperties` restricts the set of accepted messages as well in a similar way. Therefore adding `additionalProperties` is not backwards compatible, but removing is.

### 3.
As mentioned above, additional properties in `S1` restricts the messages into the following form:
```
{"postal_code": 123, "street": "Main"}
```
therefore allowing any other properties is alright.

Let me know if this makes sense, or if you come across other possible issues. Compatibility is tricky because the algorithm must be general and we decided to err on the side of caution and rather allowing false negatives than false positives. You can also always turn the compatibility rule off temporarily if you are sure that in your specific use case the compatibility is not a problem.

**Comment by jsenko** [comment]
In your updated case:
For `S1`:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "postal_code": {
            "type": "number"
        },
        "street": {
            "type": "string"
        }
    }
}
```
these messages are valid:
```
{"postal_code": 123}
{"postal_code": 123, "street": "Main"}
{"postal_code": 123, "street": "Main", "foo": "bar"}
{"postal_code": 123, "street": "Main", "foo": "bar", "country": "Czechia"}
{"postal_code": 123, "street": "Main", "foo": "bar", "country": true}
```
For `S2`:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "postal_code": {
            "type": "number"
        },
        "street": {
            "type": "string"
        },
        "country": {
            "type": "string"
        }
    }
}
```
these messages are valid:
```
{"postal_code": 123}
{"postal_code": 123, "street": "Main"}
{"postal_code": 123, "street": "Main", "foo": "bar"}
{"postal_code": 123, "street": "Main", "foo": "bar", "country": "Czechia"}
```
but this is not
```
{"postal_code": 123, "street": "Main", "foo": "bar", "country": true}
```
The issue is that you are restricting the type of `country`, where previously it could've been anything.

**Comment by jsenko** [comment]
> So adding any optional property S2 should be allowed because it does not restrict S1. It is just optional property and not marked as required.
This is not necessarily true, as mentioned above, even if `country` is not required, it can be present with a wrong type.
On the other hand, removing a property completely relaxes the requirement on its type to anything.

**Comment by arturkandur** [comment]
Ok, got your thoughts, that make sense. Thanks.

**Comment by jsenko** [comment]
Thanks for the discussion. This happens exactly because `additionalProperties: true, but would be ok if `additionalProperties: false`.

**Comment by bobmorley** [comment]
@jsenko sorry to bud in here, we have the exact same problem and it certainly wasn't clear that we would not be able to add optional fields by not explicitly setting `additionalProperties: false`. Does this have an impact when you consider forwards compatibility?

Consider your accepted document
`{"postal_code": 123, "street": "Main"}`

With a schema that defines both (as optional) with additionalProperties: false.

If I now evolve my schema to no longer define `street`, it appears this old document can no longer validate with the latest version of the schema as it would now see street as an additionalProperty.

What is the best practice here to guarantee both backward & forward compatibility as schemas wish to evolve?

**Comment by jsenko** [comment]
I would say the best practice it to ensure that the schema matches your messages as strictly as possible, while taking default values from the spec into account.

The compatibility checker works with a limited amount of information, so if you want to evolve a schema in a way that you know will not cause issues for your use-case, you can always disable it temporarily.

As mentioned before, we decided to be strict and rather allow false negatives than false positives. But there is a possibility we will add a less strict mode in the future if it is useful.

**Comment by arturkandur** [comment]
> But there is a possibility we will add a less strict mode in the future if it is useful.

It will be good feature I think.
In my case I want to update json schemas backward compatible and clients forget to add `additionalProperties: false` to schema from the start.
So if they want to update it, they need to create new one because it is more strict and not possible to add `additionalProperties: false` or new field. That's why I raise this question.
