### ISSUE TITLE
Artifact with reference not updated in apicurio-registry-maven-plugin

### ISSUE THREAD

**Issue by merlor** [Apicurio/apicurio-registry#2888]
## Description

**Registry
Version**: 2.3.1.Final
**Persistence type**:

### Environment
Apicurio-registri v2.3.1.Final running on Docker container, adding/updating artifact with apicurio-registry-maven-plugin v2.3.1.Final

### Steps to Reproduce

Given a complex artifact with schema A.avsc:
```
{
  "type": "record",
  "name": "A",
  "namespace": "myGroup",
  "doc": "A some Desc",
  "fields": [
    {
      "name": "a1",
      "type": "string",
      "doc": "some string",
      "default": ""
    },
    {
      "name": "b",
      "type": [
        "null",
        "myGroup.B"
      ],
      "doc": "item b",
      "default": null
    }
  ]
}
```

An artifact B, with schema B.avsc, that is a reference of A:
```
{
  "type": "record",
  "name": "B",
  "namespace": "myGroup",
  "doc": "B desc",
  "fields": [
    {
      "name": "b1",
      "type": "string",
      "doc": "sother string",
      "default": ""
    },
    {
      "name": "b2",
      "type": "string",
      "doc": "sother other string",
      "default": ""
    },
  ]
}
``` 

And a pom.xml file with this configuration:
```
            <plugin>
                <groupId>io.apicurio</groupId>
                <artifactId>apicurio-registry-maven-plugin</artifactId>
                <version>${apicurio-registry.version}</version>
                <executions>
                    <execution>
                        <id>register-artifact</id>
                        <phase>package</phase>
                        <goals>
                            <goal>register</goal>
                        </goals>
                        <configuration>
                            <registryUrl>${apicurio-registry.url}</registryUrl>
                            <artifacts>
                                <artifact>
                                    <groupId>myGroup</groupId>
                                    <artifactId>A</artifactId>
                                    <type>AVRO</type>
                                    <version>2</version>
                                    <file>
                                        ${project.basedir}/src/main/resources/schemas/A.avsc
                                    </file>
                                    <ifExists>RETURN_OR_UPDATE</ifExists>
                                    <canonicalize>true</canonicalize>
                                    <references>
                                        <reference>
                                            <name>B</name>
                                            <groupId>myGroup</groupId>
                                            <artifactId>B</artifactId>
                                            <type>AVRO</type>
                                            <file>
                                                ${project.basedir}/src/main/resources/schemas/B.avsc
                                            </file>
                                            <ifExists>RETURN_OR_UPDATE</ifExists>
                                            <canonicalize>true</canonicalize>
                                        </reference>
                                    </references>
                                </artifact>
                            </artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

1. launch `mvn clean package`
2. add a field file B.avsc
3. launch `mvn clean package`

### Expected vs Actual Behaviour

**Expetced**
after steps 1,2 and 3 I expect
 for artifact B: old version (version 1 with globalId 1) and new version (version 2 with globalId 3)
 for artifact A: old version (version 1, with globalId 2 and a B v1 reference) and new version (version 2 with globalId 4 and B v2 reference)

**Actual**
after steps 1,2 and 3 I have
 for artifact B: old version (version 1 with globalId 1) and new version (version 2 with globalId 3)
 for artifact A: old version (version 1, with globalId 2 and a B v1 reference);  **new version of artifact A is missing**

Is there a way to update the A artifact with the new version of artifact of B? At the moments, as far as I know, i can generate the new version of A only if i add a new field to A; am I doing something wrong?

**Comment by carlesarnal** [comment]
This has been solved by implementing directory resolvability in the maven plugin. Essentially, you can now point the plugin to a directory containing a set of schemas and the plugin will figure out all the mappings for you. I'm working on the documentation and examples for this.

**Comment by EricWittmann** [comment]
Update: I have an evolution of the directory scanning support in the Maven plugin.  I have a new proposal here:

https://github.com/Apicurio/apicurio-registry/issues/2865

It basically does the same thing but supports more types and is implemented slightly differently (but with a number of bits in common).  If anyone wants to build it locally and give it a try, I wouldnt' complain.  :)

**Comment by carlesarnal** [comment]
Closing as this has been implemented.
