### ISSUE TITLE
How to use the vertx http client

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#2910]
Because of [class loading issues](https://stackoverflow.com/questions/74155634/classnotfoundexception-java-net-http-httpresponse-in-wf-18-java-11) in my context (Wildfly 18, Java 11), I cannot use the JDK HttpClient.

I think the only solution I  have is to use the VertX Http client, but I failed to make it work.
Adding apicurio-common-rest-client-vert to my deployment does not work, JDK HttpClient is still used.
Defining a service loader in my deployment does not work either:

```
cat META-INF/services/io.apicurio.rest.client.spi.ApicurioHttpClientProvider
io.apicurio.rest.client.VertxHttpClientProvider

# leads to NoSuchMethodException: io.apicurio.rest.client.VertxHttpClientProvider.<init>()
```

Do you think there is solution for force usage of the VertX client in this context?

My dependencies:

```xml
<dependency>
  <groupId>io.apicurio</groupId>
  <artifactId>apicurio-registry-serdes-avro-serde</artifactId>
  <version>2.3.1.Final</version>
</dependency>
<dependency>
  <groupId>io.apicurio</groupId>
  <artifactId>apicurio-common-rest-client-vertx</artifactId>
  <version>0.1.13.Final</version>
</dependency>
```

_Originally posted by @zapho in https://github.com/Apicurio/apicurio-registry/issues/1482#issuecomment-1293100124_

**Comment by carlesarnal** [comment]
@zapho I have created this issue since your question was not really related to the issue you commented.

To make use of the Vert.x client you need to set the provider with the vert.x instance, [see](https://github.com/quarkusio/quarkus/blob/main/extensions/schema-registry/apicurio/common/runtime/src/main/java/io/quarkus/apicurio/registry/common/ApicurioRegistryClient.java#L12) the example in the Quarkus extension.

**Comment by zapho** [comment]
Thanks, @carlesarnal. I will try this.

**Comment by carlesarnal** [comment]
Hi @zapho, if it worked for you, please, close this issue.

Thanks!

**Comment by zapho** [comment]
I will try to give it a try this week and update this issue accordingly.

**Comment by zapho** [comment]
Ran into various Wildfly integration issues and stopped trying to use vertx client in this context.

**Comment by carlesarnal** [comment]
Done, thanks!
