### ISSUE TITLE
Configuring Apicurio Registry event sourcing with HTTP Error

### ISSUE THREAD

**Issue by 1indiangirl** [Apicurio/apicurio-registry#2913]
## Description
Trying to use APICURIO reg mem event sourcing with HTTP, followed all the steps mentioned in - https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/getting-started/assembly-configuring-the-registry.html#registry-cloud-events_registry

custom API is up and running properly and accessible as well

in logs can see appropriate event Type : io.apicurio.registry.artifact-created as well
but while firing event seems port taken default and not considering mentioned in configuration

suspected code : https://github.com/Apicurio/apicurio-registry/blob/c6afc84d269e93bf81756ddefbf9c9dd3c436aa7/app/src/main/java/io/apicurio/registry/events/http/HttpEventSink.java#L85

error msg is also confusing to identify whether its going in if (line 88) or else (line 91) block 

### Environment
localhost docker

### Steps to Reproduce
1. Start Apicurio mem registry
2. Have ready to use API with endpoint /events and provide configurations as mentioned : https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/getting-started/assembly-configuring-the-registry.html#registry-cloud-events_registry
3. perform CRUD on apicurio registry mem
NOTE:  All was done localhost docker 
custom API is accessible from docker 
-->

### Expected vs Actual Behaviour

event sourcing should happen and get all information

### Logs
```
INFO <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-0) Firing event io.apicurio.registry.artifact-created
spingboot-test-apicurio-1 | 2022-10-20 07:13:52 ERROR <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-0) Error sending event to http://myspringapp:9999/events: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:80
spingboot-test-apicurio-1 | Caused by: java.net.ConnectException: Connection refused
spingboot-test-apicurio-1 | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
spingboot-test-apicurio-1 | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
spingboot-test-apicurio-1 | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
spingboot-test-apicurio-1 | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
spingboot-test-apicurio-1 | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
spingboot-test-apicurio-1 | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
spingboot-test-apicurio-1 | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
spingboot-test-apicurio-1 | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
spingboot-test-apicurio-1 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
spingboot-test-apicurio-1 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
spingboot-test-apicurio-1 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
spingboot-test-apicurio-1 | at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by carlesarnal** [comment]
Hi @1indiangirl,

We need a bit more context here, like the Registry version you're using, how you're configuring the sink and, if possible, a reproducer of the issue. From the error, it seems to me that Registry cannot access your Spring application, but it's a bit hard to say without more information.

**Comment by EricWittmann** [comment]
+1 to Carles's comment.  The most important part is the sink configuration.  That would be extremely helpful.

**Comment by cs0978** [comment]
Hi @EricWittmann 

We have the same problem. We're using apicurio-registry-sql:2.2.5.Final

The log output of the apicurio-registry container:
```
2022-11-17 10:50:23 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-1) apicurio.audit action="createArtifact" result="success" src_ip="10.136.24.1" x_forwarded_for="10.136.24.1" artifact_id="y" principal_id="ex324"
2022-11-17 10:50:23 INFO <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-1) Firing event io.apicurio.registry.artifact-created
2022-11-17 10:50:23 ERROR <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-1) Error sending event to http://cloudevents-helper.test-ns.svc.cluster.local:8080/events: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:80
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Configuration is done according to [Documentation](https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-configuring-the-registry.html#registry-cloud-events_registry) by setting an environment variable:
```
      env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -Dregistry.events.sink.my-test-sink=http://cloudevents-helper.test-ns.svc.cluster.local:8080/events
```

Connection is working since calling the test-sink with curl from the container terminal is working perfectly fine:
```
sh-4.4$ curl -vvv -X POST "Content-Type:application/json" -d '{"hello":"event"}' http://cloudevents-helper.test-ns.svc.cluster.local:8080/events
...
> Connected to cloudevents-helper.test-ns.svc.cluster.local (10.140.99.124) port 8080 (#0)
*   Trying 10.140.99.124...
> POST /events HTTP/1.1
> Host: cloudevents-helper.test-ns.svc.cluster.local:8080
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Length: 17
> Content-Type: application/x-www-form-urlencoded
* upload completely sent off: 17 out of 17 bytes
< HTTP/1.1 204 No Content
< Content-Type: */*;charset=UTF-8
```

The log of the test-sink is as follows:
```
2022-11-17 11:13:02,605 INFO  [ch.hel.clo.imp.res.EchoResource] (executor-thread-0) Body:
{"hello":"event"}

2022-11-17 11:13:02,609 INFO  [ch.hel.clo.imp.res.EchoResource] (executor-thread-0) Headers:
content-length: 17
Accept: */*
Host: cloudevents-helper.test-ns.svc.cluster.local:8080
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.61.1
```

The same error occurs when calling an OpenShift route or only the local service name since the test-sink is in the same namespace as the apicurio-registry container.
Setting the log level to debug or trace gives no more information.

regards,
Christian

**Comment by EricWittmann** [comment]
This is really strange, since the stack trace certainly implies that the connection is being attempted on localhost on port 80.  Even though clearly the configuration is not that.

We haven't been able to reproduce this locally.  Although I'm not sure we've tested it in a docker compose or k8s environment.  What version of OpenShift are you using?

**Comment by 1indiangirl** [comment]
It's not strange, you can Take latest version of registry mem. We have
already specified configuration which is mentioned on site.

Create simple rest API host it on docker.

 When new schema is added it gives error as connection failed but
application is up running

Please provide bug fix on that

**Comment by cs0978** [comment]
We can reproduce this behavior with OpenShift 4.9 and 4.10.
The error still exist after upgrading to version 2.3.1 of the Apicurio Registry.

**Comment by EricWittmann** [comment]
We've reproduced this as well and Carles has fixed the issue in this PR:

https://github.com/Apicurio/apicurio-registry/pull/3042

**Comment by EricWittmann** [comment]
I'll do a new release today and you can test 2.4.2.Final.
