### ISSUE TITLE
Fix kafkasql node creation on slow machines with already existing messages.

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#2991]
For slower compute nodes, the internal H2 DB that we use might not be ready at the time that the Kafka consumer thread starts.  This results in consuming existing messages from the Kafka topic *before* the internal DB is ready to store them.

The workaround is to increase the startup delay of the Kafka message consumer thread. 

We will be attempting to fix this problem with some sort of thread notification strategy (where the thread that creates the H2 internal DB will notify the Kafka consumer thread when it's ready to go).

**Comment by EricWittmann** [comment]
The decision on this was to make the `initialize` logic in the abstract SQL storage available as a `CompletableFuture`.  This will allow the kafka storage impl to chain together the DB initialization with the startup of the Kafka consumer thread.

**Comment by EricWittmann** [comment]
Change of plan:  I decided to use CDI events to solve this problem:

https://github.com/Apicurio/apicurio-registry/pull/3058
