### ISSUE TITLE
`apicurio.registry.check-period-ms` is turned on by default

### ISSUE THREAD

**Issue by vjuranek** [Apicurio/apicurio-registry#2997]
While documentation for `apicurio.registry.check-period-ms` [says](https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/getting-started/assembly-configuring-kafka-client-serdes.html): *Specifies how long to cache artifacts before auto-eviction. If not set, artifacts are fetched every time.* and the default should be `None`, i.e. not set. It's actually turned on with the default of 30s (I guess it's caused by setup [here](https://github.com/Apicurio/apicurio-registry/blob/main/serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractSchemaResolver.java#L131) and how the values is obtained [here](https://github.com/Apicurio/apicurio-registry/blob/main/schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java#L173)).

This is a serious issue, as the behaviour is unexpected and can lead to errors which are very hard to debug  (besides other things because of when using debugger, cache during debugging expires and issue cannot be reproduce during debugging).

**Comment by jsenko** [comment]
I'm working on fixing this. I found more differences with the documentation.
