### ISSUE TITLE
Improve Avro canonicalizer

### ISSUE THREAD

**Issue by prestona** [Apicurio/apicurio-registry#300]
The [current implementation](https://github.com/Apicurio/apicurio-registry/blob/0ced3f4874928773299d6a604d561ab5e754f9fb/app/src/main/java/io/apicurio/registry/content/canon/AvroContentCanonicalizer.java#L51-L79) misses some situations where schemas are semantically the same. For example, if one rendering of a schema specifies a namespace and another specifies full names:

```json
{"name":"n","namespace":"ns","type":"record","fields":[]}
```
is essentially the same schema as:
```json
{"name":"ns.n","type":"record","fields":[]}
```

Another example is when a schema contains a `doc` attribute, which exists to provide user documentation and is ignored when the schema is used for serialization or resolution. So this schema:

```json
{"name":"n","type":"record","fields":[],"doc":"Hello world"}
```
can be processed the same as this schema:
```json
{"name":"n","type":"record","fields":[],"doc":"Hi world!"}
````

Currently the registry will treat the above as separate schemas, when retrieving an artifact's metadata by content (e.g. a GET request to `/artifacts/{artifactId}/meta`). This behaviour can also be observed by Kafka client serdes that fetch a schema with metadata by schema content
(e.g. a POST to `/ccompat/subjects/{schema}`).

I think that the canonicalization used for Avro could be improved by comparing
schemas using [Parsing Canonical Form](https://avro.apache.org/docs/current/spec.html#Parsing+Canonical+Form+for+Schemas) which the Avro spec describes as:
> ...a transformation of a writer's schema that let's us define what it means
> for two schemas to be "the same" for the purpose of reading data written
> against the schema.

This transformation is implemented by the [SchemaNormalization](https://avro.apache.org/docs/current/api/java/org/apache/avro/SchemaNormalization.html) class which is part of the Java Avro implementation.

If this sounds like a useful improvement, I'm happy to open a PR that switches over the implementation of `AvroContentCanonicalizer`.

**Comment by alesj** [comment]
@prestona hmmm, I remember looking into this SchemaNormalization, but cannot remember the exact reason now why I didn't use it.
I sort of have in mind that it didn't produce equals true, for the schemas that only had fields in different order.

But yeah, please go ahead with the PR.

**Comment by alesj** [comment]
> But yeah, please go ahead with the PR.

Do it against 1.1.x branch.
And include those good examples from above. ;-)

**Comment by prestona** [comment]
Investigating further, I think I might have re-discovered why you rejected a canonical format based on parsing normal form: it discards the `default` property of the schemas.

There's a number of discussion threads [like this one](http://apache-avro.679487.n3.nabble.com/Why-canonical-form-excludes-default-tt4037230.html#a4037237) about why this is, and also [AVRO-2299](https://issues.apache.org/jira/browse/AVRO-2299) which describes why having a more permissive normalization format would be useful.

The net is that parsing normal form wouldn't be able to distinguish between these this schema:
```json
{
  "type": "record",
  "name": "car",
  "fields":[
    {"name": "color", "type": "string", "default":"red"}
   ]
}
```
And this schema that specifies a different default value for the color field:
```json
{
  "type": "record",
  "name": "car",
  "fields":[
    {"name": "color", "type": "string", "default":"blue"}
   ]
}
```

I think this would be a _bad thing_:tm: as it introduces the potential for confusion between Kafka producers and consumers as to how to interpret data that omits a value for the `color` attribute.

It looks like the new concept of Standard Canonical Form would be a better candidate for normalizing Avro, unfortunately the [PR for this addition](https://github.com/apache/avro/pull/805) is still awaiting review and missed the 1.9.2 revision of the Avro specification.

**Comment by forsberg** [comment]
I hit a side-effect of this today in a rather annoying way. Consider the following example schema:

```
{'type': 'record',
 'name': 'ID',
 'namespace': 'com.example',
 'fields': [{'doc': 'ID', 'name': 'id', 'type': 'int'}]}
```

1. I used the [Python Schema Registry Client](https://marcosschroh.github.io/python-schema-registry-client/) to register my schema. For some reason, it runs the schema through fastavro.parse_schema first, which transforms it into this:

```
{'type': 'record',
 'name': 'com.example.ID',
 'fields': [{'doc': 'ID', 'name': 'id', 'type': 'int'}],
 '__fastavro_parsed': True,
 '__named_schemas': {'com.example.ID': {'type': 'record',
   'name': 'com.example.ID',
   'fields': [{'doc': 'ID', 'name': 'id', 'type': 'int'}]}}}
```

Note: the *name* was modified to include the namespace, and namespace field removed. This is perfectly fine.

2. I publish messages to Avro topic, and try to use [The Kafka Connect S3 Connector](https://docs.confluent.io/current/connect/kafka-connect-s3/index.html) to read them and save on S3.

The S3 connector first retrieves the schema ID by use of /api/ccompat/schemas/ids endpoint of Apicurio Registry, and then does a POST to /api/ccompat/subjects/<topic>-<key|value> to check which subject-version the schema has. However, as it turns out, the S3 Connector reformats the schema into its namespaced form again, i.e. the first representation above.

3. Apicurio registry, not understanding that both are exactly the same schema, responds with a 404, and S3 Connector is unhappy and crashes :-(

**Comment by EricWittmann** [comment]
That is actionable.  We could certain update the canonicalizer to format the name/namespace in a consistent way.  Thoughts @alesj or @katheris ?

**Comment by alesj** [comment]
@EricWittmann I would wait for this to get into Avro lib itself ...

**Comment by EricWittmann** [comment]
We're not using the Avro library to do canonicalization of Avro schemas right now - why wait for a change to the Avro lib.  Or are you saying that `org.example:schema-name` and `:org.example.schema-name` are not actually identical?

Now that I ask that question - it is quite weird that they would be the same.  That sure isn't how it would work in e.g. XML - those would be distinct QNames.

**Comment by alesj** [comment]
> We're not using the Avro library to do canonicalization of Avro schemas right now

Yeah, b/c there is none such mechanism.
It's been in the works forever ... which is weird ... or not, as it's not a simple problem.

I guess we could try to add this, but I'm pretty sure there will be some new issue really soon ... :-)

**Comment by udinnet** [comment]
Sorry for digging up this old issue thread. As per #2279, a new Canonicalizer has been introduced into v6 Ccompat APIs using `ENABLE_CCOMPAT_CANONICAL_HASH_MODE`. Something that I noticed with it is that it reorders the JSON fields of the schema. This means 

```
"fields": [
    {
      "name": "name",
      "type": "string",
      "doc": "The name of the application"
    },
    {
      "name": "version",
      "type": [
        "null",
        "string"
      ],
      "doc": "(Optional) The application version",
      "default": null
    },
    {
      "name": "owner",
      "type": [
        "null",
        "string"
      ],
      "doc": "The owner of the application",
      "default": null
    }
  ]
```

and 

```
  "fields": [
    {
      "name": "version",
      "type": [
        "null",
        "string"
      ],
      "doc": "(Optional) The application version",
      "default": null
    },
    {
      "name": "name",
      "type": "string",
      "doc": "The name of the application"
    },
    {
      "name": "owner",
      "type": [
        "null",
        "string"
      ],
      "doc": "The owner of the application",
      "default": null
    }
  ]
```

Evaluated as equal during the comparison. This might be an issue during the schema evolution. The Avro language specification says, `A record is encoded by encoding the values of its fields in the order that they are declared. In other words, a record is encoded as just the concatenation of the encodings of its fields. Field values are encoded per their schema.`. So evaluating differently ordered schemas to be equal might be a problem. 

At this moment, we've forked Apicurio to introduce a more sophisticated Avro Canonicalizer from our end. I would also like to know what is the way forward of this and whether there is a chance to contribute our Canonicalizer to Apicurio.

**Comment by carlesarnal** [comment]
Hi @udinnet, what we introduced is not really a new canonicalizer. Is just an option to use the canonical hash in the ccompat api when comparing two schemas by content, the canonicalizer is exactly the same. As per contributing your canonicalizer, please, go ahead, contributions are always more than welcome!

**Comment by udinnet** [comment]
Hi @carlesarnal 
>As per contributing your canonicalizer, please, go ahead, contributions are always more than welcome!

Good to hear. Will do. 

>the canonicalizer is exactly the same

I didn't quite understand this. Which canonicalizer you are referring to? [this](https://github.com/Apicurio/apicurio-registry/blob/main/schema-util/avro/src/main/java/io/apicurio/registry/content/canon/AvroContentCanonicalizer.java) one?

**Comment by carlesarnal** [comment]
> Hi @carlesarnal
> 
> > As per contributing your canonicalizer, please, go ahead, contributions are always more than welcome!
> 
> Good to hear. Will do.
> 
> > the canonicalizer is exactly the same
> 
> I didn't quite understand this. Which canonicalizer you are referring to? [this](https://github.com/Apicurio/apicurio-registry/blob/main/schema-util/avro/src/main/java/io/apicurio/registry/content/canon/AvroContentCanonicalizer.java) one?

Yes, exactly that one.

**Comment by AndreaScarselli** [comment]
Hi @carlesarnal ,

I am going to push the canonicalizer @udinnet was referring to.

Should it replace the currently existing AvroContentCanonicalizer, or should it be possible to select the canonicalizer to use with the configuration?

Thank you,
Andrea

**Comment by carlesarnal** [comment]
Hi @AndreaScarselli,

You can start creating the PR without the configuration. Depending on how it looks etc, we can add the configuration later, or, eventually, if we decide to include your implementation and replace the existing one, we can add a migration process for existing artifacts.

Thanks!

**Comment by AndreaScarselli** [comment]
Hi @carlesarnal ,

Thank you for your quick answer. A PR has been created.

**Comment by carlesarnal** [comment]
A PR has been merged containing this.
