### ISSUE TITLE
[Streams 1.1.x] ArithmeticException: / by zero

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#304]
https://gist.github.com/jsenko/346c29b80924e4dfaad82383285a64cd

This seems to occur only when the # of partitions in a topic is 1.

Source: https://github.com/apache/kafka/blob/2.3.1/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java#L69

**Comment by EricWittmann** [comment]
Was this fixed?

**Comment by EricWittmann** [comment]
@alesj is this something we should be concerned about?

**Comment by alesj** [comment]
I would say this can happen when something is seriously out-of-sync ...
Dunno how to reproduce it or fix it.
Any thoughts @tombentley ?

**Comment by tombentley** [comment]
The fix for [KAFKA-9651](https://issues.apache.org/jira/browse/KAFKA-9651) will be in Kafka 2.6.

**Comment by EricWittmann** [comment]
OK I'll move this to the backlog and we can track it.  We can close it when we upgrade to Kafka 2.6.

**Comment by carlesarnal** [comment]
Closing this as we dropped the streams storage impl.
