### ISSUE TITLE
Support for artifact version deletion

### ISSUE THREAD

**Issue by derickmr** [Apicurio/apicurio-registry#3074]
Consider adding a functionality that allows deleting an artifact version. This is related to this [conversation](https://github.com/Apicurio/apicurio-registry/issues/363#issuecomment-1346807360).

**Comment by derickmr** [comment]
Raised a PR to add this functionality: #3075. cc: @carlesarnal

**Comment by EricWittmann** [comment]
@Apicurio/developers  Any thoughts on the change to allow deletion of versions?

**Comment by EricWittmann** [comment]
Update:  We discussed this last week and, for a variety of reasons, think that we **should** allow versions to be deleted.  I believe @jsenko has responded to the PR with some suggestions.  We'll let that process play out as it will.  :)

There are some edge cases to handle and we will need to update the UI.

**Comment by derickmr** [comment]
Awesome, thank you @EricWittmann and @jsenko. I will follow-up in the PR. Truly appreciate it

**Comment by derickmr** [comment]
Hi @EricWittmann, @jsenko, can I get a review on the PR please? Comments from last review were addressed already. Thanks!
