### ISSUE TITLE
[Kafka 1.1.x] Time-out and InvalidProtocolBufferException

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#308]
https://gist.github.com/jsenko/4cbeb967cd71296efa723414e91346c2

**Comment by jsenko** [comment]
So the error disappeared after recreating the topics, which means it was probably caused by reusing them from -streams. But the 504 is still present on the last 3 out of 4 requests.

```
$ curl -X POST -H "Content-Type: application/json" -H "X-Registry-ArtifactType: JSON" -H "X-Registry-ArtifactId: test13" -d '{"type": "cat", "color": "black"}' http://registry.example.com/artifacts
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
$ curl -X POST -H "Content-Type: application/json" -H "X-Registry-ArtifactType: JSON" -H "X-Registry-ArtifactId: test14" -d '{"type": "cat", "color": "black"}' http://registry.example.com/artifacts
{"createdOn":1583340755045,"modifiedOn":1583340755045,"id":"test14","version":1,"type":"JSON","globalId":0,"state":"ENABLED"}
$ curl -X POST -H "Content-Type: application/json" -H "X-Registry-ArtifactType: JSON" -H "X-Registry-ArtifactId: test14" -d '{"type": "cat", "color": "black"}' http://registry.example.com/artifacts
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
$ curl -X POST -H "Content-Type: application/json" -H "X-Registry-ArtifactType: JSON" -H "X-Registry-ArtifactId: test15" -d '{"type": "cat", "color": "black"}' http://registry.example.com/artifacts
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
```

**Comment by alesj** [comment]
This is with 2+ nodes cluster?

**Comment by jsenko** [comment]
yes

**Comment by alesj** [comment]
Apps / nodes need to see eachother, so that gRPC communcation works.
Imo, we're missing APPLICATION_SERVER env var ... 

> %prod.registry.streams.topology.application.server=${APPLICATION_SERVER:localhost:9000}

Since it looks like "localhost:9000" is not OK?

**Comment by EricWittmann** [comment]
So is `APPLICATION_SERVER` a required property we should be documenting?  I don't think I've seen that in the documentation... and what should the default value be?

**Comment by alesj** [comment]
This is a "host:port" value for gRPC server.
It should be such so that cluster nodes see each other via this host:port ...
(as we then do remote / distributed gRPC lookups between nodes for the actual key owners)

**Comment by EricWittmann** [comment]
OK I get the concept/reason but not the specifics - can you describe a simple two-node configuration and what the value of `APPLICATION_SERVER` would be for each node?

**Comment by alesj** [comment]
See my PR

That the best I know.
Perhaps K8s experts can tell us more.

**Comment by EricWittmann** [comment]
Yeah I just reviewed and merged that.  Trying to internalize it in my brain. :)
