### ISSUE TITLE
How to upload JSON schemas that reference other schemas with $ref

### ISSUE THREAD

**Issue by avi5kdonrh** [Apicurio/apicurio-registry#3086]
## Description

# schema1.json gets uploaded successfully.

```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "schema1.json",
    "type": "object",
    "$defs": {
      "name": {
          "type": "string"
        }
        }
      }
```
# The referencing schema user.json  fails with an error

```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "test/user.json",
  "type": "object",
  "properties": {
    "external": {
      "$ref": "schema1.json#/$defs/name"
    }
  },
  "$defs": {
    "personal": {
      "email": {
        "type": "string",
        "format": "email"
      },
      "birthday": {
        "type": "string",
        "format": "date"
      }
    }
  }
}
```

# Error

JSON schema not valid: java.net.MalformedURLException: no protocol: test/schema1json

# Question

How can we connect different schemas so they can easily refer to each other? If I have already uploaded schema 1 then how should I refer to it from schema 2?

**Registry
Version**: latest 
**Persistence type**: all

**Comment by jsenko** [comment]
I'm going to look into the exception problem.

**Comment by jsenko** [comment]
I've tried to create the example artifacts you provided on both the latest Registry from `main`, and the latest product version from `2.3.0.GA`, but didn't get a `java.net.MalformedURLException`. Can you be more specific about the version you are using? Make sure you are using the correct latest image tags `quay.io/apicurio/apicurio-registry-mem:latest-release` and `quay.io/apicurio/apicurio-registry-mem:latest-snapshot`, and not `quay.io/apicurio/apicurio-registry-mem:latest` accidentally.

As for the references feature in Registry, we currently support recording references using the REST API. Example:

Prepare first artifact content:
```
echo '{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "schema1.json",
    "type": "object",
    "$defs": {
        "name": {
            "type": "string"
        }
    }
}' > artifact1.json
```

Prepare second artifact content:
```
echo '{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "test/user.json",
    "type": "object",
    "properties": {
        "external": {
            "$ref": "schema1.json#/$defs/name"
        }
    },
    "$defs": {
        "personal": {
            "email": {
                "type": "string",
                "format": "email"
            },
            "birthday": {
                "type": "string",
                "format": "date"
            }
        }
    }
}' > artifact2.json
```

Create the first artifact:
```
curl -X POST -d @artifact1.json http://localhost:8080/apis/registry/v2/groups/default/artifacts
```
Returns:
```
{"createdBy":"","createdOn":"2023-02-21T13:49:27Z","modifiedBy":"","modifiedOn":"2023-02-21T13:49:27Z","id":"04614757-f4a9-45c3-bcf9-3a51cc045481","version":"1","type":"JSON","globalId":1,"state":"ENABLED","contentId":1,"references":[]}
```
Create the second artifact, which references the first one:
```
export CONTENT=`jq -R -s '.' < artifact2.json`
curl -X POST -H 'content-type: application/create.extended+json' -d "{\"content\":$CONTENT,\"references\":[{\"artifactId\":\"04614757-f4a9-45c3-bcf9-3a51cc045481\",\"groupId\":\"default\",\"version\":\"1\",\"name\":\"schema1.json\"}]}" http://localhost:8080/apis/registry/v2/groups/default/artifacts
```
Returns:
```
{"createdBy":"","createdOn":"2023-02-21T13:54:41Z","modifiedBy":"","modifiedOn":"2023-02-21T13:54:41Z","id":"111f4ba1-e00c-49bc-ab65-290e71dcae38","version":"1","type":"JSON","globalId":2,"state":"ENABLED","contentId":2,"references":[{"artifactId":"04614757-f4a9-45c3-bcf9-3a51cc045481","version":"1","name":"schema1.json"}]}
```
Get the references again:
```
curl http://localhost:8080/apis/registry/v2/groups/default/artifacts/111f4ba1-e00c-49bc-ab65-290e71dcae38/versions/1/references
```
Returns:
```
[{"artifactId":"04614757-f4a9-45c3-bcf9-3a51cc045481","version":"1","name":"schema1.json"}]
```

This is, however, the current extend of the support for references. We don't yet support adding references via the UI and dereferencing. It would be useful to get more information about you use-case, so we can prioritize improving Registry in this area.

**Comment by jsenko** [comment]
hi, not yet. I have created a [tracking issue](https://github.com/Apicurio/apicurio-registry/issues/6033) for `3.x`. It's unlikely we will add this to `2.x`, so we can focus our efforts on 3.
