### ISSUE TITLE
Ensure the supported APIs are listed in the docs

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#3091]
Add the mention of http://localhost:8080/apis page to the docs, or add the information directly.

**Comment by smccarthy-ie** [comment]
Hi @jsenko, 

We have a section in the intro docs that explains this called "Compatibility with other schema registry REST APIs". 

The http://MY-REGISTRY-URL/apis page is mentioned under "Additional Resources": 

https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-intro-to-the-registry.html#registry-rest-api_registry
