### ISSUE TITLE
Allow deleting artifact versions via the UI

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#3107]

**Comment by EricWittmann** [comment]
Fixed in 3.0.

**Comment by IncandescentChrysalis** [comment]
While this feature is indicated here to have been added to v3, it looks like this issue ended up by mistake in the [2.6.0.Final](https://github.com/Apicurio/apicurio-registry/releases/tag/2.6.0.Final) changelog.

On top of that, the [v3 announcement](https://www.apicur.io/blog/2024/06/17/apicurio-registry-3) is silent about this feature which is worth publicising IMHO.
