### ISSUE TITLE
Apicurio Schema Registry (V 2.4.1.Final) - Security Vulnerability Issues

### ISSUE THREAD

**Issue by ozarkblue** [Apicurio/apicurio-registry#3144]
I've scanned Apicurio Schema Registry (V 2.4.1.Final) Docker image (that is in Docker Hub) with our enterprise image scan S/W and found below security vulnerability issues:
High Risk : 25 issues
Medium Risk :61
Low Risks :20

Lot of these issues (around 40 if them ) have fix available (as provided links and reference in each lines) and most of them are related to dependency package.

Report Attached:
[Security Vulnarability Issues - Apicurio 2.4.1.Final.docx](https://github.com/Apicurio/apicurio-registry/files/10701783/Security.Vulnarability.Issues.-.Apicurio.2.4.1.Final.docx)

@EricWittmann @carlesarnal would you pls help to address these in future releases.Looking fwd for the fixed version.
I'm hoping considering security vulnerability risks these will have some priority on your triaging.

**Comment by ozarkblue** [comment]
Hi @carlesarnal thanks for checking these and your update/assurance.
Looking fwd for next release with the fixes.
 
For enterprise usage these security scan findings are treated with high importance.

**Comment by EricWittmann** [comment]
We have some internal (to Red Hat) challenges with upgrading Quarkus.  We have ongoing discussions about this topic.  You have inspired another round.  :)

**Comment by ozarkblue** [comment]
@EricWittmann Thanks for reviewing this. These are reported security vulnerability issues from our enterprise level image scan. I'm sure other organization users also will surface this in coming days. 
So any effort to prioritizing the effort to fix these are appreciated and I'm sure it's in your consideration as well.

Here is latest scan report on Apicurio Registry image - 2.4.1.Final with proposed solution as well (Right most Column)
[Security Scan report -Apicurio Registry 2.4.1.Final.xlsx](https://github.com/Apicurio/apicurio-registry/files/10900785/Security.Scan.report.-Apicurio.Registry.2.4.1.Final.xlsx)

**Comment by carlesarnal** [comment]
Hi @ozarkblue as the outcome of the discussion Eric mentioned earlier, we decided to upgrade Quarkus to the latest final version. That should allow us to fix most of the underlying security vulnerabilities. In addition to that, we're aiming to migrate to Quarkus 3 as soon as the final version is out, so expect us to be way more diligent with security vulnerabilities thanks to the new Quarkus upgrade flow we're gonna implement.

**Comment by samuel-hawker** [comment]
Hi, just curious what the timeline on this Quarkus 3 upgrade is, did you need any assistance with it, is there an issue with oustanding work required prior to the quarkus 3 upgrade that myself or my colleagues could help push forward?

**Comment by carlesarnal** [comment]
The timeline is this month. We've been blocked essentially by a release, but the last release with Quarkus 2 will be released today and then I have a PR already created https://github.com/Apicurio/apicurio-registry/actions/runs/5808694440/job/15746007042?pr=3566 with the upgrade to Quarkus 3. Once this is done, I'll do another release that will be the first one based on Quarkus 3 (likely 2.5.0.Final).

**Comment by ozarkblue** [comment]
sounds good @carlesarnal . thanks for the update in this thread. Looking fwd for the update
