### ISSUE TITLE
Document the artifact references feature

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#3165]
We don't have documentation for the new REST API endpoints that allow for recording references information.

**Comment by smccarthy-ie** [comment]
Hi @jsenko 

We have the following doc on how to use the REST API with artifact references :
https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-managing-registry-artifacts-api.html#managing-artifact-references-using-rest-api_registry

**Comment by jsenko** [comment]
Ahh, I missed that! Thanks for letting me know, closing this:)
