### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#3185]
## Description

**Registry
Version**:  Server version 2.3.0 client library version 2.4.1
**Persistence type**:  "sql"

We are getting below intermittent errors while doing validation using apicurio library

Error Message : [com.fasterxml.jackson.databind.JsonMappingException: multiple points (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])].

Error Message : [com.fasterxml.jackson.databind.JsonMappingException: For input string: "2002233.E20022334E4" (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["modifiedOn"])]

### Expected vs Actual Behaviour

Validation should be successful without error as the error is coming intermittent

### Logs

Error Message : [com.fasterxml.jackson.databind.JsonMappingException: multiple points (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])].

Error Message : [com.fasterxml.jackson.databind.JsonMappingException: For input string: "2002233.E20022334E4" (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["modifiedOn"])]

**Comment by jsenko** [comment]
Do you have any additional information about the error, like a stack trace, anything that stands out about your environment or configuration, or anything else that would help with investigation?

**Comment by Gourav2912** [comment]
@jsenko As @ohadpinch mentioned for us also it coming in coming when validation is run on concurrently on different threads.
As I mentioned we don't have any other configurations below is our APICurio stack for registry as well as library. 
Registry
Version: Server version 2.3.0 client library version 2.4.1
Persistence type: "sql"

**Comment by Gourav2912** [comment]
@jsenko  PFA the project to reproduce the issue.
Please run Create.java to register the schema in your local apicurio.
Run Main.java which start 5 thread for validation of data with registered schema.
Error can be reproduced with run 
[apicurio-issue.zip](https://github.com/Apicurio/apicurio-registry/files/11077756/apicurio-issue.zip)
