### ISSUE TITLE
Allow for public read-only console access that bypasses keycloak, but still use keycloak for API access

### ISSUE THREAD

**Issue by dlydiard** [Apicurio/apicurio-registry#3192]
### Feature or Problem Description

My use case is that I want the console to be publically accessible for both internal and external users in a read-only mode and bypass the KeyCloak login redirects. I do not want console users to register or use social IDPs. However, I still want to use KeyCloak auth for API requests (read/write). Can ApiCurio be configured to do this?

**Comment by carlesarnal** [comment]
Hi @dlydiard,

No, this is not possible with the current configuration options. The only way I see to achieve something similar would be to deploy the UI and the API in the same cluster and make the API accessible only within the cluster (with no Keycloas server involved).

If you want to elaborate on the use case, I'm more than happy to discuss it.

**Comment by dlydiard** [comment]
Our use case is that we want the UI to be read-only so that internal and external customers can view all registry data without requiring any login flows. At the same time we do not want external customers to have write access to the API. Our CI/CD pipelines should be the only authorized API accounts that can publish to the registry.

**Comment by carlesarnal** [comment]
So, the short answer is not, this is not supported. That said, the long answer is that it's achievable with the current code, but not using the published images out of the box. What you need is, essentially, to deploy the UI independently from Registry with the following configuration  -> 
![imagen](https://user-images.githubusercontent.com/12640103/224939508-96d87837-e387-4a08-a0ff-52d73ba970ea.png)

That would just configure the UI to start in read-only mode.

In addition to that, you must configure Registry with the following configuration -> 
![imagen](https://user-images.githubusercontent.com/12640103/224939992-f1f94468-74bc-425e-b9a6-9291b632dce8.png)

This second configuration starts the Registry application with authentication enabled, while at the same time, it disables the UI *and* allows anonymous users (unauthenticated) to perform read operations in Registry.

As you can see not very handy, but it is achievable (I just tested it locally and it works with no issues).

**Comment by dlydiard** [comment]
this is helpful, i will look into this, thanks!
