### ISSUE TITLE
REGISTRY_UI_FEATURES_READONLY mode isn't readonly

### ISSUE THREAD

**Issue by dlydiard** [Apicurio/apicurio-registry#3193]
## Description

**Registry
Version**:  2.4.1.Final
**Persistence type**: in-memory

### Environment
OpenShift 4.11

### Steps to Reproduce

I enabled the environment variable `REGISTRY_UI_FEATURES_READONLY=true` and the UI still allows any user to upload artifacts via UI elements, as well as navigate to the "settings" tab and change global settings. This is with `AUTH_ENABLED=false`.

### Expected vs Actual Behaviour

I expect the UI to truly be read-only and not show UI elements that are a path to mutations. I realize the API is left unprotected in this mode, but this is a separate use case. I'm just targeting UI elements that should not appear in the mode like the "upload artifacts modal" and "settings" tab.

### Logs

![image](https://user-images.githubusercontent.com/1084777/224845472-791007a4-f1c8-463e-b77c-3baf33e134e4.png)

**Comment by carlesarnal** [comment]
Hello @dlydiard,

This feature only works when authentication is enabled, as you can see in the following code example. 
![imagen](https://user-images.githubusercontent.com/12640103/224934006-758645a6-703a-4625-9471-d25a1350a369.png)

**Comment by dlydiard** [comment]
If i set the `REGISTRY_UI_FEATURES_READONLY` flag to false an upload button appears (keycloak not configured for both true/false). So this is a little confusing since the flag mostly works without keycloak setup. 

If `REGISTRY_UI_FEATURES_READONLY` is set to true, shouldn't auth checks be ignored in the UI? Readonly means readonly regardless of auth settings?

**Comment by carlesarnal** [comment]
> If i set the `REGISTRY_UI_FEATURES_READONLY` flag to false an upload button appears (auth not configured for both true/false). So this is a little confusing since the flag mostly works without auth setup.
> 
> If `REGISTRY_UI_FEATURES_READONLY` is set to true, shouldn't auth checks be ignored in the UI? Readonly means readonly regardless of auth settings?

Ok, I got you now. There is indeed a missing check in the upload multiple artifacts parts, that option should not be there in the readonly mode. As for the settings page, there is a property to hide that page on this mode `REGISTRY_UI_FEATURES_SETTINGS`.

**Comment by dlydiard** [comment]
I tried `REGISTRY_UI_FEATURES_SETTINGS` but it did not work. I also did see the variable referenced in code https://github.com/search?q=repo%3AApicurio%2Fapicurio-registry%20REGISTRY_UI_FEATURES_SETTINGS&type=code
