### ISSUE TITLE
Schema not updated when the version of the reference changes

### ISSUE THREAD

**Issue by mouadk** [Apicurio/apicurio-registry#3203]
Hello. It looks like Apicurio server does not take into account the version of the references while checking If the schema has changed. For example when registering a schema as follows: 

```
{
 "schema": "{\"type\":\"record\",\"name\":\"Metadata\",\"namespace\":\"com.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UniqueId\"}]}",
 "schemaType": "AVRO",
 "references": [
    {
       "name": "com.avro.task",
       "subject":  "com.avro.task",
       "version": 1
    }
  ]
}

Response: 200 OK 
{
    "id": 2
}

```

When the reference is updated, the ID returned is the same and the schema is not updated (one can even use a dummy ID and the server does not check it). 

```
{
 "schema": "{\"type\":\"record\",\"name\":\"Metadata\",\"namespace\":\"com.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UniqueId\"}]}",
 "schemaType": "AVRO",
 "references": [
    {
       "name": "com.avro.task",
       "subject":  "com.avro.task",
       "version": 88889999999
    }
  ]
}

Response: 200 OK 
{
    "id": 2
}
```

I tested this on a vanilla confluent schema registry and the behaviour is correct. 

I am using Apicurio version 2.4.1.Final

**Comment by carlesarnal** [comment]
Hi @mouadk,

We're aware of this and is because of this https://github.com/Apicurio/apicurio-registry/issues/3109. We're actively working on getting this solved.
