### ISSUE TITLE
Document minimal permisions for kafkasql topic

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#3238]
See https://access.redhat.com/solutions/7004644
Related to https://github.com/Apicurio/apicurio-registry/issues/3196
CC @smccarthy-ie

**Comment by smccarthy-ie** [comment]
@jsenko Please review/merge https://github.com/Apicurio/apicurio-registry-operator/pull/202 to address customer isssue. Thanks.
