### ISSUE TITLE
Get All Artifacts: implement LIMIT for all storages

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#328]
We recently introduced a Get All Artifacts operation to the Apicurio Registry REST API.  It does not support filtering or sorting or (most importantly) paging.  So we should implement a LIMIT in each of the storage impls to avoid edge cases where the registry is holding a very large number of artifacts.

**Comment by carlesarnal** [comment]
Hi, @EricWittmann, this still applies after the introduction of the search operation? Should this operation be deprecated or at least discourage its usage?

**Comment by EricWittmann** [comment]
Yes it should be discouraged.  All we want here is to introduce a LIMIT at e.g. the JPA level and in-memory impls so that we don't return 100,000,000 IDs.  Just put a sensible ceiling on it and call it a day.  Maybe 1000 or 10,000?
