### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#3283]
### Feature or Problem Description

Support Java 17

**Comment by carlesarnal** [comment]
Java 17 is already supported. Our workflows are running using it.

**Comment by Gourav2912** [comment]
What i meant was to compile and package  the library using java 17 currently all apicurio code is compile with java 11

https://github.com/Apicurio/apicurio-registry/blob/main/pom.xml
  <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
