### ISSUE TITLE
Direct access grant for 2.4.2

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry#3285]
In version 2.4.1 we where able to to use basic auth and this was mapped to a resource owner password grant (keycloak direct access grant) with this code https://github.com/Apicurio/apicurio-registry/blob/2.4.1.Final/app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java#L154.

Somehow this is gone in 2.4.2. Are we still able to use the 2.4.2 the same as in 2.4.1?

**Comment by carlesarnal** [comment]
@dweber019 it should be working (although it is discouraged). Do you have any stacktrace or anything to help reproduce the problem?

**Comment by dweber019** [comment]
I was browsing the code and noticed the change described above. So I wondered if basic auth with username and password, which will be converted to a resource owner password grant (direct access grant called in Keycloak) is gone.
Sadly I can't reproduce this quickly as https://github.com/Apicurio/apicurio-registry/blob/main/distro/docker-compose/src/main/resources/docker-compose.apicurio.yml isn't working on macs.

I close the issue as you stated this still works.
