### ISSUE TITLE
KSQL storage: unable to start up Apicurio 2.4.2 with schema references

### ISSUE THREAD

**Issue by bootyeaterboy** [Apicurio/apicurio-registry#3287]
### Setup
- Apicurio Version: 2.4.2.Final
- Storage: KafkaSQL
- Schema type: Protobuf
### How to reproduce
1. Start up Apicurio with an empty kafkasql-journal topic (default config).
2. Register 5 Protobuf schemas referencing each other in the following way: a.proto and b.proto reference c.proto, c.proto and d.proto reference e.proto.
4. Restart the current Apicurio pod or start another one.
5. The pod doesn't get up because Apicurio is unable to consume its own messages on startup, which leads to the following logs.
### Logs
```
DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Registry exception detected: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.h2.jdbc.JdbcSQLDataException: Parameter "#4" is not set; SQL statement:
UPDATE content SET canonicalHash = ? WHERE tenantId = ? AND contentId = ? AND contentHash = ? [90012-214]
...
DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlUpgrader$KafkaSqlProtobufCanonicalizerUpgrader] (KSQL Kafka Consumer Thread) Protobuf content canonicalHash outdated value detected, updating contentId 2
...
INFO <_> [io.smallrye.health.SmallRyeHealthReporter] (executor-thread-5) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Database connections health check","status":"UP","data":{"<default>":"UP"}},{"name":"PersistenceSimpleReadinessCheck","status":"DOWN"},{"name":"ResponseTimeoutReadinessCheck","status":"UP","data":{"errorCount":0}}]}
INFO <_> [io.quarkus.bootstrap.runner.Timing] (main) apicurio-registry-storage-kafkasql stopped in 0.322s
```
### Messages in kafkasql-journal
After Apicurio unsuccessfully tried to start up, messages such as the following are produced to kafkasql-journal, repeatedly:

**Key:** {"tenantId":"_","contentHash":"6c5deb6b624e4a51d3c79635df3ff2b9f9df9abfaa827efff6f24d7a1f8cd6dd","contentId":2}
**Message:** .....@972de3c38a73a0d69db6c251bf0eef56d3fdce6c1bb65049a234f8f2f76c4679........
### Additional notes
- After the upgrade to Apicurio 2.4.2 and registering schemas with references as described above, a rollback to Apicurio 2.4.1 is not possible - at least not without removing the new schemas from kafkasql-journal first - since Apicurio 2.4.1 is also unable to consume these schemas.
- This is a problem during start up. If I start up Apicurio with an empty kafkasql-journal and migrate Apicurio's Kafka messages into the topic, it works.

**Comment by carlesarnal** [comment]
Hi @bootyeaterboy,

Thanks for raising this. I have confirmed the bug and created a PR for fixing it.

Thanks
