### ISSUE TITLE
Apicurio Registry uses outdated Keycloak context path

### ISSUE THREAD

**Issue by internetcoffeephone** [Apicurio/apicurio-registry#3315]
## Description

**Registry
Version**: 2.4.2.Final
**Persistence type**: sql

Keycloak version 17 removed `/auth` from the default context path.
The context path should probably be changed in Apicurio Registry so that it works with the Keycloak defaults again.

### Steps to Reproduce

Launch the Apicurio Registry 2.4.2.Final image in combination with the Keycloak image `quay.io/keycloak/keycloak:21.1.1`. See [Keycloak docs](https://www.keycloak.org/getting-started/getting-started-docker) for instructions on how to launch it.

For the Apicurio container, configure the environment variable `KEYCLOAK_URL` as such:
`KEYCLOAK_URL="${url}:${port}/auth"`

Now, check the Apicurio Registry logs.

### Expected vs Actual Behaviour

Expected behavior: the Keycloak connection works
Actual behavior: this error is printed:

`2023-05-04 09:33:04 WARN <> [null] (vert.x-eventloop-thread-1) OIDC server is not available at the '${url}:${port}/auth/realms/${realm}' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'`

### Temporary workaround
A temporary workaround is building Keycloak with the `--http-relative-path /auth` flag.

**Comment by carlesarnal** [comment]
Hello @internetcoffeephone 

I don't think there's a bug here, although I get that the configuration is currently a bit confusing (we're aiming to fix that in future releases).

To configure the Keycloak you have two options.
-  Set `REGISTRY_AUTH_URL_CONFIGURED` to the value of the full URL, with the format `"${url}:${port}/${realm}"`.
-  Alternatively, you can set `KEYCLOAK_URL` *and* `KEYCLOAK_REALM`. For the URL part, you can use the format "${url}:${port}" (I have used it with no issues).

Maybe you're missing the realm configuration in your setup?

**Comment by internetcoffeephone** [comment]
Hey @carlesarnal!

I have done the latter, and have defined both `KEYCLOAK_URL` and `KEYCLOAK_REALM`.
Both are used in the final URL. The problem is that the format of the URL is wrong for Keycloak 17 and onwards.

E.g. when setting
`KEYCLOAK_URL=localhost:8080/auth`
`KEYCLOAK_REALM=registry`
the URL generated by Apicurio Registry is:
`localhost:8080/auth/realms/registry`
But the Keycloak URL that actually works is:
`localhost:8080/realms/registry/protocol/openid-connect/auth`

This is due to the Keycloak [migration](https://www.keycloak.org/migration/migrating-to-quarkus) to a Quarkus distribution. To quote directly:
>`/auth` removed from the default context path

The way I found this was by inspecting `localhost:8080/realms/registry/.well-known/openid-configuration` (which I found a link to in the Keycloak admin panel). On this page, the above URL is listed as the `authorization_endpoint`.

The first option isn't mentioned in the [guide](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-the-registry.html). Might be useful to add it there?
Or to simplify things, resolve https://github.com/Apicurio/apicurio-registry/issues/3308 and use the `.well-known` to configure all the endpoints.

**Comment by carlesarnal** [comment]
Yes, if you add /auth that is not gonna work for Keycloak >=17, the question is, why are you adding it when configuring the KEYCLOAK_URL parameter?

If you set KEYCLOAK_URL to `http://localhost:8080` and set the KEYCLOAK_REALM to `registry` it just works.

**Comment by internetcoffeephone** [comment]
Ah, that makes sense, thanks! Just tried it, it works.

I added `/auth` to the `KEYCLOAK_URL` parameter because the [configuration guide](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-the-registry.html) told me to.
https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc#L44

It's present in many other places as well.
E.g. https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/utils/tests/src/main/java/io/apicurio/registry/utils/tests/JWKSMockServer.java#L74
https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/new-system-tests/src/test/resources/apicurio/02_registry_sql_keycloak.yaml#L14
https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/new-system-tests/src/test/resources/keycloak/02_deployment.yaml#L28
https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/app/src/main/resources/application.properties#L30
https://github.com/Apicurio/apicurio-registry/blob/de7940c2f25351c6c02600639bcf6f93312b5600/ui/src/services/config/config.service.ts#L30

**Comment by carlesarnal** [comment]
Yes, it's present because the documentation and examples were created before keycloak removed it. We need to update the documentation accordingly. 

cc @smccarthy-ie

**Comment by smccarthy-ie** [comment]
The documentation part of this issue is addressed in https://github.com/Apicurio/apicurio-registry/pull/3537. 

@carlesarnal @EricWittmann The other parts (e.g., system tests and app config) might be addressed under different PRs?

**Comment by carlesarnal** [comment]
Yes, anything else related to this will be addressed in other PRs. Thanks, @smccarthy-ie. I'm closing this since the other places are still there because we haven't been able to update the tests yet to use newer versions of Keycloak but the application handles the scenario properly and the documentation has been updated.
