### ISSUE TITLE
Deploy: Use Quarkus configuration & conf. profiles

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#34]
Use Quarkus's configuration system to create a set of profiles for various kind of deployment scenarios, including selection of the persistence layer implementation and logging.

Profiles could be e.g.: dev (h2 DB), single (PostgreSQL) cluster (Infinispan), kafka, ...

Resources:
 - https://quarkus.io/guides/application-configuration-guide#configuration-profiles

**Comment by EricWittmann** [comment]
Where are we on this? @jsenko @alesj

**Comment by alesj** [comment]
What's the use-case here?
Atm I simply put all config into single application.properties, and impls use what they need.

**Comment by jsenko** [comment]
I think we can close this after @alesj adds the Kafka info as in PR #80

**Comment by alesj** [comment]
@jsenko what's missing? I did add dev/prod info into docs ...
