### ISSUE TITLE
RegistryFacade - improve default detection of apicurio-registry-app-1.1.2-SNAPSHOT-runner.jar

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#347]
Right now the `DEFAULT_REGISTRY_JAR_PATH` in `RegistryFacade` breaks whenever we do a release (because the version changes).  We should update the test code to search for an appropriate runner .jar file instead of just assuming one is there.

**Comment by alesj** [comment]
public void start() {
        String path = REGISTRY_JAR_PATH;
        if (path == null) {
            String version = System.getProperty("project.version");
            path = String.format(REGISTRY_JAR_PATH_FORMAT, version);
        }
        LOGGER.info("Starting Registry app from: {}", path);

**Comment by alesj** [comment]
This fixes things for Maven.
If you run this from IDE, either we need a new mechanism or you set this property yourself.

**Comment by jsenko** [comment]
I made some quick improvements here https://github.com/Apicurio/apicurio-registry/pull/357/commits/24d48bd70f4c17357ee7268697830f919bc18626#diff-845d93f2ac542f8639357cfcdbba7fa5L36
I will alert you if the project version is not supplied.

**Comment by EricWittmann** [comment]
OK that's a good change.  Could you update the message to explain how to fix the issue when running from an IDE (ie which property to set)?

At some point I'd like to also write a little bit of code that tries to figure out what to use - it's not hard to make some guesses about the path.
