### ISSUE TITLE
Better display of group ID in UI

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#3489]
There was a suggestion from Breda to add group ID into the `Overview / Version details` panel. We could consider this, but I noticed that there is also no group in the breadcrumbs, which leads to consideration about how we display group ID in general. There is no group ID in the artifact version pages at all, only in the artifact list page.

**Comment by smccarthy-ie** [comment]
@EricWittmann I'm seeing group ID in breadcrumbs, which also usefully filters artifacts by group when clicked:  

![Screenshot from 2023-07-06 11-56-46](https://github.com/Apicurio/apicurio-registry/assets/29098561/6663d4b1-bd30-4aa8-b17c-302261b46817)

But agree that it might also be useful to display the group ID in the details. I notice that the `default` group is not displayed at all in the UI. I think it should be displayed in the breadcrumbs, same as `my-group`above? It's useful to know that the `default ` group exists, especially when it comes to using the API, which requires you to specify the group ID.

**Comment by EricWittmann** [comment]
Closing as stale.
