### ISSUE TITLE
Allow expanding/collapsing groups in UI

### ISSUE THREAD

**Issue by forsberg** [Apicurio/apicurio-registry#3562]
### Feature or Problem Description

Having a lot of artifacts (200+), with many artifacts duplicated in multiple groups (due to review environments etc), the UI quickly gets a bit hard to navigate. 

### Proposed Solution

Allow expanding/collapsing the artifact groups, i.e show only groups by default, and allow expanding them to see their artifacts.

**Comment by EricWittmann** [comment]
The UI has been redesigned for 3.0 and I believe this can be considered fixed.  The information flow in the 3.0 UI is different now: 

* You can search for just Groups
* You can search for Artifacts
* You can click on a Group and manage its metadata **and** list its artifacts

Also these things:

* Artifacts have their own metadata
* The Artifact Detail page now allows managing the metadata
* The Artifact Detail page now shows the list of versions (not as a dropdown but as a table)

So the UI now has these tiers:

1. Explore (search for artifacts or groups)
2. Group Detail page (show metadata, rules, and artifacts)
3. Artifact Detail page (show metadata, rules, and versions)
4. Version Detail page (show metadata, content, docs)
