### ISSUE TITLE
Global compatibility rule execution broken for RuleApplicationType.CREATE

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#358]
Reproduction steps:
- Create a global compatibility rule
- Before creating an artifact, run a `RuleApplicationType.CREATE` rule check on the content
- The global rule runs, but because it requires a "current" artifact version content, which is not present, it crashes with an NPE

**Comment by jsenko** [comment]
This could be solved by a `null` check, but can happen again if we add more rules, so it should be clearly documented

**Comment by alesj** [comment]
Add a test for this ;-)

**Comment by EricWittmann** [comment]
Perhaps each rule should indicate whether it requires previous content or not.  That way we can know to skip some rules for `CREATE` vs `UPDATE`.

**Comment by jsenko** [comment]
PR #357 should fix the error, but not the possible design issue as @EricWittmann mentioned.
