### ISSUE TITLE
Log level configuration via environment variable in docker container

### ISSUE THREAD

**Issue by gr8routdoors** [Apicurio/apicurio-registry#3585]
### Feature or Problem Description

I'd like to be able to configure log level at startup for the apicurio docker container without having to extend it and override files locally.

### Proposed Solution

The k8s operator has support for the `LOG_LEVEL` and `REGISTRY_LOG_LEVEL` environment variables to set the log levels at startup.  It would be great if the docker container supported these as well.

### Additional Context

Logging can currently be configured by calls to the REST API, [as recommended by the docs](https://access.redhat.com/documentation/en-us/red_hat_build_of_apicurio_registry/2.4/html/installing_and_deploying_apicurio_registry_on_openshift/managing-the-registry#registry-logging_registry).  However, this introduces additional complexity when managing an Apicurio fleet.

**Comment by EricWittmann** [comment]
Actually the docker container supports both of those environment variables.  I just tested the latest released image like this:

`docker run -it --env REGISTRY_LOG_LEVEL=DEBUG -p 8080:8080 apicurio/apicurio-registry-mem:latest-release`

That ran the registry docker image with the registry log level set to `DEBUG` for more fine grained output.  You could also set `LOG_LEVEL` to `DEBUG` but that will probably be overwhelming as it will turn on full debug logging for all of Quarkus.

Another useful logging setting you can enable is `ENABLE_ACCESS_LOG`.  If you set that to `true` then access logging will be enabled.

`docker run -it --env REGISTRY_LOG_LEVEL=DEBUG --env ENABLE_ACCESS_LOG=true -p 8080:8080 apicurio/apicurio-registry-mem:latest-release`

**Comment by EricWittmann** [comment]
I'm going to close this as I think what you're asking for already exists.  But please don't hesitate to re-open!

**Also note**:  the documentation link you sent was about our dynamic logging feature, which has not been popular and is being deprecated.  I would not recommend using it.

**Comment by gr8routdoors** [comment]
Thanks for the response, and my apologies for being slow to see this.  I think what confused me is that although `REGISTRY_LOG_LEVEL` is set to `INFO` at startup, `io.apicurio.registry.storage` log level for KSQLDB storage is still `DEBUG` by default and quite noisy.  Is there an environment variable I'm missing to set its threshold at startup?
