### ISSUE TITLE
Improve metadata

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#361]
Metadata should be generic key-value, so parts of the application such as rules are able to store custom metadata. There should be a clean separation between meta values that users can just see, can see and edit, and private ones.

How should users work with metadata, e.g. could they be used for UI labels feature?

Should there be metadata for artifact versions as well, or could we implement rule configuration as rule metadata?

See also #359

**Comment by EricWittmann** [comment]
Versions definitely need some meta-data, such as when a version was created and by which user.  Also I think user-editable meta-data should be stored with the appropriate version, since it would be very nice to be able to see how that user-editable meta-data changed over time.

**Comment by EricWittmann** [comment]
I think we're going to need to defer this until post-GA.

**Comment by tal181** [comment]
+1

**Comment by ronsher** [comment]
+1

**Comment by EricWittmann** [comment]
Anyone watching this issue should also watch this related one:  https://github.com/Apicurio/apicurio-registry/issues/720

**Comment by EricWittmann** [comment]
We are in the process of adding custom meta-data as a separate "properties" field that will be similar to the existing "labels" field.  Still work to be done but progress has been made.

**Comment by EricWittmann** [comment]
I think this is taken care of by the new user-defined properties capabilities.
