### ISSUE TITLE
[3.0] Improve the modularization

### ISSUE THREAD

**Issue by andreaTP** [Apicurio/apicurio-registry#3618]
### Feature or Problem Description

Registry is currently shipped as a Quarkus application (one for each storage implementation).
Depending on a Quarkus application is not a supported "pattern" and we have [hacks](https://github.com/Apicurio/apicurio-registry/blob/a8d46147671fa2aa42febfed35a4d878d40f12b1/storage/sql/pom.xml#L74-L94) in place to achieve the desired result and overcome the CDI issues.

After opening the door to customize `ArtifactType` and re-using Registry as a library in other Quarkus applications we should provide a more streamlined approach that doesn't involve a deep and precise understanding of the dependency graph.

### Proposed Solution

We should provide all of the needed implementations as libraries(as opposed to applications) that can be imported in a canonical way for all of the storage variants.

**Comment by carlesarnal** [comment]
The specific knowledge required to have Registry included as a library in another application is no longer required, as can be seen here https://github.com/Apicurio/apicurio-registry/blob/main/storage/sql/pom.xml#L79C14-L79C14.
