### ISSUE TITLE
Consider making artifact versions immutable

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#363]
Consider making artifact immutable/append-only, i.e. you can not delete artifact versions, only whole artifact. A replacement would be the artifact state feature implemented using metadata (i.e. a `DELETED` state). This would support the git metaphor and auditing.

See also #359

**Comment by EricWittmann** [comment]
I actually am in favor of this change.  I don't recall why I felt DELETE was an important operation to have for artifact versions.  Perhaps it was just a desire for completeness.  But I think you are right - versions should be immutable.

**Comment by gr8routdoors** [comment]
Hi, sorry for resurrecting an old thread, but it looks like being able to delete a single artifact version will be useful for my use case.  We have a multi-region architecture that consists of multiple registry deployments, and we're looking for transactional behavior across multiple registries when adding a new artifact version.  Not having single version delete stops us from cleanly rolling back in the event adding an artifact fails on one of the registry instances.

Would it be OK to send a PR to bring this back, tucked behind a feature flag?

**Comment by gr8routdoors** [comment]
Awesome, will do.  Thanks!

**Comment by derickmr** [comment]
Hi @carlesarnal, I see that the original code from (this commit)[https://github.com/Apicurio/apicurio-registry/commit/93344fde8e8697feaef19ebc62af4541d3469ec0] was from v1 API. Looks like your repo structure has changed a bit since then and there's now a API v2. Is it ok if we resurrect the code in its original place, i.e. v1 API? Or should we go for a new code on the API v2? Please let me know your thoughts.

**Comment by carlesarnal** [comment]
Hi @derickmr, all the new code should go to the V2 api.

**Comment by derickmr** [comment]
Hi folks, I raised this #3074 issue for us to track adding this functionality back.

**Comment by derickmr** [comment]
Hi @carlesarnal, @EricWittmann, the PR for the above mentioned is open and waiting for a review: https://github.com/Apicurio/apicurio-registry/pull/3075. Please let me know if we need to provide anything else to start the PR review process.

**Comment by EricWittmann** [comment]
@Apicurio/developers Any thoughts on the change to allow deletion of versions?
