### ISSUE TITLE
Support artifact state in CCompat API

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#370]
Should we reflect `ArtifactState` in CCompat API? i.e. if an artifact is in a `DELETED` state, do not return it in REST calls.

See also #359

**Comment by EricWittmann** [comment]
Yeah - it's not so much that we need to "support artifact state" as we need to "project" the artifact/version state into the CCompat API.  Meaning that we won't be exposing the state via the CCompat API, but we need to make sure that e.g. if a version is `DISABLED` that its content can't be accessed via CCompat.

**Comment by EricWittmann** [comment]
I believe this is already done.
