### ISSUE TITLE
Explain the artifact metadata

### ISSUE THREAD

**Issue by tombentley** [Apicurio/apicurio-registry#3703]
I'm reading [the documentation](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-artifact-reference.html#registry-artifact-metadata_registry) about artifact metadata. There's a helpful table with the system-managed (read-only) metadata and another one with the client-managed metadata. However nothing explains what these pieces of metadata _are_. For example there are fully 4 kinds of id, but nothing to help the reader understand how these 4 different identifiers differ. The [REST API docs](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/assets-attachments/registry-rest-api.htm#tag/Metadata/operation/getArtifactMetaData) don't explain either. 

I'm sure these concepts are defined elsewhere in the docs. The point is that the reader shouldn't have to go looking for those definitions. `id` especially is difficult for the reader to understand or related to a concept defined elsewhere: What is it the id _of_?

**Comment by smccarthy-ie** [comment]
Thanks @tombentley, that's very helpful feedback on the user docs. I agree that we should include descriptions for each item of metadata. The doc update is planned for v2.5.

**Comment by smccarthy-ie** [comment]
Fix published in the [v2.5.x user docs on artifact metadata](https://www.apicur.io/registry/docs/apicurio-registry/2.5.x/getting-started/assembly-artifact-reference.html#registry-artifact-metadata_registry).
