### ISSUE TITLE
Option to use stale cache entry over erroring out when schema cache load fails

### ISSUE THREAD

**Issue by gr8routdoors** [Apicurio/apicurio-registry#3807]
### Feature or Problem Description

When running apicurio in a production envioronment, we would prefer to use a stale schema than error out entirely when trying to refresh the schema (i.e. intermittent network errors).

### Proposed Solution

Add a to `ERCache.faultTolerantRefresh` option that instead of erroring out when a load error occurs, will log the exception and return the old value.  Note that this should work alongside retries.  Update `AbstractSchemaResolver` and so it can be configured to use this type of error handling.

This will be configured in `DefaultSchemaResolver` with the following boolean that defaults to `false` to preserve the existing behavior:  `apicurio.registry.fault-tolerant-refresh`

### Additional Context

I considered a design where this information gets propagated to the caller and the caller decides, but that (1) seems to be against the design taken in the `retry` functionality, and (2) would require a contract change to `ERCache` significantly increasing scope.

I'm happy to implement this functionality ASAP.  Just wanted to align on a design @EricWittmann .

**Comment by gr8routdoors** [comment]
I'd like to go a little further with this design and add an option for skipping retries when we already have a cache entry , in order to optimize performance for our production use case.  I'll pile that on as a second commit so that it can be rolled back if there isn't alignment on this functionality.

**Comment by gr8routdoors** [comment]
Nevermind, I just read that [ERCache only retries on RateLimitedClientException](https://github.com/Apicurio/apicurio-registry/blob/main/schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java#L210), so adding `skipRetryOnExistingValue` will be a bit more than a simple change.  I don't want to risk breaking other things that depend on its current behavior so I'll leave that for another PR

**Comment by carlesarnal** [comment]
Assuming the scope of this issue is done on the linked PR.
