### ISSUE TITLE
Mismatch between documentation and code for `apicurio.registry.as-confluent` default value

### ISSUE THREAD

**Issue by kiest** [Apicurio/apicurio-registry#3840]
## Description

**Registry Version**: 2.4.x

Documentation claims that the default value for property `apicurio.registry.as-confluent` is `true`, see _Table 4_ in https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-kafka-client-serdes.html#registry-serdes-config-props_registry

But when looking through the code, the only place where the default value is set for this property is [BaseKafkaSerDeConfig.java](https://github.com/Apicurio/apicurio-registry/blob/4a1dd720ddfe1b1defa51ba6bbfc81b48062ca4a/serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaSerDeConfig.java#L36) and it is set to `false`.

### Expected vs Actual Behaviour

Documented and actual default values should match for `apicurio.registry.as-confluent`.

**Comment by pwright** [comment]
@carlesarnal  should this be cherry picked back to 2.5.x?
https://github.com/Apicurio/apicurio-registry/blob/2.5.x/docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
