### ISSUE TITLE
Reduce footprint of converter distribution

### ISSUE THREAD

**Issue by gunnarmorling** [Apicurio/apicurio-registry#389]
It currently has a size of 16 MB and contains quite a few things which should probably not be in there:

* connect-json-2.4.0.jar should be provided by Kafka Connect, i.e. no need to add this (also makes this usable with different KC versions)
* there is Jersey *and* RESTEasy JARs contained, I think it should be one or the other (RESTEasy preferably)
* geronimo-config-impl-1.2.2.jar: should use JBoss' MP Config implementation
* ProtoBuf: Is this actually supported by the Converter yet, or could this be excluded?
* Jackson: Relevant parts come with KC already, so can be excluded
* Kotlin, Guava: they add 4 MB by alone, perhaps we can get rid of them?

**Comment by alesj** [comment]
@gunnarmorling didn't @jpechane prepare this distro?

**Comment by EricWittmann** [comment]
Paolo took a stab at this here:  https://github.com/Apicurio/apicurio-registry/pull/425

Requires testing but looks reasonable.
