### ISSUE TITLE
Json schema validation issue

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#3891]
## Description

**Registry
Version**: 2.4.4.Final
**Persistence type**: "sql"
I have observed JSONSchema validation for complex object when object is inside an object property is not working as expected.
Validation of objects inside an object are ignored by validation library.

### Steps to Reproduce

PFA small example project i created for issue. Project will register citizen and city schema in apicurio registry.
city is array object in citizen. In the example for data to be validated with register schema, city object is incorrect. Still on validating the data with apicurio SDK, validation is success. Hope this help to reproduce the issue

Run the class SchemaValidation to reproduce from attached project

### Expected vs Actual Behaviour

Expected validation should fail with error zipCode is string and expected to be integer.

[apicurio-issue.zip](https://github.com/Apicurio/apicurio-registry/files/13180476/apicurio-issue.zip)

**Comment by Gourav2912** [comment]
@carlesarnal Could you please update on the issue.

**Comment by carlesarnal** [comment]
Sorry, I've been out for a few days. I'll take a look and let you know my findings.

**Comment by carlesarnal** [comment]
This has been fixed in 2.5.11.Final.
