### ISSUE TITLE
Use more light-weight design for converter client

### ISSUE THREAD

**Issue by gunnarmorling** [Apicurio/apicurio-registry#390]
The converter dist's big footprint seems at least partly be attributeable to the usage of (MP) REST client APIs. We might be able to get rid of many dependencies by using a basic HTTP client for the requests instead. It might be a bit less comfortable to use, but should help to reduce size and productization efforts.

**Comment by EricWittmann** [comment]
@alesj and @jsenko - any opinions on this?  I think we could try generating a client from the OpenAPI rather than generating from JAX-RS.  I haven't tried the OAI generator yet, but it's worth a try.

**Comment by alesj** [comment]
It depends how good is the generator.
Hacking all that REST / HTTP support (async, streaming, ...) support on its own (as per @gunnarmorling ), is just re-inventing the wheel ...
I don't think that a few MBs today means anything ... imho.

**Comment by gunnarmorling** [comment]
Yes, sheer size shouldn't be the main driver. I was thinking more of complexity, security surface (CVEs) and productization efforts. Reducing the dependencies seems like a worthy goal to that end.

**Comment by alesj** [comment]
> Reducing the dependencies seems like a worthy goal to that end.

Well, RestBuilder from microprofile-rest-client should be the norm, and as such free or handled from any CVEs, ...
Me personally have no desire to re-invent this REST builder stuff. :-)
Seen it too many times ... Square's Retrofit, RestEasy, Microprofile REST, etc and a few of my own hacks :-)

**Comment by gunnarmorling** [comment]
> Well, RestBuilder from microprofile-rest-client should be the norm

Ok, but this alone surely cannot pull in Jersey, RESTEasy, Guava, Kotlin etc.?

**Comment by alesj** [comment]
At least with Jersey vs RESTEasy, it should be just one.
Dunno for Guava or Kotlin.
Although Kotlin looks suspicious. :-)

**Comment by carlesarnal** [comment]
This has been solved, closing.
