### ISSUE TITLE
recent dockerhub command  does not work

### ISSUE THREAD

**Issue by davidradl** [Apicurio/apicurio-registry#4031]
## Description

**Registry
I went to [dockerhub](https://www.apicur.io/registry/)
then [https://hub.docker.com/search?q=apicurio%2Fapicurio-registry&type=image](https://hub.docker.com/search?q=apicurio%2Fapicurio-registry&type=image)
I chose the first one (updated 3 days ago)- which I expected to be the new release.
I cut and pasted the command 

`docker pull apicurio/apicurio-registry-mem`
And got 
`Using default tag: latest
Error response from daemon: manifest for apicurio/apicurio-registry-mem:latest not found: manifest unknown: manifest unknown
(base) davidradley@davids-mbp-2 ~ % docker pull apicurio/apicurio-registry-mem
Using default tag: latest
Error response from daemon: manifest for apicurio/apicurio-registry-mem:latest not found: manifest unknown: manifest unknown`

### Steps to Reproduce

See above

### Expected vs Actual Behaviour

I expected it to complete with no error.

I assume the pull command should be have :latest-release or the latest valid version string on it.

### Logs

as above

**Comment by carlesarnal** [comment]
HI @davidradl,

We're aware of this since we're (for now) not publishing the `latest` tag. If you want the same behaviour, `latest-release` must be used instead.

Sorry for the inconvenience!
