### ISSUE TITLE
Apicurio registry Azure AD auth integration fails

### ISSUE THREAD

**Issue by jayanvlaerdal** [Apicurio/apicurio-registry#4044]
## Description

**Registry
Version**:  apicurio/apicurio-registry-sql:2.4.14.Final
**Persistence type**: 

### Environment Dev

What is the environment in which you are running Apicurio Registry? AWS EKS v1.24.17-eks-4f4795d
Apicurio Registry setup info: Using the above mentioned registry version, we are creating a deployment and access the registry endpoint through aws application loadbalancer ingress. The backend is AWS RDS Postgres instance

### Steps to Reproduce

https://www.apicur.io/blog/2023/07/13/registry-azure-ad
Followed the above documentation to setup the single page Azure Active directory authentication. 
Except the below environment variables, we have set all other environment values to the registry container
ROLE_BASED_AUTHZ_ENABLED=true
QUARKUS_OIDC_ROLES_ROLE_CLAIM_PATH=roles

The UI works perfectly but while connecting the registry through API the requests are failing with HTTP/1.1 401 Unauthorized error.

In the container log, we could see only the below error

2023-11-28 05:13:21 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-15) apicurio.audit action="request" result="failure" src_ip="10.67.5.179" x_forwarded_for="117.14.15.40" path="/apis/registry/v2/users/me" response_code="401" method="GET" user=""

What could be the reason? Are we missing any settings?

### Expected vs Actual Behaviour

The API requests should pass

### Logs

2023-11-28 05:13:21 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-15) apicurio.audit action="request" result="failure" src_ip="10.67.5.179" x_forwarded_for="117.14.15.40" path="/apis/registry/v2/users/me" response_code="401" method="GET" user=""

GET /apis/registry/v2/users/me HTTP/1.1
Origin: *
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
User-Agent: PostmanRuntime/7.35.0
Accept: */*
Postman-Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx
Host: xx.xxx.io
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
HTTP/1.1 401 Unauthorized
Date: Tue, 28 Nov 2023 05:52:19 GMT
Content-Length: 0
Connection: keep-alive
access-control-allow-origin: *
access-control-allow-credentials: false
Expires: Mon, 27 Nov 2023 05:52:19 GMT
Pragma: no-cache
Cache-control: no-cache, no-store, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains
www-authenticate: Bearer

**Comment by jayanvlaerdal** [comment]
@carlesarnal - FYA

**Comment by carlesarnal** [comment]
Hi,

It's not a workaround, it's the expected way. I will make it explicit in the blog post.

<img width="677" alt="Screenshot 2023-11-28 at 13 19 48" src="https://github.com/Apicurio/apicurio-registry/assets/12640103/0a5ecfe3-ac51-468e-8539-b61278ada79f">
