### ISSUE TITLE
Trim down the size of our downstream maven repo

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#415]
The Maven repo we are building is quite large.  I suspect that is partly because we are including the application in the maven repo (including all storage variants).  We should consider excluding those artifacts to keep the repo small.

**Comment by paoloantinori** [comment]
This script should be enough to get the minimal list required:

https://gist.github.com/paoloantinori/27f08b7add008ef932425b9002a7f772

**Comment by EricWittmann** [comment]
Resolved by:  https://github.com/Apicurio/apicurio-registry/pull/425
