### ISSUE TITLE
Content extraction not working for SQL storage impl

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#419]
There is a feature called content extraction where we attempt to pull out meta-data from the content of an artifact.  This appears to only be used in the in-memory storage impls.  Seems to be missing from the JPA impl.  This also means we don't have a test for this feature.  So we should add that as well.

**Comment by alesj** [comment]
I can see extractMetaData() in JPARegistryStorage being used.
And I remember I had to fix one of the tests, since now the content did get extracted.

**Comment by EricWittmann** [comment]
Yeah you are right - my mistake.  I did a find-all-references on the extractor and didn't find it in the JPA storage.  Failure on my part I think.  I'll close as not a bug.

**Comment by EricWittmann** [comment]
I also did find the test as well.  :)  I'm currently adding support for content extraction for the various artifact types other than Avro.

**Comment by alesj** [comment]
Do add an explicit test via client, so we don't go directly to extractors, but via storage -- so we test storage's usage of extractor.

**Comment by EricWittmann** [comment]
You already did that. :)

**Comment by alesj** [comment]
I did?
Yeah, just testing you ... ;-)
