### ISSUE TITLE
Allow filtering based on labels and groups

### ISSUE THREAD

**Issue by jirkapipek** [Apicurio/apicurio-registry#4204]
### Feature or Problem Description

The problem is filtering objects by groups or labels. All APIs are always displayed in the UI, for example, you cannot switch to view only groups or labels and then click on the schemas for the appropriate groups or labels.

### Proposed Solution

Enhance the user interface to allow filtering based on labels (tags) and groups. Also the ability to display a list of existing groups and labels. This is probably similar to issue. (https://github.com/Apicurio/apicurio-registry/issues/3562)
Also display list of groups, labels, tags, owners

**Comment by EricWittmann** [comment]
To keep things tidy I'm going to close this issue as Complete, given the improvements I've made to the UI in 3.0.  These improvements include:

1. Separate search for Groups on the Explore page
2. Search for artifacts on the Explore page
3. Search by labels when exploring Groups or Artifacts
4. Search by Group name when exploring Artifacts
5. Group Details page, allowing management of group metadata
6. View Artifacts in Group as a tab on the Group Details page

I haven't done anything in the UI or REST API around label management or listing of owners.  I'm not sure about those features, so I'm closing this issue.

@jirkapipek - could you please open a new GH issue with more details and perhaps use-cases for further enhancements around listing of Labels and Owners?  What are you looking for there?  What use case does it address?  We can tackle those features in one or more additional GH issue.
