### ISSUE TITLE
keycloak authentication flip flops between authentication success and failure every 5 minutes

### ISSUE THREAD

**Issue by msillence** [Apicurio/apicurio-registry#4231]
## Description

**Registry
Version**: 2.5.8.Final
**Persistence type**: kafkasql

### Environment

kubernets v1.27.5-gke.200

Installed as a satefulset with two replicas and sticky session service

### Steps to Reproduce

simply using curl to fetch some information every 10 seconds:

while date | tr '\n' '='; do curl -i -s -u $SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO https://schema-registry.strimzi.svc.cluster.local:8443/apis/ccompat/v6/subjects | head -1; sleep 10; done

### Expected vs Actual Behaviour

authentication should work consistently

actual output (the three dots represent the same result and then the last result before the state change:

Mon Jan 22 13:24:52 UTC 2024=HTTP/2 401
Mon Jan 22 13:25:02 UTC 2024=HTTP/2 200
...
Mon Jan 22 13:29:55 UTC 2024=HTTP/2 200
Mon Jan 22 13:30:06 UTC 2024=HTTP/2 401
...
Mon Jan 22 13:34:59 UTC 2024=HTTP/2 401
Mon Jan 22 13:35:09 UTC 2024=HTTP/2 200
...
Mon Jan 22 13:40:05 UTC 2024=HTTP/2 200
Mon Jan 22 13:40:15 UTC 2024=HTTP/2 401

### Logs

schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:45 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:48 DEBUG <_> [io.apicurio.registry.downloads.DownloadReaper] (executor-thread-36) Running download reaper job at 2024-01-22T13:39:48.002113925Z
schema-registry-1 schema-registry 2024-01-22 13:39:48 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-36) Deleting all expired downloads
schema-registry-1 schema-registry 2024-01-22 13:39:49 DEBUG <> [io.apicurio.registry.config.RegistryStorageConfigCache] (executor-thread-36) Running config property refresh job at 2024-01-22T13:39:49.004252424Z
schema-registry-1 schema-registry 2024-01-22 13:39:49 DEBUG <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-36) Getting all tenant IDs with stale config properties.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:39:55 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.authenticated-read-access.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.auth.owner-only-authorization in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:05 DEBUG <_> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for registry.ccompat.max-subjects in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:16 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:16 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-36) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-36. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:16 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-36) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:40:26 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:26 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:26 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:40:36 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:36 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:36 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:40:46 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:46 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:46 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:40:48 DEBUG <_> [io.apicurio.registry.downloads.DownloadReaper] (executor-thread-40) Running download reaper job at 2024-01-22T13:40:48.005235315Z
schema-registry-1 schema-registry 2024-01-22 13:40:48 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-40) Deleting all expired downloads
schema-registry-1 schema-registry 2024-01-22 13:40:49 DEBUG <> [io.apicurio.registry.config.RegistryStorageConfigCache] (executor-thread-40) Running config property refresh job at 2024-01-22T13:40:49.006803424Z
schema-registry-1 schema-registry 2024-01-22 13:40:49 DEBUG <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-40) Getting all tenant IDs with stale config properties.
schema-registry-1 schema-registry 2024-01-22 13:40:56 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:56 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:40:56 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:05 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:05 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:06 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:06 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:06 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:16 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:16 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:16 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:26 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:26 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:26 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:36 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:36 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:36 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:46 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:46 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:46 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:41:48 DEBUG <_> [io.apicurio.registry.downloads.DownloadReaper] (executor-thread-40) Running download reaper job at 2024-01-22T13:41:48.000972299Z
schema-registry-1 schema-registry 2024-01-22 13:41:48 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-40) Deleting all expired downloads
schema-registry-1 schema-registry 2024-01-22 13:41:49 DEBUG <> [io.apicurio.registry.config.RegistryStorageConfigCache] (executor-thread-40) Running config property refresh job at 2024-01-22T13:41:49.015003494Z
schema-registry-1 schema-registry 2024-01-22 13:41:49 DEBUG <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-40) Getting all tenant IDs with stale config properties.
schema-registry-1 schema-registry 2024-01-22 13:41:57 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:57 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:41:57 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:42:07 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:07 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:07 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:42:17 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:17 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:17 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:42:27 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:27 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:27 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:42:37 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:37 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.
schema-registry-1 schema-registry 2024-01-22 13:42:37 INFO <> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-40) apicurio.audit action="request" result="failure" src_ip="10.48.7.115" path="/apis/ccompat/v6/subjects" response_code="401" method="GET" user=""
schema-registry-1 schema-registry 2024-01-22 13:42:47 DEBUG <> [io.apicurio.common.apps.config.impl.DynamicConfigSource] (executor-thread-40) Could not get dynamic configuration value for app.authn.basic-auth-client-credentials.enabled in thread executor-thread-40. Storage returned null.

**Comment by msillence** [comment]
config converted to key=value

```
KAFKA_BOOTSTRAP_SERVERS=local.bootstrap
REGISTRY_KAFKA_COMMON_SECURITY_PROTOCOL=SASL_SSL
REGISTRY_KAFKA_COMMON_SASL_MECHANISM=PLAIN
REGISTRY_KAFKA_COMMON_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${var.kafka_user}\" password=\"${var.kafka_password}\";

REGISTRY_CCOMPAT_LEGACY_ID_MODE_ENABLED=false
REGISTRY_KAFKASQL_TOPIC=__apicurio_jouirnal
REGISTRY_LOG_LEVEL=DEBUG
CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED=true
ROLE_BASED_AUTHZ_ENABLED=true
REGISTRY_AUTH_ANONYMOUS_READS_ENABLED=false
ENABLE_CCOMPAT_CANONICAL_HASH_MODE=true
REGISTRY_AUTH_OBAC_ENABLED=false
REGISTRY_ALLOW_DYNAMIC_CONFIG=false

JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/cacerts/cacerts
QUARKUS_HTTP_SSL_CERTIFICATE_KEY_STORE_FILE=/registry-certs/schema-registry.keystore.jks
QUARKUS_HTTP_SSL_CERTIFICATE_KEY_STORE_PASSWORD=...
QUARKUS_HTTP_SSL_CERTIFICATE_TRUST_STORE_FILE=/registry-certs/schema-registry.truststore.jks
QUARKUS_HTTP_SSL_CERTIFICATE_TRUST_STORE_PASSWORD=...

KEYCLOAK_URL=local.keycloak_base_url
KEYCLOAK_REALM=local.keycloak_realm
REGISTRY_AUTH_ENABLED=true
REGISTRY_AUTH_RBAC_ENABLED=true
REGISTRY_AUTH_ANONYMOUS_READS_ENABLED=false
KEYCLOAK_API_CLIENT_ID=module.kafka_client.username
KEYCLOAK_UI_CLIENT_ID=module.kafka_client.username
CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED=true
REGISTRY_AUTH_CLIENT_SECRET=module.kafka_client.password
AUTH_CLIENT_SECRET=module.kafka_client.password
```

**Comment by carlesarnal** [comment]
We're aware of the problem and we have created `[this](https://github.com/Apicurio/apicurio-registry/issues/4233)` to improve the situation. For now, the recommended solution is to tweak the value of `CLIENT_CREDENTIALS_BASIC_CACHE_EXPIRATION` to whatever the expiration value in your authentication server (5min in keycloak) minus one minute.

Thanks!

**Comment by EricWittmann** [comment]
This should get fixed using this solution:  https://github.com/Apicurio/apicurio-registry/issues/4233

**Comment by msillence** [comment]
Fantastic, thank you, especially for the quick response

**Comment by msillence** [comment]
Please could you add a note to https://www.apicur.io/registry/docs/apicurio-registry/2.5.x/getting-started/assembly-configuring-the-registry.html#registry-security_registry
as it seems quite likely others will fall for this with the missmatch in defaults
It might also be worth reducing the default cache time to 4  minutes so this is less likely to occur

**Comment by carlesarnal** [comment]
Yes, it was quite likely but this has been addressed using the token expiration time in the last release so the comment is no longer needed.
