### ISSUE TITLE
Improve ccompat read by contentId performance 

### ISSUE THREAD

**Issue by wolfchimneyrock** [Apicurio/apicurio-registry#4243]
## Description

**Registry Version**: 2.5.8
**Persistence type**: sql

While performing scalability tests with high-availability Apicurio Registry connected to distributed PostgreSQL we encountered an interesting bottleneck that effects reading by contentId in the ccompat API.

No matter how high we scaled the number of Apicurio nodes or PostgresSQL nodes, we could not achieve more than 12k read requests per second on this API, whereas we could see upto 36k read requests per second on other read APIs (which I think is a bottleneck with our PostgreSQL architecture)

I noticed in the ccompat API when legacy id mode is false and looks are using the contentId instead of globalId a couple of strange things are happening when calling `GET /apis/ccompat/v7/schemas/<ID>`:

1. the basic content select statement is happening twice
2. there is an 'orphan check' that occurs which incurs an expensive joined select

This orphan check is not made when `GET /apis/registry/v2/ids/contentIds/<ID>` is called - and I don't think it is necessary for the ccompat call either.

At least in the SQL storage layer, the only times that orphans can be generated (delete artifact(s), delete artifact version(s)) there is a call to `deleteAllOrphanedContent()`.

If this is a concern for the kafka or in-memory storage, maybe a new storage call `getAllOrphaned(contentId)` can be added which resolves as no-op on sql but finds orphans in other storage backends.

**Comment by carlesarnal** [comment]
Closing as this was fixed in the linked PR and is fixed on main.
