### ISSUE TITLE
Create shared team credentials for services Apicurio project uses

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#429]
There should be credentials shared with the team for accessing services such as Docker Hub or Maven Central.

Services
- [x] Docker Hub
- [ ] Maven Central
- [x] GitHub
- [ ] Operator Hub
- [x] Email account
- [x] npmjs.com

**Comment by EricWittmann** [comment]
@jsenko can you create shared credentials for operator hub?  I'm not sure if Maven Central credentials can be done.  I'll have to look into that.

**Comment by jsenko** [comment]
Operator Hub works differently, they keep the content in a repository, so you publish new versions by creating a PR. Each contributor must sign a certificate that they have a right to publish a new version [1]. I'm not sure if there are other auth-related prerequisites, but each PR is checked by a human. Example [2].
I could try and use our shared GH account to do a next release, by the sign-off must be done by the person.

[1] https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work
[2] https://github.com/operator-framework/community-operators/pull/2727

**Comment by EricWittmann** [comment]
OK thanks - no worries.  I was just going through old issues and saw this one.  I'm going to close.
