### ISSUE TITLE
http access logging

### ISSUE THREAD

**Issue by msillence** [Apicurio/apicurio-registry#4342]
### Feature or Problem Description

it appears this is based on Quarkus but turning on access logging doesn't seem to yeild annything
`QUARKUS_HTTP_ACCESS_LOG_ENABLED=true`
https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-access-log-enabled

I added this to the JAVA_TOOL_OPTIONS and could see it being picked up

### Proposed Solution

Have the ability to run on access logging to help diagnose issues

In the end I resorted to using mitmproxy to see what was happening

### Additional Context

Running this using the docker image

**Comment by msillence** [comment]
could I add that these two related parameters also look very useful

* quarkus.rest-client.logging.body-limit=1024 
* quarkus.rest-client.logging.scope=request-response

**Comment by carlesarnal** [comment]
I just enabled them on `latest-snapshot` and, when I do operations like artifact creation I can see logs like this one -> 

````
2024-02-28T15:02:57.351125342Z 2024-02-28 15:02:57 INFO [io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver] (executor-thread-34) "apicurio-registry.access method="POST" path="/apis/registry/v2/groups/avro-maven-with-references-auto/artifacts?ifExists=RETURN_OR_UPDATE&canonical=true" response_code="200" response_time="-" remote_ip="_____" remote_user="-" user_agent="Vert.x-WebClient/4.4.6""

````

Do you mind elaborating a bit more on what is not working, what you have tried, which version are you using etc?

Thanks!

**Comment by carlesarnal** [comment]
Closing as stale, if the suggested solution does not work, please, re-open and we can continue the discussion.
