### ISSUE TITLE
ECS Health Check fails on health endpoint not found when deployed docker image

### ISSUE THREAD

**Issue by heman00702** [Apicurio/apicurio-registry#4356]
AWS ECS Health Check fails on health endpoint not found when deployed docker image

just wondering whats the health check for APICURIO

I am trying /apis and /apis/ccompact/v7  both fails

Does APICURIO has an endpoint how to handle this in ECS ?

**Comment by carlesarnal** [comment]
Hello,

No `/apis`. You have your health check just in your host under the /health path. E.g. for localhost, it would be: `http://localhost:8080/health`. There you have access to something like this -> `{
    "status": "UP",
    "checks": [
        {
            "name": "StorageLivenessCheck",
            "status": "UP"
        },
        {
            "name": "PersistenceTimeoutReadinessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "PersistenceExceptionLivenessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "ResponseErrorLivenessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "Database connections health check",
            "status": "UP"
        },
        {
            "name": "ResponseTimeoutReadinessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "PersistenceSimpleReadinessCheck",
            "status": "UP"
        }
    ]
}`
