### ISSUE TITLE
ccompat confluent api endpoint /subjects requires a groupId as header parameter

### ISSUE THREAD

**Issue by ppsodd** [Apicurio/apicurio-registry#4403]
## Description

**Registry
Version**: latest 
**Persistence type**: sql

We try to connect AKHQ to Apicurio to get the registered schemas. For that, we use the provided compatibility REST API for Confluent Schema Registry clients. AKHQ requests first the /subjects endpoint, but instead of getting the subjects it gets an empty list back.

After a first investigation, Apicurio expects a groupId set in the header parameter `X-Registry-GroupId`. With this parameter set, Apicurio responses with the correct subjects. AKHQ does not set this parameter which is why it receives an empty list. A research in the Apicurio code revealed, that the groupId parameter was introduced with this PR: https://github.com/Apicurio/apicurio-registry/pull/3514
but unfortunately it is hard to find any intention why this change was introduced as it does not comply with the confluent api: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#subjects

### Environment

Apicurio is running in a Kubernetes environment where also runs AKHQ

### Steps to Reproduce

Start Apicurio with some schemas and request Apicurio the same way like AKHQ does it:

`curl 'http://apicurio/apis/ccompat/v7/subjects'`

add a valid schema groupId via the header parameter to make it work:

`curl 'http://apicurio/apis/ccompat/v7/subjects' -H 'X-Registry-GroupId: testgroup'`

### Expected vs Actual Behaviour

Expected:

The /subjects endpoint expects only the parameters which are documented in the Confluent-API: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#subjects
to keep the compatibility to it. Hence, it shall respond a list of all registered subjects across all contexts in the Schema Registry if no groupId was provided.

Actual:
A call to the /subjects endpoints without set groupId results in an empty list. Confluent REST clients like AKHQ uses it, does not add a groupId parameter to its request: https://github.com/confluentinc/schema-registry/blob/acf854c6b1e1d1e0ceab63ac6e72a1ce423e2215/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L1113

**Comment by carlesarnal** [comment]
> ## Description
> **Registry Version**: latest **Persistence type**: sql
> 
> We try to connect AKHQ to Apicurio to get the registered schemas. For that, we use the provided compatibility REST API for Confluent Schema Registry clients. AKHQ requests first the /subjects endpoint, but instead of getting the subjects it gets an empty list back.
> 
> After a first investigation, Apicurio expects a groupId set in the header parameter `X-Registry-GroupId`. With this parameter set, Apicurio responses with the correct subjects. AKHQ does not set this parameter which is why it receives an empty list. A research in the Apicurio code revealed, that the groupId parameter was introduced with this PR: #3514 but unfortunately it is hard to find any intention why this change was introduced as it does not comply with the confluent api: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#subjects
> 
> ### Environment
> Apicurio is running in a Kubernetes environment where also runs AKHQ
> 
> ### Steps to Reproduce
> Start Apicurio with some schemas and request Apicurio the same way like AKHQ does it:
> 
> `curl 'http://apicurio/apis/ccompat/v7/subjects'`
> 
> add a valid schema groupId via the header parameter to make it work:
> 
> `curl 'http://apicurio/apis/ccompat/v7/subjects' -H 'X-Registry-GroupId: testgroup'`
> 
> ### Expected vs Actual Behaviour
> Expected:
> 
> The /subjects endpoint expects only the parameters which are documented in the Confluent-API: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#subjects to keep the compatibility to it. Hence, it shall respond a list of all registered subjects across all contexts in the Schema Registry if no groupId was provided.
> 
> Actual: A call to the /subjects endpoints without set groupId results in an empty list. Confluent REST clients like AKHQ uses it, does not add a groupId parameter to its request: https://github.com/confluentinc/schema-registry/blob/acf854c6b1e1d1e0ceab63ac6e72a1ce423e2215/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L1113
> 
> ### Logs

Hello,

The described behaviour is by design. This header was introduced to make groups usable to isolate subjects using the group feature using the ccompat API. If you don't want to use them at all (fair), then you should not create artifacts using a specific group. This endpoint returns *all* the subjects within a provided group. If no group is passed, as with any other endpoint in the compatibility API, the default group is used, defaulting to a "regular" behaviour of the endpoint. The possibility of using the group id was introduced for authorization and data isolation purposes so this endpoint returning *all* subjects across *all* groups would break this principle.

**Comment by ppsodd** [comment]
Thanks for clarification, it makes it better understandable and thus reasonable why the groupId is used here.
