### ISSUE TITLE
Return configuration on /v6/config

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry#4411]
## Description

Version**: 2.5.5
The endpoints /ccompat/v6 and v7 regarding GET /config should behave correctly when using authorization.
Currently when the setting REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED is set to true, one receives a 401 for GET /config which should not be the case.

### Steps to Reproduce

1. Enable AUTH_ENABLED=true and ROLE_BASED_AUTHZ_ENABLED=true
2. Enable REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED=true
3. Call registry with GET /ccompat/v6/config
4. You get 401

### Expected vs Actual Behaviour

Should return something like
```
{
  "compatibilityLevel": "BACKWARD"
}
```

**Comment by carlesarnal** [comment]
Hello,

You're absolutely right, I have raised a PR to correct this situation.
