### ISSUE TITLE
"Upload multiple artifacts" showing in read-only UI

### ISSUE THREAD

**Issue by danielbobbert** [Apicurio/apicurio-registry#4473]
## Description

**Registry
Version**: 2.5.10
**Persistence type**: any

### Steps to Reproduce

If the UI is switched to read-only mode, the "Upload" button is properly hidden. But in the "..." menu, there is still an item for "Upload multiple artifacts"

### Expected Behaviour

It the UI is switched to "read-only", the "Upload multiple artifacts" menu item should be removed from the "..." menu in the main "artifacts" UI page.

**Comment by danielbobbert** [comment]
I believe the problem is in the "import" DropdownItem in toolbar.tsx, where the item is added if "isAdmin=true", no matter what the "readOnly" state is.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/4902
