### ISSUE TITLE
how can i change base image from redhat into debian?

### ISSUE THREAD

**Issue by mingmingshiliyu** [Apicurio/apicurio-registry#4481]
i want to change apicurio image from redhat into debian,is there any practice for me to follow?

**Comment by mingmingshiliyu** [comment]
change the dockerfile base image from redhat into debian,can you help?

**Comment by carlesarnal** [comment]
You'll likely have to rebuild the project from sources and build your own image. You can look at how we're [building](https://github.com/Apicurio/apicurio-registry/blob/main/.github/workflows/verify.yaml#L77-L91) the images in CI.

**Comment by carlesarnal** [comment]
Closing as stale as there is an answer to the question but no response.
