### ISSUE TITLE
mvn clean install causes this problem

### ISSUE THREAD

**Issue by mingmingshiliyu** [Apicurio/apicurio-registry#4482]
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while executing JBang. Exit code: 1
![image](https://github.com/Apicurio/apicurio-registry/assets/143821597/8ecd0e63-863b-4ecc-8b78-cbc480358fd5)

**Comment by carlesarnal** [comment]
You'll likely have more information in the console, upper in the chain. The error above does not have enough information for us to help. Instead of a screenshot, try to attach a log file to the issue.

**Comment by EricWittmann** [comment]
Closing as stale.  @mingmingshiliyu please feel free to re-open while providing the full mvn output/log - we'll be happy to have a look!
