### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by beebeeep** [Apicurio/apicurio-registry#4522]
### Feature or Problem Description

Hi folks.

I've been playing with alternative storages for Apicurio, because replication in PG is not trivial, and automatic failover is even harder, and turns out that at least as of 2.5.10.Final, CRDB can almost be a drop-in replacement for Posgres (more about [interoperability](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility)). The only issue I've faced so far is DB initialization, specifically index creation, e.g. `CREATE INDEX IDX_artifacts_0 ON artifacts USING HASH (type)` - `USING HASH` syntax is not supported in CRDB and hash indexes actually have a bit different semantics ([more on that](https://www.cockroachlabs.com/docs/v23.2/hash-sharded-indexes)). Simply removing `USING HASH` from DDLs just lets apicurio to initialize and start working. I've conducted very basic smoke tests (mostly using Confluent Schema Registry API, honestly), and seems like basic CRUD operations are working just fine. 

So, my question to community and contributors - how do you think, is it worth declaring support of CRDB for Apicurio, given that *likely* there isn't much efforts required to do that? 

### Proposed Solution
If the answer to question above is yes, then I can take care of submitting a PR with required changes (I guess the very bare minimum would be the integration tests and updated DDLs that should work both for PG and CRDB; alternatively, CRDB can be registered as a separate storage just by copying pieces of PG-related code).

**Comment by sjuls** [comment]
I think this would be a great enhancement. Since CockroachDB is a widely adopted HA distributed database, adding support would open the door for many companies to adopt apicurio-registry.

I would suggest separating postgres and cockroach implementations since Cockroach Labs does not provide guarantees that the DDL/DML will maintain compatibility with postgres (evidenced by the issue you currently face).

**Comment by beebeeep** [comment]
Thank you, Carles! 
I will try to prepare a PR once I'll have a chance. Closing this issue for now.
