### ISSUE TITLE
Add createdOn metadata for each version of an artifact

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#453]
Right now, we are not storing values for the `createdOn` metadata for each version of an artifact. We need to implement this for all the storages and then be able to retrieve that information for example in the `searchVersions` operation.

Also, in the JPA storage, we are not storing a `createdOn` metadata value for the artifacts.

**Comment by carlesarnal** [comment]
Partially addressed by [514](https://github.com/Apicurio/apicurio-registry/pull/514/files)
