### ISSUE TITLE
APICURIO API hardcodes 'artifacts' part in schema registry url

### ISSUE THREAD

**Issue by canadiansky** [Apicurio/apicurio-registry#4534]
## Description

**Registry
APICURIO API  Version**:  1.3.3.Final

### Environment

APICURIO API 1.3.3.Final
Confluent.SchemaRegistry Nuget package 2.3.0

### Steps to Reproduce

to use in Producer/Consumer schema validation: 
```
new CachedSchemaRegistryClient(new Dictionary<string, string>
{
    { "schema.registry.url", options.Server! },
    { "schema.registry.basic.auth.credentials.source", "SASL_INHERIT" },
    { "sasl.username", options.Username! },
    { "sasl.password", options.Password! }
});
```
 from Confluent.SchemaRegistry package

Steps to reproduce it:

temporary allows to use anonymous in ether web browser or postman:

1. Go to 'http://_schema.registry.url_/apis/registry/v2/groups/_your-group_/**artifacts** it works and responses with JSON
2. Go to 'http://_schema.registry.url_/apis/registry/v2/groups/_your-group_/**schemas** it DOES NOT work and responses with 404

The issue is 
 - APICURIO API hardcodes '/**artifacts**/' as a part of schema registry URL
 - Confluent.SchemaRegistry package hardcodes '/**schemas**/' as a part of schema registry URL

we have incompatible usages APICURIO API+Confluent.SchemaRegistry

### Expected vs Actual Behaviour

to have the same URL compatible with APICURIO API and Confluent.SchemaRegistry package

**Comment by carlesarnal** [comment]
Hello @canadiansky, let me clarify thing a bit.

Apicurio Registry exposes multiple APIs, as you correctly discovered, but:

1. The main one, the core API, can be found, as you stated, under `http://schema.registry.url/apis/registry/v2`, so here you can discover any of the operations of this APIs, that you can find defined `[here](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json)`. 

2. Now, the CCompat API, can be found [here](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/ccompat/v7/openapi.json). The base path for this API is `http://schema.registry.url/apis/ccompat/v7`. 

If you have tools that are using the Apicurio Registry V2 core API, you must point them to the path in 1. If you have tools that are using the CCompat API, you must point them to the path described in option 2.

Essentially, what you get is a runtime server that has compatibility for **both** APIs, but under **different** paths.

**Comment by canadiansky** [comment]
I discovered that ccompat api resolved it, but loosing groups in url path
