### ISSUE TITLE
Introduce API versioning

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#456]
We should version our APIs to protect against breaking changes. There are several approaches to be discussed.

**Comment by EricWittmann** [comment]
I think I would prefer to defer this until we actually have breaking API changes.  We should feel free to continue evolving the API as long as we don't make any breaking changes.  This obviously includes adding new operations and adding optional properties to existing data types.

**Comment by EricWittmann** [comment]
As a result, I'm keeping this on the backlog.

**Comment by famartinrh** [comment]
we can close this
