### ISSUE TITLE
Add IDs to UI html elements for testing purposes

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#457]
The idea is to have id's in all html elements that are clickable or will contain usefull information to allow testing the web UI. 
Think of the clicks a user have to make to upload an artifact and add id's to those elements, think of the clicks needed to sort items in lists or to find in lists ... 
About the items in list or grids AFAIK they cannot have id's because they are automatically generated, so don't worry about those, there are workarounds for those situations that can be made in tests.

**Comment by EricWittmann** [comment]
We'll use `data-testid` as the attribute here as described in:  https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change
