### ISSUE TITLE
2.5.11 release notes not accurate

### ISSUE THREAD

**Issue by pegtrifork** [Apicurio/apicurio-registry#4654]
## Description

In the 2.5.11 [release notes](https://github.com/Apicurio/apicurio-registry/releases/tag/2.5.11.Final) it listsa fix for [4411](https://github.com/Apicurio/apicurio-registry/issues/4411) as beeing part of that release.
It does however seem like the fix was only commited to main and not the release branch.
We are affected by the bug described in 4411, and would like a new patch release where the bugfix is included. Alternatively the release notes should be updated to reflect that this bugfix is not part of the release.

**Comment by carlesarnal** [comment]
@pegtrifork you're right, this has been fixed on main and has not been backported. It was caught in the release notes since they're automatically generated based on closed issues, I'll fix them.

**Comment by carlesarnal** [comment]
It will be included in the 2.6.0 release most likely.
