### ISSUE TITLE
Test Update Artifact v2 requires write permissions

### ISSUE THREAD

**Issue by ikstewa** [Apicurio/apicurio-registry#4704]
## Description

**Registry Version**: 2.5.11
**Persistence type**: in-memory

The `testUpdateArtifact` operation in the v2 API now requires write permissions. In v1 the API only requires read permissions.

v1: https://github.com/Apicurio/apicurio-registry/blob/2.5.11.Final/app/src/main/java/io/apicurio/registry/rest/v1/ArtifactsResourceImpl.java#L201
v2: https://github.com/Apicurio/apicurio-registry/blob/2.5.11.Final/app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java#L541

Was this an intended change?
If so, is there any way to reduce the required permissions so anonymous read-only access can test schema changes?

### Environment
local docker run

### Steps to Reproduce

1. Enable anonymous read access
2. Attempt to test a schema update

### Expected vs Actual Behaviour

Expected read-only access could test schema changes.

**Comment by EricWittmann** [comment]
I don't recall making a decision to change this from `read` to `write`, which means either

1. this was a mistake and should be fixed

or

2. I'm getting old and have forgotten

@Apicurio/developers thoughts on this?

**Comment by EricWittmann** [comment]
One interesting update to this is that for v3 we are replacing this operation with a new `dryRun` query parameter that can be used when creating artifacts and when creating versions.  I think this is a nice semantic improvement, but it does mean that this issue will continue to exist in v3, since both those operations require `write` permission.

I would argue that semantically that makes sense.

But we **could** probably put something in that would change the permission to `read` if the `dryRun` query param exists and is `true`.

**Comment by ikstewa** [comment]
That would be ideal if we could keep v2/v3 as read-only support for dry run updates. We're running into this as we're migrating our current workflow from the confluent compatibility APIs to the native apicurio apis.

Our workflow enables a user during local development to modify the schema and validate their changes are backwards compatible. This allows us to keep user permissions as read-only and only provide update/write permissions in the deployment workflows.

Write permissions for schema validation would require users to push their changes in order to confirm the compatibility.

**Comment by EricWittmann** [comment]
This is being fixed in https://github.com/Apicurio/apicurio-registry/pull/4800

It didn't make the cutoff for 3.0.0.M3 but will be in M4.

**Comment by EricWittmann** [comment]
Fixed:

* https://github.com/Apicurio/apicurio-registry/pull/4800
