### ISSUE TITLE
Expose listening port as a param for the Docker images

### ISSUE THREAD

**Issue by paoloantinori** [Apicurio/apicurio-registry#473]

**Comment by EricWittmann** [comment]
Curious to know what the benefit of this is for the docker image?  Not sure why it matters what port the app is running on when running inside docker...

**Comment by paoloantinori** [comment]
I was running the image on my host with `--net host` so that the container doesn't get its on `veth` but is addressable via the host name/ip.

In doing so I was looking for a way to specify the port I wanted, not being able to solve the problem with port-forwarding

**Comment by EricWittmann** [comment]
OK that's a reasonable use-case. :)
