### ISSUE TITLE
Connection to registry is "dying" after running bunch of tests

### ISSUE THREAD

**Issue by im-konge** [Apicurio/apicurio-registry#475]
When I tried to fix IT tests I get really strange error.

The problem here is when you do some actions (like in tests) - creating, deleting and updating schemas/artifacts/subjects - the connection to API somehow dies. So the other tests will fail and return exception:

```
o.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]; error code: 50005
```
The error is correct - you can get HTML response with something like this:
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
When you try it with cURL, you will get the same error. The strange thing is, that ServiceRegistry pod is up and running, deployment is ready, service too and response from `/health/live` is:

```
{
    "status": "UP",
    "checks": [
        {
            "name": "PersistenceTimeoutReadinessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "ResponseErrorLivenessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        },
        {
            "name": "StorageLivenessCheck",
            "status": "UP"
        },
        {
            "name": "PersistenceExceptionLivenessCheck",
            "status": "UP",
            "data": {
                "errorCount": 0
            }
        }
    ]
}
```
It's like the connection to API will somehow close.

How to reproduce it:
 - Openshift
 - Strimzi operator and Kafka, ZK and EO deployed
 - deployed ServiceRegistry with Streams storage
 - connect it to Strimzi operator
 - do some work or run IT tests (all, if it will run without exception, run again)

--> I think this will be problem with any storage, not only with AMQ Streams

YAMLs: https://gist.github.com/im-konge/4f0fd3e46f323d5d1d2fe2ba9e9a6aa5
Logs: https://gist.github.com/im-konge/a78bb0d1a8352ed9b8b15217a0e48b22

**Comment by im-konge** [comment]
This is always hit when you want to create like 50 schemas (you can use for loop for this)

**Comment by EricWittmann** [comment]
Hey @alesj can you provide a brief explanation of the fix for this and then close it?

**Comment by alesj** [comment]
When RegistryStorage method returns CompletionStage this can be completed in Kafka consumer thread (as in the case of Kafka or Streams storage).
So any continuation on that CS will happen in that thread -- if that continuation again calls RegistryStorage method, this can then block indefinitely -- since first invocation did't yet finish.
Make sure things are properly async -- see RegistryFacade change/fix.
