### ISSUE TITLE
Updating artifact with type AVRO always fails

### ISSUE THREAD

**Issue by im-konge** [Apicurio/apicurio-registry#476]
++++ USING AMQ STREAMS STORAGE ++++

When we create new artifact with `artifactType=AVRO` and then update it, update always fails. I double check it if I'm doing everything right, but the tests that includes updating of schema are failing too.

Created artifact:
```
{"type":"record","name":"record-name","fields":[{"name":"key1","type":"string"}]}
```

cURL command:
```
curl -X PUT -H "Content-type: application/json; artifactType=AVRO" --data '{"type":"record","name":"record-name","fields":[{"name":"key1","type":"string"},{"name":"key2","type":"string"}]}'  http://some-url.com/artifacts/example-artifact
```

Error message:
```
{"message":"Incompatible artifact: example-artifact [AVRO]","error_code":400}
```

How to reproduce:
- create some artifact, artifactType = AVRO, with some schema
- try to update it - add new another field to `fields:`, again with artifactType = AVRO

--> This will be problem in every storage - JPA, Infinispan, AMQ Streams ..

**Comment by famartinrh** [comment]
also fails if tryied from the UI

**Comment by alesj** [comment]
What about if you run this locally -- and leave it running longer period (not just for the tests, etc)?

**Comment by im-konge** [comment]
What do you mean `run this locally`? I mean -> I'm testing this against openshift cluster. All rules (which can block this editing too from my POV) are cleaned up too, the time doesn't matter here.

I tried it few times, in like 30 mins.

**Comment by alesj** [comment]
Can you create a test for this, for a single-instance local run, that would fail as well?

**Comment by im-konge** [comment]
I'll take a look at it tomorrow, maybe there was some rule that I didn't removed and that's why tests (and manual updating) were failing. I'll let you know @alesj. Thanks.

**Comment by EricWittmann** [comment]
@im-konge @alesj Is there an update on this?

**Comment by im-konge** [comment]
I think this is already fixed.

**Comment by im-konge** [comment]
So if @alesj doesn't have anything about it, it's done from my POV
