### ISSUE TITLE
Search Artifacts - sorting should be by name (not working)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#485]
When searching for artifacts, the sorting should be done over the Name meta-data field.  I think we're sorting by Artifact ID right now.

Note that some artifacts might not have a Name.  So the primary sort field should be Name and the secondary sort field should be ID.

**Comment by carlesarnal** [comment]
You’re right, right now, we are sorting by ID. I’ll improve the ordering part.

**Comment by carlesarnal** [comment]
The PR #498 solves this for the jpa storage.
