### ISSUE TITLE
CORS error when logging with Microsoft

### ISSUE THREAD

**Issue by krystofrezac** [Apicurio/apicurio-registry#4853]
## Description

**Registry
Version**: 2.6.0.Final
**Persistence type**: sql

When logging with Microsoft I get this error and get stuck on white screen.
<img width="992" alt="Screenshot 2024-07-04 at 14 01 48" src="https://github.com/Apicurio/apicurio-registry/assets/39591095/cf9b7d44-336b-40ec-a5d1-3a1d09f1b436">

I am able to log in with this plugin enabled: https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino

### Environment

config env variables:
```
REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: "true"
REGISTRY_AUTH_ENABLED: "true"
REGISTRY_UI_AUTH_TYPE: oidc
KEYCLOAK_API_CLIENT_ID: xxx
REGISTRY_OIDC_UI_CLIENT_ID: xxx
REGISTRY_AUTH_URL_CONFIGURED: https://login.microsoftonline.com/xxx
REGISTRY_OIDC_UI_REDIRECT_URL: xxx
ROLE_BASED_AUTHZ_ENABLED: "true"
QUARKUS_OIDC_ROLES_ROLE_CLAIM_PATH: roles
CORS_ALLOWED_ORIGINS: "*"
```

### Steps to Reproduce

1. Go to the ui 
2. Login with Microsoft
3. Check the console

### Expected vs Actual Behaviour

The expected behaviour is to login without any problem.

### Possible fix

It works with this patch applied on tag `2.6.0.Final` . But I am not sure if it will break some other functionality

```diff
diff --git a/ui/src/services/auth/auth.service.ts b/ui/src/services/auth/auth.service.ts
index 3446461dc..96da207cd 100644
--- a/ui/src/services/auth/auth.service.ts
+++ b/ui/src/services/auth/auth.service.ts
@@ -128,7 +128,7 @@ export class AuthService implements Service {
             response_type: "code",
             scope: "openid profile email",
             filterProtocolClaims: true,
-            loadUserInfo: true
+            // loadUserInfo: true
         };
     }
```

**Comment by carlesarnal** [comment]
In this context the request is being blocked by ENTRA ID, not by Registry, if you follow the [blog](https://www.apicur.io/blog/2023/07/13/registry-azure-ad) we have you must be able to log in without any problems.

**Comment by krystofrezac** [comment]
Yeah, you're right. It was misconfigured. I missed the `v2.0` at the end of `REGISTRY_AUTH_URL_CONFIGURED`
