### ISSUE TITLE
UI functionality against Kafka/Streams back-ends

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#488]
Hey @alesj do I need to update the UI to handle the fact that some creates/updates/deletes when using Kafka as the back-end are async?  For example, in the UI when you create an artifact, the UI redirects to the "Artifact Details" page for that artifact.  Do we need to handle the case where that artifact is not actually available via the API right away?  If so, what strategy do you recommend?  I could introduce a standard delay, or we can poll the back-end until the content is available.

**Comment by alesj** [comment]
You get back metadata. Is that not enough?

**Comment by EricWittmann** [comment]
The meta-data is enough to create the redirect in the UI to the details page.  But the details page loads the content and rules as well.  It also loads the list of versions.  If any of that is unavailable right away (after a create) then the UI page may fail to load, or it may be incomplete.

**Comment by alesj** [comment]
I would design this around the notion of knowing that things can be async -- and no one need that info immediately.

**Comment by EricWittmann** [comment]
OK
