### ISSUE TITLE
v2 /groups list API crashes with SQL error

### ISSUE THREAD

**Issue by wolfchimneyrock** [Apicurio/apicurio-registry#4933]
## Description

**Registry
Version**: 3.0.0.M3
**Persistence type**: sql / postgres

### Environment

RHEL8

### Steps to Reproduce

curl http://localhost:8080/apis/registry/v2/groups

### Expected vs Actual Behaviour

should return list of groups, instead it returns status 500 with payload:
```
{"message":"org.postgresql.util.PSQLException: ERROR: syntax error at or near \"asc\"\n  Position: 39","error_code":500,"detail":"PSQLException: ERROR: syntax error at or near \"asc\"\n  Position: 39","name":"RuntimeSqlException"}
```

### Logs

postgres logs:
```
ERROR:  syntax error at or near "asc" at character 39
STATEMENT:  SELECT * FROM groups g  WHERE (1 = 1) asc LIMIT $1 OFFSET $2
```

**Comment by EricWittmann** [comment]
This has apparently been fixed somewhere along the way from 3.0.0.M3 to the official 3.0.0 release.  I've tested manually and added a new unit test in this PR:

* https://github.com/Apicurio/apicurio-registry/pull/5480

Closing as fixed.  :)
