### ISSUE TITLE
Close the result set once we're done with it.

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-registry#4947]
According to the documentation, when a Statement is closed the underlying ResultSet (if there's one) is also closed. According to the conversation [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JDBC.3A.20how.20to.20debug.20leaked.20result.20sets) this is not true, and although we're protected from an actual resource leak by Agroal, a warning is still printed. We can close the result set so no warning is raised and release the resources as soon as possible.

**Comment by pwright** [comment]
see https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JDBC.3A.20how.20to.20debug.20leaked.20result.20sets for discussion about this log msg
