### ISSUE TITLE
Superfluous files in connector distribution

### ISSUE THREAD

**Issue by jpechane** [Apicurio/apicurio-registry#497]
Files that are part of converter distribution

* connect-json
* jackson-*

are included in Kafka Connect libs too.

**Comment by EricWittmann** [comment]
@jpechane would you be able to check the current `master` connector distribution's list of dependencies and provide some feedback and perhaps give it a try?  We've made significant changes to the serdes/client layer (with a new client) so the connector distro should be much slimmer now.  But I don't want to close this out until someone who knows what they're doing can check.  If we still have JARs to trim out, let's document that here.

**Comment by jpechane** [comment]
@EricWittmann Hi, sorry for the delay. I tested it with 1.3.0.Final and it is much much better. I just propose to eliminate (I tried to remove it and it works)
 - connect-json-*.jar
 - jackson-*.jar
 -jboss-jaxrs-*.jar

**Comment by EricWittmann** [comment]
Which of these JARs above are already part of Kafka vs. things we simply don't need?

**Comment by EricWittmann** [comment]
I'm guessing we actually need all of these but they already exist in Kafka?

**Comment by jpechane** [comment]
All of them are present in akfa/libs dir. Just a different verison in case of Jackson
