### ISSUE TITLE
apicurioregistrysdk

### ISSUE THREAD

**Issue by pwright** [Apicurio/apicurio-registry#5058]
## Description

**Registry
Version**: 2.6
**Persistence type**: in mem

### Environment

local podman 

### Steps to Reproduce

Run https://github.com/Apicurio/apicurio-registry/blob/main/python-sdk/tests/basic_test.py

### Expected vs Actual Behaviour

I wanted to write a script to automate some work on registry, and  I choose to use https://pypi.org/project/apicurioregistrysdk/2.6.2/

however it look like some dependencies changed name?
https://learn.microsoft.com/en-us/openapi/kiota/quickstarts/python

and the old versions are no longer available?

```
apicurioregistrysdk 2.6.2 requires microsoft-kiota-abstractions<0.7.0,>=0.6.0, but you have microsoft-kiota-abstractions 1.3.3 which is incompatible.
```

I may be totally misinterpretting this stuff, but couldn't find any docs about how to use the the python SDK, maybe that's the bug?

**Comment by EricWittmann** [comment]
How did you run that Python test from main but using the 2.6.2 SDK?

You definitely will not be able to use the 2.6.2 SDK along with the code on the main branch. The main branch is all new 3.0 work. So there will likely be lots of conflicts and problems.

**Comment by pwright** [comment]
>How did you run that Python test from main but using the 2.6.2 SDK?

Was trying to use the sdk with 2.6 and wasn't getting anywhere, scrambled for a working example and didn't notice i was running 'main'.. doh!
