### ISSUE TITLE
3.0.0.M4 not published to maven central

### ISSUE THREAD

**Issue by wolfchimneyrock** [Apicurio/apicurio-registry#5063]
Can you publish the newest v3 milestone to maven central?

**Comment by EricWittmann** [comment]
Ouch didn't see this.  Our workflow succeeded but didn't actually publish the artifacts to central!  I'm looking into it.

**Comment by EricWittmann** [comment]
Done.  Thanks for opening the issue.

https://central.sonatype.com/artifact/io.apicurio/apicurio-registry/3.0.0.M4

**Comment by wolfchimneyrock** [comment]
Thanks! Do you have a timeline for releasing 3.0.0.M5 ? I am very eager to test out #4974,  #4953, #5128
