### ISSUE TITLE
Change default SerDes config options to be compatible with Confluent clients out of the box

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#5086]

**Comment by k-wall** [comment]
Just a curiosity, this change has a 3.0.0 milestone but was released as part of 2.6.4.Final.  Was that the intent?  Given the breaking nature of this change I'd have thought including it on the major would have been appropiate.

**Comment by k-wall** [comment]
I spoke with @EricWittmann in another channel, we confirmed that this change isn't part of 2.6.4.
