### ISSUE TITLE
Confluent compatibility api - delete subject requires content-type header

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#509]
Delete subject API in confluent compatibility API requires content-type header to be set in order to work properly
This fails
```
$ curl -i -X DELETE localhost:8080/api/ccompat/subjects/ee613144-5339-455b-9996-d56852470de00
HTTP/1.1 415 Unsupported Media Type
Date: Wed, 20 May 2020 17:44:43 GMT
Expires: Tue, 19 May 2020 17:44:43 GMT
Pragma: no-cache
Cache-control: no-cache, no-store, must-revalidate
Content-Type: application/json
Content-Length: 7288

{"message":"RESTEASY003200: Could not find message body reader for type: interface javax.ws.rs.core.HttpHeaders of content type: */*","error_code":415,"detail":"javax.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: interface javax.ws.rs.core.HttpHeaders of content type: */*\n\tat org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.throwReaderNotFound(ServerReaderInterceptorContext.java:55)...
```
And this works
```
$ curl -i -X DELETE localhost:8080/api/ccompat/subjects/ee613144-5339-455b-9996-d56852470de00 -H "Content-Type: application/json"
HTTP/1.1 404 Not Found
Date: Wed, 20 May 2020 17:46:50 GMT
Expires: Tue, 19 May 2020 17:46:50 GMT
Pragma: no-cache
Cache-control: no-cache, no-store, must-revalidate
Content-Type: application/json
Content-Length: 13917
```
And as per confluent [documentation](https://docs.confluent.io/5.4.1/schema-registry/develop/api.html#delete--subjects-(string-%20subject)) this should work
```
$ curl -i -X DELETE localhost:8080/api/ccompat/subjects/ee613144-5339-455b-9996-d56852470de00 -H "Accept: application/vnd.schemaregistry.v1+json"
HTTP/1.1 415 Unsupported Media Type
Date: Wed, 20 May 2020 17:48:00 GMT
Expires: Tue, 19 May 2020 17:48:00 GMT
Pragma: no-cache
Cache-control: no-cache, no-store, must-revalidate
Content-Type: application/json
Content-Length: 7288

{"message":"RESTEASY003200: Could not find message body reader for type: interfa...
```

**Comment by carlesarnal** [comment]
@famartinrh, If I execute the following everything works as expected, are we sure that the confluent API works as you describe?
The `Accept` header tells the server which contents the caller can accept, and the `Content-Type` tells the server which kind of content you are sending.

`$ curl -i -X DELETE localhost:8080/api/ccompat/subjects/ee613144-5339-455b-9996-d56852470de00 -H "Content-Type: application/vnd.schemaregistry.v1+json"
HTTP/1.1 404 Not Found
Date: Wed, 03 Jun 2020 11:02:20 GMT
Expires: Tue, 02 Jun 2020 11:02:20 GMT
Pragma: no-cache
Cache-control: no-cache, no-store, must-revalidate
Content-Type: application/json
Content-Length: 101`

**Comment by EricWittmann** [comment]
I think the question is whether `DELETE` with the `Accept` header and **not** the `Content-Type` header works or fails.  It seems like this particular `DELETE` call (because it returns a list of the versions it deleted) should require the `Accept` header (to tell the server what it expects to get back) but not require the `Content-Type` header (because the client isn't going to send any payload).

**Comment by famartinrh** [comment]
Regarding how the confluent API works I can't tell being 100% because I just took a look at their docs and the example they provide, docs may not be accurate

**Comment by carlesarnal** [comment]
Problem found, have a look at the linked pull request for more information.
