### ISSUE TITLE
`org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex` fails on Java 21

### ISSUE THREAD

**Issue by IncandescentChrysalis** [Apicurio/apicurio-registry#5093]
# Description

**Registry
Version**: `2.6.2.Final`

The `org.jboss.jandex:jandex-maven-plugin` `v1.2.3` module defined in the latest `2.*` version (`2.6.2.Final`) fails to build on Java 21.

This is the same problem [as discovered in the `apache/hop` project](https://github.com/apache/hop/issues/3637), solved by updating the dependency to `io.smallrye:jandex-maven-plugin` `v3.1.8` ([`3.2.0+` changes the index version, causing problems with quarkus](https://github.com/quarkusio/quarkus/issues/40739#issuecomment-2122639055)).

This update has already been made on `main` (#4656), hence this would merely be a backport of that update to the `2.*` versions.
I see #5079 did not mention this plugin. I am also noticing this robot auto-update is only done on `2.5.x`, not `2.6.x`

# Logs
```
#0 383.3 [ERROR] Failed to execute goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex (make-index) on project apicurio-registry-utils-tools: Execution make-index of goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex failed: Cannot read the array length because "bytes" is null -> [Help 1]
#0 383.3 [ERROR] Failed to execute goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex (make-index) on project apicurio-registry-utils-kafka: Execution make-index of goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex failed: Cannot read the array length because "bytes" is null -> [Help 1]
#0 383.3 [ERROR] Failed to execute goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex (make-index) on project apicurio-registry-common: Execution make-index of goal org.jboss.jandex:jandex-maven-plugin:1.2.3:jandex failed: Cannot read the array length because "bytes" is null -> [Help 1]
```

**Comment by EricWittmann** [comment]
Yes thank you! This can be closed because it is now fixed on main and on 2.6.x.
