### ISSUE TITLE
apicurio-registry-java-sdk published classes require JDK17

### ISSUE THREAD

**Issue by wolfchimneyrock** [Apicurio/apicurio-registry#5127]
## Description

**Registry
Version**: 3.0.0.M3
**Persistence type**: postgresql

We have a lot of users of Flink, and [the current stable version of Flink considers JDK17 experimental](https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/deployment/java_compatibility/) which means most of our users run this on JDK11.

While attempting to build a client wrapper library for these users, I notice that the artifacts published to maven central for 3.0.0.M3 only work with JDK17+

While this is the first such error we see (from the Kiota generated classes in `apicurio-registry-java-sdk`), our wrapper library will also depend on `apicurio-registry-schema-resolver` and `apicurio-registry-serdes-*` so at least those too should be compatible with JDK11.

Our build pipeline cannot invoke Kiota, so we rely on the maven central published artifacts for these libraries.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project client: Compilation failure: Compilation failure:
[ERROR] /<REDACTED>/schemaregistry/FlinkRegistryClient.java:[3,40] cannot access io.apicurio.registry.rest.client.RegistryClient
[ERROR]   bad class file: /<REDACTED>/maven-m2/io/apicurio/apicurio-registry-java-sdk/3.0.0.M3/apicurio-registry-java-sdk-3.0.0.M3.jar(/io/apicurio/registry/rest/client/RegistryClient.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /<REDACTED>/schemaregistry/FlinkRegistryClient.java:[28,19] cannot find symbol
```

please publish artifacts that work with JDK11 since a large number of potential users are still using that runtime.

### Environment

any environment with openjdk11 runtime

**Comment by andreaTP** [comment]
Hi :wave: and thanks for reaching out!
On current `main` the Java version is configured at the project level: https://github.com/Apicurio/apicurio-registry/blob/70d74cafbb2a4bd33ef25464b28c44e064235b2e/pom.xml#L127-L128

Let me know if the fix I provided solves your problems.

**Comment by wolfchimneyrock** [comment]
> Hi 👋 and thanks for reaching out! On current `main` the Java version is configured at the project level:
> 
> https://github.com/Apicurio/apicurio-registry/blob/70d74cafbb2a4bd33ef25464b28c44e064235b2e/pom.xml#L127-L128
> 
> Let me know if the fix I provided solves your problems.

I think since JDK9 the [safer, better way](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html) is to use

```
    <maven.compiler.release>11</maven.compiler.release>
```
 
 instead of the source + target options, since using release it makes sure the code actually conforms to the specified API.

**Comment by EricWittmann** [comment]
Seems I may have jumped the gun on the merge.  @andreaTP feel free to switch to using `maven.compiler.release` as you prefer.  :)
