### ISSUE TITLE
Failed to start apicurio-registry-ui:3.0.0.M4

### ISSUE THREAD

**Issue by marcantoine-bibeau** [Apicurio/apicurio-registry#5170]
## Description

I getting the following error when trying to start the UI
```

---------------------------------------------
Performing the Initial Config...
---------------------------------------------
Generating application config at: /opt/app-root/src/config.js
/usr/local/bin/create-config.cjs:72
        CONFIG.auth.options.clientId = AUTH_CLIENT_ID_URL;
                                       ^

ReferenceError: AUTH_CLIENT_ID_URL is not defined
```

It seems to have been fixed [here](https://github.com/Apicurio/apicurio-registry/commit/e0b47f82ea92ff4be8c3fc5b0565681d6b66c4a1) but seems the fix is not part of `quay.io/apicurio/apicurio-registry-ui:3.0.0.M4` build

### Environment

I'm running on Kubernetes using docker image: quay.io/apicurio/apicurio-registry-ui:3.0.0.M4

### Steps to Reproduce

Set ENV VAR: REGISTRY_AUTH_TYPE: "oidc"

### Expected vs Actual Behaviour

Should start

### Logs

```
---------------------------------------------
Performing the Initial Config...
---------------------------------------------
Generating application config at: /opt/app-root/src/config.js
/usr/local/bin/create-config.cjs:72
        CONFIG.auth.options.clientId = AUTH_CLIENT_ID_URL;
                                       ^

ReferenceError: AUTH_CLIENT_ID_URL is not defined
```

**Comment by marcantoine-bibeau** [comment]
Just tried "latest-snapshot" SHA: 8ead1ceaf5cb and it is working :) If you can please republish M4 or create a M5 release I would appreciate. Thanks a bunch for all the good work!

**Comment by EricWittmann** [comment]
Thanks for the report!  Sorry for the inconvenience - I'll see about getting an M5 release done tomorrow.  I have a couple of PRs I'd like to include anyway.

**Comment by EricWittmann** [comment]
We'll do an M5 release very soon.  Just trying to make sure we get as many PRs in as possible.

**Comment by EricWittmann** [comment]
Fixed in M5, which was released today.
