### ISSUE TITLE
List artifact types duplicated

### ISSUE THREAD

**Issue by cesareomacias** [Apicurio/apicurio-registry#5216]
## Description

**Registry
Version**: 2.6.3.Final
**Persistence type**: sql

### Environment

Hi, 

I have deployed Apicurio Registry in an EC2 Instance. I was using the API and I've realized that the endpoint:

`/admin/artifactTypes`

It's duplicated on the API Documentation: 

- Admin
- Artifact Type

It's attached a screenshot.
![image](https://github.com/user-attachments/assets/e9ad9788-debc-4411-89c3-63aca68073f1)

Best!

**Comment by EricWittmann** [comment]
Is this just because it has two tags? So it's listed under two categories by redoc?  It's the same endpoint, right?

**Comment by cesareomacias** [comment]
Hi @EricWittmann 

Yes, It's the same endpoint `/admin/artifactTypes ` It just listed in two categories (admin and Artifact Type).

Best!

**Comment by EricWittmann** [comment]
Okay in that case it's as designed. 😁

I absolutely love that somebody is reading the documentation though!
