### ISSUE TITLE
Missing "generate client SDK" functionality (or documentation how to enable it)

### ISSUE THREAD

**Issue by mslocinski-friday** [Apicurio/apicurio-registry#5273]
## Description

**Registry Version**: 3.0.0
**Persistence type**: SQL

I just installed the latest version 3.0.0 and can't find a place where I can generate client SDK - there was such functionality in 2.6.x.

Is it permanently removed? Maybe I need to enable it via some config parameter (maybe it's undocumented because I don't see any parameter that could be relevant)?

**Comment by EricWittmann** [comment]
Temporarily removed.  That functionality will get restored in a patch release.

**Comment by EricWittmann** [comment]
* https://github.com/Apicurio/apicurio-registry/pull/5289

**Comment by EricWittmann** [comment]
Functionality restored and will be available in 3.0.1.

**Comment by andreaTP** [comment]
@mslocinski-friday thanks for opening this issue, if you want to share I'm genuinely interested in learning how you are using this feature.
