### ISSUE TITLE
No option to delete artifacts in UI v3

### ISSUE THREAD

**Issue by mmmmillar** [Apicurio/apicurio-registry#5292]
There is no way to delete artifacts in v3 UI

REGISTRY_FEATURE_READ_ONLY is set to false

<img width="1293" alt="image" src="https://github.com/user-attachments/assets/d5de04b2-f268-42df-b00e-61bd76e5178d">

**Comment by EricWittmann** [comment]
Hi @mmmmillar .  Delete operations are now "opt-in" for Apicurio Registry.  By default, you cannot delete groups, artifacts, or versions.  But you can enable that functionality using the following configuration properties:

https://github.com/Apicurio/apicurio-registry/blob/dd705c4151130e1a7d6861ed8117642dd733fff8/app/src/main/java/io/apicurio/registry/rest/RestConfig.java#L21-L34

```java

    @Dynamic(label = "Delete group", description = "When selected, users are permitted to delete groups.")
    @ConfigProperty(name = "apicurio.rest.deletion.group.enabled", defaultValue = "false")
    @Info(category = "rest", description = "Enables group deletion", availableSince = "3.0.0")
    Supplier<Boolean> groupDeletionEnabled;

    @Dynamic(label = "Delete artifact", description = "When selected, users are permitted to delete artifacts.")
    @ConfigProperty(name = "apicurio.rest.deletion.artifact.enabled", defaultValue = "false")
    @Info(category = "rest", description = "Enables artifact deletion", availableSince = "3.0.0")
    Supplier<Boolean> artifactDeletionEnabled;

    @Dynamic(label = "Delete artifact version", description = "When selected, users are permitted to delete artifact versions.")
    @ConfigProperty(name = "apicurio.rest.deletion.artifact-version.enabled", defaultValue = "false")
    @Info(category = "rest", description = "Enables artifact version deletion", availableSince = "2.4.2-SNAPSHOT")
    Supplier<Boolean> artifactVersionDeletionEnabled;
```

You can set those config properties at deployment time using ENV vars.  For example:

```
docker run -it -p 8080:8080 --env apicurio.rest.deletion.artifact.enabled=true apicurio/apicurio-registry:latest-release
```

But also you will notice that they are dynamic properties.  So if you have Admin access to the server, you should be able to just go to the Settings page and enable them there:

![image](https://github.com/user-attachments/assets/ade75964-2b2c-4a46-9953-df332b7de199)

**Comment by EricWittmann** [comment]
Note: after enabling, you will likely need to reload the UI to see the changes.
