### ISSUE TITLE
Missing compatibility with Confluent Schema Registry API

### ISSUE THREAD

**Issue by Yoni-Weisberg** [Apicurio/apicurio-registry#5337]
## Description

**Registry
Version**: latest
**Persistence type**: all

As specified here: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--config-(string-%20subject)
the endpoint of `GET /config/subject` should support query parameter of `defaultToGlobal` which when set to `true` should provide the default value from the global config in case the subject has no config.

However, the `ccompat` API ignores this parameter.

### Environment

docker

### Steps to Reproduce

1. Set global config compatibility to `BACKWARD` (`POST /apis/ccompat/v7/config)
2. Create some subject (POST /apis/ccompat/v7/subjects/mySubject/versions)
3. Query the config with `defaultToGlobal=true` (GET /apis/ccompat/v7/config/abc?defaultToGlobal=true)
4. Result is `"compatiblity": "NONE"`

### Expected vs Actual Behaviour

Result should be `"compatiblity": "BACKWARD"`

**Comment by EricWittmann** [comment]
Fixed in:
* https://github.com/Apicurio/apicurio-registry/pull/5490
