### ISSUE TITLE
new versions of schema are created when schema hasn't changed when using ccompat endpoint

### ISSUE THREAD

**Issue by zzztimbo** [Apicurio/apicurio-registry#551]
Each time I run this:

```
 ./bin/kafka-avro-console-producer --property schema.registry.url=http://localhost:8080/api/ccompat --topic SNACKS_AVRO --property value.schema='
{
  "type": "record",
  "name": "myrecord",
  "fields": [
      {"name": "name",  "type": "string" }
    , {"name": "calories", "type": "float" }
    , {"name": "color", "type": "string" }
  ]
}' < ~/Workspace/kafka-serialization/snacks_2.txt
```

I get another version in the apicurio registry. I don't think this is the expected behavior.

**Comment by alesj** [comment]
Auto-register is by default (afaik) in Confluent’s serde.
It now just depends how this is handled server-side - would need to check
in more details
If you use Confluent’s serde perhaps turn this auto off.
Or use Apicurio’s serde which has more config options.

**Comment by EricWittmann** [comment]
Yeah I do think that the Confluent registry does a content check when registering a schema.  If the schema already exists in the registry (based on the actual bytes of the schema) then they won't re-register a new one - you'll get back the same GlobalId.  I'm not sure whether a new *version* will get created - I'm guessing not.  Although if you register the same schema to a different subject, you'll get a new subject+version but keep the same GlobalId.  That we will *not* do.  It's a storage optimization that isn't really necessary IMO.

That said, we can probably tweak the `register` method to better mimic the confluent behavior.  I've marked this as a bug.
