### ISSUE TITLE
JSON Schema de-referencing missing references in `allOf`

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#5511]
## Description

**Registry
Version**: 2.6.x
**Persistence type**: All

### Environment
Telus eval

### Steps to Reproduce
1. Create JSON schema artifact called `specref.json` (valid JSON schema, content does not matter)
2. Create another JSON schema artifact with reference to (1) like so:

```json
{
    "$id": "https://tinaa.telus.com/univ/resourceCatalog/tinaa/v1/ipv4Address.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "ipv4Address":  { 
            "type": "string"
        }
    },
    "required": ["ipv4Address"],
    "allOf": [
        {
            "$ref": "https://ext.com/specref.json"
        }
    ]
}
```

Note the `$ref` inside the `allOf`.

3. Request the content from the artifact in (2) but with dereferencing enabled

The response is:

```json
{
    "message": "Can't resolve 'https://ext.com/specref.json', only internal refs are supported.",
    "error_code": 500,
    "detail": "UnsupportedOperationException: Can't resolve 'https://ext.com/specref.json', only internal refs are supported.",
    "name": "UnsupportedOperationException"
}
```

**Comment by carlesarnal** [comment]
Isn't this expected if the dereferencing is pointing to an schema on the internet? Or are we discussing that the 500 must be handled (with that I do agree). Isn't this working if the $ref points to a reference in Registry?

**Comment by EricWittmann** [comment]
I believe that a mapping is being provided.  When the mapping is provided, and the `$ref` is not inside an `allOf` then it works.  But if a mapping is provided and the `$ref` **is** inside an `allOf` then it fails.  That's my understanding.  I haven't tested it yet.

**Comment by carlesarnal** [comment]
I have confirmed the problem. References re-writes were not properly handled inside array objects (allof, anyof, oneof etc). I have fixed the problem in the PR I linked.

**Comment by EricWittmann** [comment]
Fixed in:
* https://github.com/Apicurio/apicurio-registry/pull/5560
