### ISSUE TITLE
 Environment 'APICURIO_KAFKA_BOOTSTRAP_SERVES' doesn't work.

### ISSUE THREAD

**Issue by melodyfromheaven** [Apicurio/apicurio-registry#5539]
![image](https://github.com/user-attachments/assets/4c9dac56-5529-40da-a552-776c39cc2838)

https://www.apicur.io/registry/docs/apicurio-registry/3.0.x/getting-started/assembly-installing-registry-docker.html#installing-registry-kafka-storage_registry

Environment 'APICURIO_KAFKA_BOOTSTRAP_SERVES' doesn't work.
'APICURIO_KAFKASQL_BOOTSTRAP_SERVER' works well.

Is correct in the guide?

**Comment by carlesarnal** [comment]
The guide is correct, but there's a typo in the value you typed, it should be `APICURIO_KAFKA_BOOTSTRAP_SERVERS`, you're missing an 'R'.

**Comment by melodyfromheaven** [comment]
> The guide is correct, but there's a typo in the value you typed, it should be `APICURIO_KAFKA_BOOTSTRAP_SERVERS`, you're missing an 'R'.

That's just a typo when writing the issue. 'R' Still doen't work.

**Comment by melodyfromheaven** [comment]
![image](https://github.com/user-attachments/assets/b37fbe37-8ac8-4fb5-849e-746836a6ba6c)


![image](https://github.com/user-attachments/assets/bc4bb763-0cad-49ee-9884-634aaea427ca)

**Comment by carlesarnal** [comment]
You're right, the documentation is wrong. The correct value is APICURIO_KAFKASQL_BOOTSTRAP_SERVERS.
