### ISSUE TITLE
referenced schemas in ccompat endpoint is not supported? 

### ISSUE THREAD

**Issue by zzztimbo** [Apicurio/apicurio-registry#586]
I'm trying to use the confluent kafka python protobuf serializers and I'm seeing these errors when trying to use the apicurio-registry to produce messages. 

```
confluent_kafka.schema_registry.error.SchemaRegistryError: Unknown Schema Registry Error: b'Unrecognized field &quot;references&quot; (class io.apicurio.registry.ccompat.dto.SchemaContent), not marked as ignorable' (HTTP status code 400, SR code -1)
[2020-06-02 15:21:23,702] [90599] [INFO] [^----OneForOneSupervisor: (1@0x10f665c50)]: Restarting dead <Agent*: __main__.snack>! Last crash reason: Unknown Schema Registry Error: b'Unrecognized field &quot;references&quot; (class io.apicurio.registry.ccompat.dto.SchemaContent), not marked as ignorable' (HTTP status code 400, SR code -1) 
```

I believe it is due to these lines of code. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/schema_registry_client.py#L328-L334

I also noticed the confluent libraries encode the schema using base64. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/protobuf.py#L121-L132

**Comment by carlesarnal** [comment]
Which version of the registry are you using? We’ve introduced recently the support of the `getReferencedSchemas` operation.

**Comment by carlesarnal** [comment]
This was not supported but this is now implemented. Closing this issue,
