### ISSUE TITLE
Handle records poll in retry

### ISSUE THREAD

**Issue by alesj** [Apicurio/apicurio-registry#608]
Wrt this PR
* https://github.com/Apicurio/apicurio-registry/pull/606

If there would be any error in deserialization (or poll) currently consumer-loop would be finished,
where the app (Registry) would still "work" -- only loop thread would finish, resulting in an error log.
With this fix, we make sure we still try to poll the records until successful (or at least the error is noticed).
e.g. deserializer could depend on external resources, or input would be invalid (bad json, etc)

**Comment by alesj** [comment]
@paoloantinori ^

**Comment by EricWittmann** [comment]
Fixed on `master` with commit:  https://github.com/Apicurio/apicurio-registry/commit/f92c7f696c391b5242ec5199810142ded8241d3a
