### ISSUE TITLE
Increase granularity of logging config

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#609]
Right now we have one global env var `LOG_LEVEL` that sets the Quarkus logging level.  It would be better if we could get more granular about that so that we could change the logging level of e.g. just the Apicurio Registry logging.

**Comment by dang-gyg** [comment]
@EricWittmann any pointers to get started on this ticket? I tried to use the `quarkus.log.category.` as mentioned in [Quarkus Logging](https://quarkus.io/guides/logging#category-named-handlers-example) to change the log level for different namespaces/libraries but it did not work.

**Comment by EricWittmann** [comment]
That link is exactly where I would have started.  I don't have any insights other than that.  :(  Perhaps @carlesarnal has an idea why that wouldn't work....

@dang-gyg Can you perhaps open a Draft Pull Request with the changes you tried but didn't work?  Easier to collaborate that way!

**Comment by carlesarnal** [comment]
@dang-gyg A draft PR would be awesome so I can check what configuration do you have. Also, as a first suggestion, make sure that you have escaped the category name [this](https://quarkus.io/guides/logging#category-example) way.

**Comment by dang-gyg** [comment]
silly me. I got it working now. The reason it did not work was due to a conflicting log4j binding from another library I used. With just the jboss binding, it works as described in the tutorial, for example:
`%dev.quarkus.log.category."io.netty".level=WARN`
No escape is needed.

**Comment by EricWittmann** [comment]
I think we have dynamic, granular log level configuration now (via the /admin v2 rest api).  Closing this as a result.
