### ISSUE TITLE
UI - improve experience uploading artifact to slow storage

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#614]
This is maybe already in someone's TODO list.

When uploading an artifact in the UI to a registry using an async or slow storage sometimes there is some time after the user clicks the upload button and the page for the newly created artifact is open. It would be a nice improvement to add some marker or widget to indicate the UI is loading

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/commit/923237e89c0c455d782b226cb8215b98bf1702ae
