### ISSUE TITLE
Set up test env for apicurio-registry-search-client module

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#621]
Module apicurio-registry-search-client now includes tests that depend on some running env to execute properly, this tests should set up automatically the required env.
This is a blocker for #404

**Comment by EricWittmann** [comment]
Which tests in `apicurio-registry-search-client` require a running kafka env?

**Comment by famartinrh** [comment]
AFAIK `apicurio-registry-search-client` depends on an infinispan instance

**Comment by EricWittmann** [comment]
Search client is deprecated/removed.  Closing.
