### ISSUE TITLE
cannot access artifacts , blocking bug

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-registry#625]
Hi,
I've tried to deploy several templates:

- mem
- streams

with both dev or prod profile and I cannot load the main page. I see the following stack trace from the GUI:
```
{
   "message": "Network Error",
   "name": "Error",
   "fileName": "https://my-service-registry.apps.my.cluster.ocp4.openshift.es/ui/vendors.bundle.6b1a271b69192f98d9e5.js",
   "lineNumber": 289,
   "columnNumber": 56022,
   "stack": "pQXz/e.exports@https://my-service-registry.apps.my.cluster.ocp4.openshift.es/ui/vendors.bundle.6b1a271b69192f98d9e5.js:289:56022\nAy6X/e.exports/</h.onerror@https://my-service-registry.apps.my.cluster.ocp4.openshift.es/ui/vendors.bundle.6b1a271b69192f98d9e5.js:80:46039\n",
   "config": {
      "url": "http://my-service-registry.apps.my.cluster.ocp4.openshift.es/api/search/artifacts?limit=10&order=asc&over=everything",
      "method": "get",
      "headers": {
         "Accept": "application/json"
      },
      "transformRequest": [
         null
      ],
      "transformResponse": [
         null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1
   }
}
```

**Comment by EricWittmann** [comment]
How precisely have you tried installing?  Using the operator?  You mentioned templates, are you trying to use the openshift template?

The problem is that the browser is failing when trying to make an API call.  I was trying to figure out why when I think your OCP app was shut down.  So I can't reach it anymore.

**Comment by lucamaf** [comment]
sorry, yes I removed it but can reinstall. I used the openshift templates

**Comment by EricWittmann** [comment]
It would be better if you could use the OpenShift Operator when installing registry.  The template may be stale - it hasn't been updated since Tech Preview 2.  The GA release is operator based.  @jsenko can link you to operator documentation.

**Comment by lucamaf** [comment]
that's what I did in the end and it worked, thank you!

**Comment by EricWittmann** [comment]
@jsenko I'm thinking we should probably delete the OpenShift template from the repo - what do you think?

**Comment by EricWittmann** [comment]
And probably replace it with a Readme or something in that directory with a pointer to the operator on operator hub.
