### ISSUE TITLE
Add support for running registry in read-only mode

### ISSUE THREAD

**Issue by brokenjacobs** [Apicurio/apicurio-registry#637]
I have a scenario where I'd like to run the apicurio registry as a read-only replica from a central kafka/registry instance. I have a mirrormaker2 setup that replicates topics to multiple different destinations that need to operate offline if they lose connectivity. I want them to receive the latest schema changes via replication when they come online, but not allow updates to schemas at the remote locations.

It looks like I cannot do this with the 'kafka' storage driver as it will snapshot every 2 days to the snapshot topic. 

It is unclear if I can do this with the 'streams' storage driver. 

Currently I am using the confluent schema registry and setting the property:
`master.eligibility: 'false'`

To prevent it from making any changes to the topic.

**Comment by EricWittmann** [comment]
Just to be clear, you want a version of the registry where GET operations work but PUT, POST, and DELETE operations all fail.  Would it be possible to achieve that with some sort of e.g. nginx proxy in front of the registry?

**Comment by brokenjacobs** [comment]
Yes it would be possible from an API perspective to allow only GET/HEAD, but at least for the 'kafka' storage there is a snapshot interval that writes back to a topic that would still occur. Even without any updates.

It is unclear to me if the same applies to the Kafka streams implementation. Some clarification on that would help greatly.

**Comment by EricWittmann** [comment]
@alesj Any thoughts on this?

**Comment by brokenjacobs** [comment]
ping?

**Comment by brokenjacobs** [comment]
A question: could I get away with just blocking POST/DELETE requests to the api? If so would I need to block to certain paths, or could I just block all POST/DELETE actions on the read only copy? I don't care if it breaks UI functionality.... Just so long as operationally it would work.

Related to this: I would be using one of the two kafka persistence backends for this.

**Comment by brokenjacobs** [comment]
It looks like these application config properties could help as well, and that the streams interface does not do checkpointing as near as I can tell... I also can't figure out how to override the topic names used either... which I will need to do. UI read only properties:
```
# UI Features
%dev.registry.ui.features.readOnly=${REGISTRY_UI_FEATURES_READONLY:false}
%prod.registry.ui.features.readOnly=${REGISTRY_UI_FEATURES_READONLY:false}
```

**Comment by alesj** [comment]
Streams storage doesn't have snapshot feature.
It's all already in Streams itself -- see KeyValueStore and its log-topics.

You can configure entry topic and storage store name.
See:
* https://github.com/Apicurio/apicurio-registry/blob/master/storage/streams/src/main/java/io/apicurio/registry/streams/StreamsPropertiesImpl.java
And:
* https://github.com/Apicurio/apicurio-registry/blob/master/storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryConfiguration.java#L74

**Comment by brokenjacobs** [comment]
Any hints you could provide about the appropriate property name / environment variable? I've tried several variations but I can't seem to get it to pick up the storage.store and global.id.store

**Comment by alesj** [comment]
You need a full profile + prefix + key path:
* %dev.registry.streams.topology.storage.store=my-store-name

**Comment by EricWittmann** [comment]
Yes I think if you block all PUT/POST/DELETE REST API calls that will work.  That's basically how I would implement this feature in Registry itself - I would add a JAX-RS interceptor that checked for the read-only flag and responded with an error if it was enabled (only for PUT/POST/DELETE operations).

@alesj Do any of the Registry API GET calls result in changes to the topics?  I think that's the crux if the question here, if I'm not mistaken.  I think you already answered the snapshot question, but maybe not this part?

**Comment by brokenjacobs** [comment]
I got it working using:
```
%prod.registry.streams.topology.global.id.topic
%prod.registry.streams.topology.storage.topic
%prod.registry.streams.storage-producer.global.id.topic
%prod.registry.streams.storage-producer.storage.topic
```
Are all 4 of these necessary?

Also. General quarkus complaint here, because of Quarkus's configuration profiles support it is not possible to override these settings with an environment variable, since % isn't a valid env var. So i'm going to have to set env vars in my deployment manifest, and then use the env vars in the JAVA_OPTIONS environment variable in order to be able to cleanly 'modify' these settings with Kustomize. IMO it would be better to not use the configuration profiles at all in this case. Especially in a kubernetes context it just makes your manifests more complicated.

I need to modify the topic names on the read only deployments, because with mirrormaker2 the topics change names in the 'read only' clusters.

On the blocking the api calls, that is the way to go I think. To be comprehensive I'd also add the list of authorized methods to the CORS headers being returned by the API as well. Perhaps a:
```
REGISTRY_API_READONLY:false
```
env var similar to the UI setting?

**Comment by alesj** [comment]
I think you should be fine with the top two.

You can drop the profile prefix -- as I think I fixed this before prod release. @EricWittmann, right ?
And it should pickup env vars as well.
e.g. REGISTRY_STREAMS_TOPOLOGY_STORAGE_TOPIC=foobar

**Comment by alesj** [comment]
I don't think that lookup into KVStore should issue any changes to the topic(s).

**Comment by EricWittmann** [comment]
@alesj If you can tell me which commit fixes the profile prefix issue I can tell you which version it's in.  :)

@brokenjacobs I'm not sure about an ENV variable for the readonly mode - it's unclear to me whether ENV vars are mutable in e.g. kubernetes without a pod restart.  I'm thinking we definitely want this setting to be mutable without restarting the app...

**Comment by alesj** [comment]
> If you can tell me which commit fixes the profile prefix issue I can tell you which version it's in. :)

https://github.com/Apicurio/apicurio-registry/commit/afa97ca640e64effd218382022b814686d5c739c

Simplify properties handling

**Comment by EricWittmann** [comment]
That commit is on `master` but not on the `1.2.x` branch.  So it's not part of any release yet - it will be part of the next release (1.3.0.Final).

**Comment by carlesarnal** [comment]
This is possible when using the new KafkaSQL storage variant by blocking the requests and no snapshot is happening, closing.
