### ISSUE TITLE
Create a combined SerDe for Kafka Streams use of Avro

### ISSUE THREAD

**Issue by AndrewJSchofield** [Apicurio/apicurio-registry#641]
Kafka Streams uses a combined serialiser/deserializer called a SerDe. The Apicurio Avro support has separate Serializer and Deserializer classes, but no SerDe. I would like to be able to use the Avro support as the default SerDe in a Kafka Streams application so I can write something like this:

```
        Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "ICMJob");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
        props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, AvroKafkaSerDe.class);
        props.put(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM, "http://localhost:8080");
        props.put(AbstractKafkaSerDe.REGISTRY_ID_HANDLER_CONFIG_PARAM, "io.apicurio.registry.utils.serde.strategy.AutoRegisterIdStrategy");
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        props.put(StreamsConfig.COMMIT_INTERVAL_MS_CONFIG, 10 * 1000);
        
        StreamsBuilder builder = new StreamsBuilder();

        KStream<String, String> stream = builder.stream("mytopic");
        stream.print(Printed.toSysOut());

        KafkaStreams streams = new KafkaStreams(builder.build(), props);
        streams.start();
```

Without a SerDe, I need to create my own SerDe from an instance of a Serializer and a Deserializer, and I then need to provide that SerDe object where the API permits overriding of the default SerDe. This is cumbersome.

**Comment by EricWittmann** [comment]
@Apicurio/ibm-developers Is this something one of you fine folks could pick up?  :)

**Comment by katheris** [comment]
Hey @EricWittmann, this one also isn't required for us for next release, but we think it might not take too long so will get to it if we can. I'll let you know if/when we are picking it up

**Comment by EricWittmann** [comment]
Yeah let me know and I'll assign it as appropriate.

**Comment by EricWittmann** [comment]
@ajborley This can be close now, yes?

**Comment by ajborley** [comment]
Yes, thanks!
