### ISSUE TITLE
"Clean" Avro option for Avro serialiser and deserializer

### ISSUE THREAD

**Issue by AndrewJSchofield** [Apicurio/apicurio-registry#642]
The Avro format used by the Apicurio Avro serialiser and deserializer uses a "magic byte" followed by the artefact id of the schema, and then the binary Avro encoding. This is nice and compact, but  it means the payload cannot be used directly by other components that use Avro.

It would be good to have an alternative way to carry the artefact id as a Kafka record header. When enabled, neither the magic byte nor the artefact id would be in the payload.

**Comment by tagarr** [comment]
@alesj I was thinking or reusing the constants defined in JsonSchemaSerDeConstants. How do you feel about creating a SerDeConstants class and putting all the config constants into that i.e. also including constants defined in AbstractKafkaStrategyAwareSerDe and AbstractKafkaSerDe ?

**Comment by alesj** [comment]
@tagarr sure, np

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/811
