### ISSUE TITLE
Option to use Avro schemas with JSON encoding

### ISSUE THREAD

**Issue by AndrewJSchofield** [Apicurio/apicurio-registry#643]
Avro can be represented using a binary encoding or a JSON encoding. With the JSON encoding, you get the value of expressing the structure of the data using an Avro schema but keeping the payload human-readable, or even processing by systems that understand JSON but not Avro.

It would be great to have a configuration on the Avro serialiser (and perhaps deserializer) to request a JSON encoding instead of binary.

**Comment by tagarr** [comment]
@alesj Are you actively working on this issue or would you be happy for me to pick it up ?

**Comment by alesj** [comment]
@tagarr it would be great if you could pick it up :-)

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/774
