### ISSUE TITLE
Transitive compatibility

### ISSUE THREAD

**Issue by AndrewJSchofield** [Apicurio/apicurio-registry#644]
The registry supports backwards and forwards compatibility checking between the current version of a schema and the new version (N-1 to N).

In order to support longer lasting compatibility, it would be good to have a "transitive" compatibility option which ensures that the compatibility applies across all versions of the schema (1, 2, 3, ....., to N).

For example, I would like to be able to have producers using the latest version of a schema safely sending data to consumers that understand any version of the same schema. Clearly, an older schema would not be identical to the latest version, but it could be comprehensible still provided the transitive compatibility is maintained.

**Comment by EricWittmann** [comment]
The compatibility rules allow for this, but the implementation is lacking (we don't currently supply all of the content versions to the compatibility checker).

**Comment by EricWittmann** [comment]
@Apicurio/ibm-developers Is this something required for your next release?

**Comment by katheris** [comment]
Hey @EricWittmann this isn't a requirement for us for the next release. A nice to have, but not high priority

**Comment by EricWittmann** [comment]
I believe this is fixed in registry 2.0.  I am closing it, but please @jsenko can you verify and re-open if I'm wrong?

**Comment by jsenko** [comment]
This should be fixed, yes.
