### ISSUE TITLE
UI - inconsistent display of modifiedOn

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#651]
Tested using streams based persistence.
Testing the UI I created one artifact and uploaded two versions of it, then I played with the rules configuration to see the createdOn and modifiedOn dates become different. However the modifed on date is not correct in the latest version view (which should be equivalent to version 2 view)

Version 1
![image4](https://user-images.githubusercontent.com/46371672/85389635-fd961b80-b547-11ea-8ade-d8dcdf860d36.png)

Version 2
![image5](https://user-images.githubusercontent.com/46371672/85389606-f1aa5980-b547-11ea-8a51-a3c12dc7d464.png)

Version Latest
![image3](https://user-images.githubusercontent.com/46371672/85389548-db040280-b547-11ea-84ce-9b4035998014.png)

**Comment by carlesarnal** [comment]
Hi @famartinrh, can you have a look at the response from the endpoint? Thanks!

**Comment by famartinrh** [comment]
I guess you are looking for the metadata lookup, here are the response for each version
Version 1
```
{"version":1,"createdOn":1592908645627,"type":"GRAPHQL","globalId":131073,"state":"ENABLED","id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003"}
```
Version 2
```
{"version":2,"createdOn":1592908651716,"type":"GRAPHQL","globalId":196609,"state":"ENABLED","id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003"}
```
Latest (which should be same as version 2?)
```
{"createdOn":1592908651716,"modifiedOn":1592908651716,"id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003","version":2,"type":"GRAPHQL","globalId":196609,"state":"ENABLED"}
```

Looks like the bug is modifiedOn not being sent for version 1 and 2 , so the `a few seconds ago
` is incorrect, which makes sense because it's a several minutes now since I modified the artifact. The createdOn and modifiedOn being the same for latest is a bug as well

**Comment by famartinrh** [comment]
There are two bugs identified, we will use this issue to track this bug:
Metadata for both versions does not return the modifiedOn date, that's the reason why version 1 and version 2 both always have `a few seconds ago` as modied on date

**Comment by EricWittmann** [comment]
Good point - perhaps the UI should hide the "modifiedOn" information when displaying a specific version.

**Comment by EricWittmann** [comment]
We are working on a new UI design which would solve this issue. :)

**Comment by famartinrh** [comment]
Actually createdOn and modifiedOn are properties in our APIs but we don't have modifiedOn in the database squema. So createdOn column in the database could be understood as "date when artifact version was uploaded". 

For example: createdOn for the first version of an artifact is the "createdOn" in the API, createdOn for each version of an artifact is the date when that version was uploaded and createdOn for the last version of an artifact is "modifiedOn" in the API.

These dates are not updated when modifiying the metadata with the API call for that purpose or from the UI. I'm fine with that.

So our API is returning dates correctly, this is not a bug in the backend. But we could improve the UI as Eric pointed out and hide "modifiedOn" for every version that  is not "latest".

**Comment by EricWittmann** [comment]
Fixed in the PR above.
