### ISSUE TITLE
UI - unclear search results (search by label)

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#652]
Tested using streams based persistence.
Testing the UI I created one artifact and uploaded two versions of it, then I edited both versions to add two different labels to each one, "label1" to version 1 and "label2" to version 2.
Then in the artifacts list I tried to search by "label1" and "label2" both searches return the artifact created and each one displays the matching label 
![image1](https://user-images.githubusercontent.com/46371672/85391170-20c1ca80-b54a-11ea-98f6-56a25713c8dd.png)
![image2](https://user-images.githubusercontent.com/46371672/85391188-23bcbb00-b54a-11ea-8c38-7fe28f13f39f.png)

It's not clear to me if there is a bug and if so what exact behaviour is not correct, I just want to point out the fact that looks like it's possible to set different labels to different artifact versions and then the artifact search allows to search by labels on all version but it's not clear what is being displayed in artifacts lists (is it a specific artifact version?) , there is a weird mix with the labels and the way the search works that can confuse users

**Comment by EricWittmann** [comment]
@alesj I think the streams implementation of the Search API should only search meta-data over the "latest" version of each artifact.  I think right now it is perhaps searching over all versions.  And maybe returning the version that matched the search.

**Comment by EricWittmann** [comment]
Thoughts @carlesarnal ?

**Comment by alesj** [comment]
Yeah, now it's going over all data (data == artifactId), and over all artifacts (per data/artifactId),
and tries to find a match -- in metadata.
If other storages only look for lates, then this needs to be changed / fixed.

**Comment by carlesarnal** [comment]
The other storages are searching over the latest version. For the streams one, I think we should change it. Playing a bit I've found something interesting I wanted to comment. The `ArtifactSearchsResults` points to a specific version of the artifact but, when the user goes to the artifact details page, the page shows the latest version of the artifact, so maybe is a good idea to adapt this to show the version returned from the search. Obviously this 'strange' behaviour is something that will be solved once we change the storage, just wanted to mention it.

**Comment by EricWittmann** [comment]
Looking at the definition of `SearchedArtifact` in the API, I do not see a `version` property.  And that's what I expected (no version info in the search results).   Where are you seeing the pointer to a specific version?

My thought is that the search should be returning a list of artifacts *without* any indication of a version.  The behavior in the UI is correct IMO - click on an artifact and be taken to the latest version.

**Comment by carlesarnal** [comment]
Yes, there is no `version` property. My point is that for now, in the streams storage, we can face the situation of returning a specific version in the search results (since it's searching over all the artifact versions) and if the user goes to the artifact details page, then the displayed version is the latest one. Not a big deal, and will be fixed once we change the streams storage, just wanted to make that point.

**Comment by EricWittmann** [comment]
Ah ok I misunderstood - thanks for clarifying.

**Comment by EricWittmann** [comment]
@carlesarnal Is the streams implementation still searching over all versions, or just the latest?

**Comment by carlesarnal** [comment]
All versions, nothing has been changed here.

**Comment by carlesarnal** [comment]
@EricWittmann, I guess this can be closed...

**Comment by Do-min-ik** [comment]
> All versions, nothing has been changed here.

@carlesarnal  is this still true? I want to search for a property in ALL versions, but, apparently, it only searches the latest.
