### ISSUE TITLE
Artifact metadata shows incorrect modified on date

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#653]
Identified through the UI from issue #651 
```
http://XXXXXXXXXXX/api/artifacts/f207e6ca-517d-4e91-8e57-cbeb21d8f003/meta
```
```
{"createdOn":1592908651716,"modifiedOn":1592908651716,"id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003","version":2,"type":"GRAPHQL","globalId":196609,"state":"ENABLED"}
```

The createdOn and modifiedOn dates being the same is not correct as I've been modifiying the artifact rules.
Also something that looks wrong and it's related to this , here the metadata for the artifact versions
```
{"version":1,"createdOn":1592908645627,"type":"GRAPHQL","globalId":131073,"state":"ENABLED","id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003"}
```
```
{"version":2,"createdOn":1592908651716,"type":"GRAPHQL","globalId":196609,"state":"ENABLED","id":"f207e6ca-517d-4e91-8e57-cbeb21d8f003"}
```

**Comment by EricWittmann** [comment]
I think this may be fixed on `master` but I could be wrong. @carlesarnal thoughts?

**Comment by carlesarnal** [comment]
Sorry @EricWittmann, a bit late but yes, this is something that can be solved on `master`.

**Comment by EricWittmann** [comment]
I actually meant that is might **already** be fixed on `master`...

**Comment by carlesarnal** [comment]
Ok sorry, I totally misunderstood that. No, this hasn't been fixed yet on `master`.

**Comment by EricWittmann** [comment]
OK thanks.  I've marked it as a bug and assigned it to @carlesarnal  :) :)

**Comment by EricWittmann** [comment]
@carlesarnal This is probably fixed in all storages at this point, right?

**Comment by carlesarnal** [comment]
Fixed, yes.
