### ISSUE TITLE
Replace the current generated API Client with a custom one

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#672]
The generated client for the registry ends up requiring a lot of dependencies and is also not as easy to use as it could be.  We should deprecate it and replace it with a more purpose-built (custom) client based on Apache HTTP Client or OK HTTP client or something like that.

**Comment by alesj** [comment]
Perhaps check Square’s Retrofit lib - its dependencies, etc

**Comment by antonmry** [comment]
it would be great if the new client allows some easy way to introduce customizations.  For example, we can add headers with the actual one using Rest Easy interceptors. It isn't easy to use but it helps us to integrate the registry with our systems and to overcome some security restrictions so it would be great if the new client can provide a similar (or easier to use) functionality

**Comment by gunnarmorling** [comment]
+1 for this. I don't think you assume JDK 11 as a basis yet, right? Otherwise you just could use the new built-in HTTP client.

**Comment by EricWittmann** [comment]
This has been completed and merged:  https://github.com/Apicurio/apicurio-registry/pull/721

Note: it was merged manually so the PR doesn't report as merged. :(  Sorry @carlesarnal
