### ISSUE TITLE
Caching in Serde strategies

### ISSUE THREAD

**Issue by antonmry** [Apicurio/apicurio-registry#687]
There are several strategies in https://github.com/Apicurio/apicurio-registry/tree/a077f18c541f22bc04251532d4a8f967287372a7/utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy but most of them don't cache the request so it's requesting to the Service Registry each time an event is serialized/deserialized. That's highly inefficient and I don't see any use case which could require that behaviour. 

There is a specific strategy which is caching: https://github.com/Apicurio/apicurio-registry/blob/a077f18c541f22bc04251532d4a8f967287372a7/utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/CachedSchemaIdStrategy.java

But it doesn't allow to update the artifact when the schema is different which it's the most standard behaviour. 

In general terms, I think all the out-of-the-box strategies should cache requests and probably try to decouple caching from the strategy because it's not about the strategy but a low-level behaviour of the serializer.

**Comment by EricWittmann** [comment]
What's the status of this?  Are the serdes classes working well now?  @Apicurio/ibm-developers ?

**Comment by tagarr** [comment]
We're currently testing. Our debezium connector is working fine, but we are continuing on some other scenarios

**Comment by antonmry** [comment]
Why this commit has been reverted? We are using that strategy without problem so far. Is it causing problems?

**Comment by tagarr** [comment]
Serdes classes are working for us, but not sure this issue is relevant to what we were doing

**Comment by EricWittmann** [comment]
I don't think it was actually reverted:  https://github.com/Apicurio/apicurio-registry/blob/master/utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/AbstractCrudIdStrategy.java#L54

**Comment by antonmry** [comment]
You are right, I got confused with https://github.com/EricWittmann/apicurio-registry/commit/a3c9de4233fd97eb2873da1f60e9f1f31651483c . Sorry for the misunderstanding.

**Comment by EricWittmann** [comment]
To everyone on this thread, please be aware that with Apicurio Registry 2.0 we have significantly renovated the Serdes classes to hopefully make them easier to use/configure.

Caching is now more consistent we think, and naming/config properties have been cleaned up.  I'm closing this because I think 2.0 cleans everything up nicely.  Please feel free to re-open if you try 2.0 (RC1 will be released this week) and you still have serdes class problems.
