### ISSUE TITLE
Clarification on available communication channels

### ISSUE THREAD

**Issue by elakito** [Apicurio/apicurio-registry#690]
This is not about a channel where apricurio-registry actually communicates with other systems but about a channel where the users and developer of apicurio-registry can communicate.

I don't know what is the preferred way to ask questions on apicurio-registry. The contact info page at https://www.apicur.io/contact/ mentions the mailing list apicurio@lists.jboss.org but there has not been any activity in the list since June 2019. And I don't know if creating a issue ticket for each question is really expected.

It would be nice if there is a dedicated Google-Group or Slack channel to be able to ask some questions. If there is already one, I didn't know about it. Please let me know.

regards, aki

**Comment by katheris** [comment]
I would also be interested in knowing the answer to this as I had some questions that I wasn't sure needed an actual issue.

**Comment by EricWittmann** [comment]
I'm actually pretty comfortable with using GitHub issues to ask questions (e.g. I have labeled this as a question).  :)  But I'm open to suggestions.  I think the email list never really took off, so I should probably remove that from the Contact page.  I would definitely be find with a Google Group as well.  Thoughts on this @jsenko @carlesarnal @alesj ?

**Comment by carlesarnal** [comment]
I'm a big fan of the GitHub issues usage so we can track progress or even create related tasks to the original questions. Maybe we should add some instructions at `Readme` level on how to properly ask questions using GitHub issues (e.g. correct usage of labels).

**Comment by antonmry** [comment]
I'm actively participating in the Strimzi and in the Confluent Schema Registry slack channels. They are quite active and helpful. I think the same would apply for Apicurio but not sure where it would be the best place. A Slack group only for Apicurio sounds a bit too much, it would be better integrated with other components. Other option is Gitter: https://gitter.im

**Comment by alesj** [comment]
Yeah, I agree with @carlesarnal on the GitHub issues -- we just need proper instructions and labels.

**Comment by antonmry** [comment]
As an idea, strimzi team runs an open meeting (using CNCF zoom) each two weeks to discuss the roadmap, gather ideas from the community, review issues, etc. This could be a good addition to the available communications channels

**Comment by EricWittmann** [comment]
OK I think for now a combination of GitHub issues and an open community meeting actually seems pretty reasonable.  Probably we can do it for all of Apicurio, not just the registry.  That would probably make the most sense.  We should think a little bit more about chat as well.  People do like that.  We use Gitter for Microprofile and it's not bad.  It's a very low barrier to entry (nothing to download and install) which is nice.  I might be coming around to that even as I type this...  :)

**Comment by carlesarnal** [comment]
If anyone finds this wondering about it we now also have a zulip [chat](https://apicurio.zulipchat.com/) that public users can use to ask questions to the team. I'm closing this as we have two appropriate communication channels (GH and Zulip).
