### ISSUE TITLE
Incompatibility in ccompat api

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#700]
Getting the subject configuration, the compatibility in the response should be `compatibilityLevel`, not `compatibility`. I don't know why the difference with other responses but...

https://github.com/Apicurio/apicurio-registry/blob/a4e0bfde28c0e802f756654bb783b6d87d50444c/app/src/main/java/io/apicurio/registry/ccompat/rest/ConfigResource.java#L91

https://docs.confluent.io/current/schema-registry/develop/api.html#get--config-(string-%20subject)

Also, compatibility rules between global/local rules and `ccompat` api seem to be disconnected. Confluent seem to respond with different information than Apicurio dependending on the global/local rules.

Example:
* `FULL` global compatibility rule set, `http://localhost:8081/api/ccompat/config/X` returns `NONE`. Even with `?defaultToGlobal=true` (see [Confluent Rules](https://docs.confluent.io/current/schema-registry/develop/using.html#show-compatibility-subject-or-global))
* If I set any compatibility (artifact/global) using `ccompat`, the ui doesn't show it and it fails when trying to update it.

**Comment by EricWittmann** [comment]
@carlesarnal Can you have a look at this?

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-registry/pull/867
