### ISSUE TITLE
Global rule set via env variable

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#701]
Hi, with confluent's schema registry you can pass the global compatibility level for all subjects, like this:

``` yaml
SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: FULL
```
I can't find a way to do it here, can it only be done via api/ui?

Thanks

**Comment by EricWittmann** [comment]
We don't currently have that feature - likely because we didn't know it existed in Confluent.  If this is a useful feature, we should open up an enhancement issue (or just convert this one).

**Comment by tomasAlabes** [comment]
Please do 🙂

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-registry/pull/803
