### ISSUE TITLE
Allow changes to Log Level without application restart

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#715]
It would be very useful to be able to change the log level without having to restart the application.  This is particularly helpful for support.

**Comment by EricWittmann** [comment]
https://stackoverflow.com/questions/63250947/how-to-change-the-log-level-during-runtime-in-quarkus

**Comment by famartinrh** [comment]
#1107

**Comment by EricWittmann** [comment]
I wonder if we will need this to be per-tenant. :( :(

**Comment by famartinrh** [comment]
I know... but I haven't found a way in java/quarkus world to configure the log level per request. So I think the only solution we have is to put tenant information in the log traces (using MDC context ideally) and having the logging stack to group the logs per tenant

**Comment by EricWittmann** [comment]
Yeah that's something we likely need to do **anyway**.
