### ISSUE TITLE
Disallow empty content

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#717]
We had a user report that the registry allowed them to add empty content (although this is not allowed if the Validation rule is enabled).  This can be problematic in a few ways, including causing potential issues (TBD) with Kafka Streams compaction.  In any case, it might be useful to do one of two things:

1. Disallow empty content always
2. Introduce a new rule to allow/disallow empty content

Thoughts @alesj @carlesarnal @jsenko ?

**Comment by alesj** [comment]
I would disallow empty content always.

**Comment by carlesarnal** [comment]
+1 disallowing empty content.
