### ISSUE TITLE
Add support for Artifact Groupings

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#725]
Right now we just have a flat list of artifacts.  It would be better if we supported the ability to create Groupings so that artifacts could be grouped together.  This is very useful for authorization purposes as well as just organizational purposes.  

Touch points:

- [x] Apicurio Registry API (native API)
- [x] SQL storage
- [x] REST Client
- [x] In-memory, asyncmem, and ISPN storage
- [x] Mapping of IBM compat API
- [x] Mapping of Confluent compat API
- [x] Streams storage
- [x] User interface
- [x] Maven Mojo
- [x] Kafka Serdes
- [x] Converter?
- [x] KafkaSQL storage
- [x] CLI
- [x] Examples

**Comment by EricWittmann** [comment]
Note to @chrish42 - I saw your comment here:  https://github.com/cloudevents/spec/pull/625#issuecomment-659570051

If you're looking for projects that will be implementing the cloudevents registry spec, it is our intention to do so.  If you're not already aware of this project, it is Red Hat's schema registry solution.  :)

**Comment by zaheershaik** [comment]
It'd be great to have schemas/artifacts to be grouped and have the [API paths support schema groups](https://github.com/cloudevents/spec/blob/v1.0.1/schemaregistry/schemaregistry.md#31-path-hierarchy). I'm looking at this [proposed schema registry spec from CloudEvents](https://github.com/cloudevents/spec/blob/v1.0.1/schemaregistry/schemaregistry.md). Are there any plans to support schema groups, and supporting [multiple formats](https://github.com/cloudevents/spec/blob/v1.0.1/schemaregistry/schemaregistry.md#221-multi-format-schema-groups) to an artifact in the roadmap?

**Comment by EricWittmann** [comment]
This is on the roadmap and should be in progress "soon".  :)  Our implementation of schema groups will automatically be multi-format.

Ultimately we would like to implement the schema registry API defined in CNCF (in addition to our native API).  I'm not sure if our implementation will map 100% onto the CNCF schema registry API, but we'll see once we dig into it.

**Comment by EricWittmann** [comment]
Almost done with this.  Note that multiple-formats *per artifact* is not supported.  I misread your question @zaheershaik - we support multiple formats per group (meaning you can have protobuf and avro artifacts in the same group).  But we don't support having a single artifact with both JSON Schema and Avro formats.  It's an interesting idea, but not yet on the roadmap for us.

**Comment by ozarkblue** [comment]
Having a group based authorization will enhance this product adaptability within Org setup where a team needs to manage artifacts.Waiting to see this feature.
@EricWittmann any update if anyone working on this?

**Comment by EricWittmann** [comment]
We aren't actively working on this feature - but I agree that it is a desirable enhancement.

**Comment by carlesarnal** [comment]
Closing as the main feature has been implemented. We're discussing now more options for authorization (not only for groups) but that will be tracked separately.
