### ISSUE TITLE
Add comments to project.yaml for clarity

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#728]
It would be very useful to have comments in the project.yaml file.

We should also take some time to quickly document how to perform an upstream release.  Could be an added section to the existing readme?  Or perhaps instead a separate markdown file.

**Comment by riprasad** [comment]
@EricWittmann I have added few comments in the project.yaml file in this PR https://github.com/Apicurio/apicurio-registry/pull/745
