### ISSUE TITLE
Test that deploy to maven central succeeded (release workflow)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#730]
Add a step to the release workflow where we verify that the artifacts were actually deployed properly to maven central.  At a minimum we should have a simple test/demo maven project that we can use to build and verify that the appropriate artifacts are available.

**Comment by jsenko** [comment]
Can we build the examples repo after the release, so we don't have to use a separate test repo. We can add a profile to the examples that would make sure all artifacts are downloaded.

**Comment by EricWittmann** [comment]
So I think what we can do here is twofold:

1) A basic `curl` command that tries to download one or two of the artifacts using a direct URL to maven central
2) We can create a basic standalone maven project (this can be just a `pom.xml` really) that pulls in one or more Apicurio Registry artifacts as dependencies - once the push is done we can clean out the local `.m2/repository` equivalent and then `mvn package` the test project

Note that for (1) the URL can be something like this (for example):

https://repo.maven.apache.org/maven2/io/apicurio/apicurio-registry-client/$RELEASE_VERSION/apicurio-registry-client-$RELEASE_VERSION.pom

If the push failed then this would result in a 404.  Otherwise it will work.

**Comment by riprasad** [comment]
Are we going to do both or just the `curl` command would be sufficient? @EricWittmann

**Comment by riprasad** [comment]
Also, Instead of including the steps in the release workflow, I would suggest that we should have a third workflow `verify-release.yaml` where we could verify both the docker push and deploy to maven central.  WDYT @EricWittmann @jsenko

**Comment by EricWittmann** [comment]
I think we should do both the `curl` and the sample project.  The `curl` goes first as a quick smoke test, and then building the sample project as a more thorough test.

I'm fine with a separate workflow.
