### ISSUE TITLE
Add a step to the release workflow to send a tweet

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#732]
I'm sure there is a github action for this we can use.  Obviously we'll need to secrets for the twitter login info (or does twitter have support for tokens?).

**Comment by EricWittmann** [comment]
Here is an example of a tweet sent when Apicurio Studio was released:

![image](https://user-images.githubusercontent.com/1890703/89288486-be1d1d80-d623-11ea-900b-49555760c5a1.png)

So I suggest this text:

> `$PROJECT_NAME` version `$RELEASE_VERSION` has been released!  Check out the release notes here:  `$GITHUB_RELEASE_URL`

Obviously those variable names are just placeholders.  We should add a project name property to **project.yaml**, and we already have a variable for the release version.  Do we also already have a GitHub release URL?  I know we have it in the **latestRelease.json** file we're curling for the website... can you extract it from there and use it?

**Comment by riprasad** [comment]
Thanks! This is what I needed.
