### ISSUE TITLE
Bug with USE_SPECIFIC_AVRO_READER config param

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#737]
From #699

There's a bug in the code when trying to use the `REGISTRY_USE_SPECIFIC_AVRO_READER_CONFIG_PARAM` property. Just setting it to `true` is not enough, you also have to set the `REGISTRY_AVRO_DATUM_PROVIDER_CONFIG_PARAM` prop to `DefaultAvroDatumProvider`, so that the other one is picked up. Without this, the code doesn't go through the check of the specific avro reader config.

Thanks

**Comment by EricWittmann** [comment]
@alesj Do you view this as a bug or a documentation issue?

**Comment by alesj** [comment]
It's a bug.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/commit/65cfe6da2462710a18bf40d9507fed8af771220b
