### ISSUE TITLE
Set global rules in a programmatic way

### ISSUE THREAD

**Issue by antonmry** [Apicurio/apicurio-registry#750]
Global rules can be only configured in a programmatic way using the API  `http://apicurio/api/rules/{rule}`. This makes installation and configuration automation of the registry a bit complex. It would be great if they could be created with a value by default using env variables or other type of configuration.

This would allow also to establish them in the operator.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/803
