### ISSUE TITLE
Support dynamic log levels/configuration

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#769]
It would be very useful, particularly for debugging running production applications, if the log levels for the application could be configured dynamically without restarting the application/pod.  We need to explore whether this is possible using the logging frameworks available to us, and then how to enable some sort of API for it.

**Comment by alesj** [comment]
This should simply be a question for Quarkus.
Or/if how they do it ...

**Comment by alesj** [comment]
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/dynamic.20log.20config
