### ISSUE TITLE
Create parent for storage modules to share

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#802]
All of the storage maven modules each run the entire suite of Quarkus based integration tests.  So the same set of test dependencies is required for all of the storage variants.  We should isolate these deps in a BOM so that we only need to keep it updated it one place.

**Comment by alesj** [comment]
Ah, OK, the approach we have now is good, you would just like to remove the list of deps one needs to copy -- makes sense, if easily doable.

**Comment by EricWittmann** [comment]
Exactly - would just be nice to maintain the list of test dependencies in one place so when a new dep is needed, we don't have to add it to **every** storage variant's `pom.xml`.  Should be easy enough.  I think @jsenko mentioned he's had some experience creating BOMs.

**Comment by riprasad** [comment]
@EricWittmann Sure Eric. I have no prior experience with BOM. Would love to take this up, just require a bit of support.

**Comment by EricWittmann** [comment]
Great - this is not a high priority, just a nice to have thing.  I think a google search for "maven bom" should yield some interesting information.
