### ISSUE TITLE
Maven plugin always downloads .avsc file extension even registred non Avro schema

### ISSUE THREAD

**Issue by dmvolod** [Apicurio/apicurio-registry#806]
I registered a protocol buffer schema via maven plugin and all registered fine.
When I tried to download it in the maven plugin in other project, the file created with the .avsc extension

**Comment by alesj** [comment]
You should set the extension property:

    /**
     * Default artifact file extension to use when writing the artifact to file-system.
     */
    @Parameter(defaultValue = ".avsc")
    String artifactExtension;

**Comment by alesj** [comment]
But I guess we could improve this -- by first grabbing artifact's metadata, matching its type against known extensions ...
Perhaps a PR with this? ;-)

**Comment by dmvolod** [comment]
Oh, thanks @alesj 
I thought that it's possible to get extension by type in registry.
I can provide a PR for this.

**Comment by alesj** [comment]
> I thought that it's possible to get extension by type in registry.

It is, once you have metadata.
But current code just downloads content directly, not knowing the type.
Like I wrote, additional step would have to be added -- 1st metadata, then download.

**Comment by dmvolod** [comment]
@alesj what can you suggest: extend `io.apicurio.registry.types.ArtifactType` with extension option or use own `ArtifactExtensionType` inside the maven plugin implementation?

**Comment by dmvolod** [comment]
Paused implementation, due to the same problem on master (1.3.1-SNAPSHOT) as described at #808

**Comment by alesj** [comment]
> @dmvolod what can you suggest: extend io.apicurio.registry.types.ArtifactType with extension option or use own ArtifactExtensionType inside the maven plugin implementation?

I would leave this to the plugin -- to know the extension string, as that's only relevant there, imho

**Comment by dmvolod** [comment]
> @dmvolod
> 
> > what can you suggest: extend io.apicurio.registry.types.ArtifactType with extension option or use own ArtifactExtensionType inside the maven plugin implementation?
> 
> I would leave this to the plugin -- to know the extension string, as that's only relevant there, imho
> So a simple mapping should be fine: ArtifactType --> extension string

Thanks, @alesj did this, but stopping with Jersey error.

**Comment by dmvolod** [comment]
@alesj , @EricWittmann it's very strange, but adding new maven-plugin capabilities and calling simple 
`ArtifactMetaData artifactMetaData = getClient().getArtifactMetaData(id);` got following error
```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:129)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:96)
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at io.apicurio.registry.client.RegistryRestClientImpl.parseResponseBody(RegistryRestClientImpl.java:325)
	at io.apicurio.registry.client.RegistryRestClientImpl.getLatestArtifact(RegistryRestClientImpl.java:133)
	at io.apicurio.registry.maven.DownloadRegistryMojo.executeInternal(DownloadRegistryMojo.java:122)
```

**Comment by EricWittmann** [comment]
Here is a workaround for the CNFE problem:  https://github.com/Apicurio/apicurio-registry/issues/702#issuecomment-688248363

We'll work on improving this.

**Comment by dmvolod** [comment]
Thanks, @EricWittmann
