### ISSUE TITLE
Versioned delete of artifacts and metadata can leave orphan records

### ISSUE THREAD

**Issue by dmvolod** [Apicurio/apicurio-registry#824]
`deleteArtifactVersionMetaData` and `deleteArtifactVersion` can leave orphan records in 
- META: when artifact with version is deleted
- ARTIFACTS: when metadata with version is deleted
- RULES: when latest artifact or metadata is deleted

This is true for JPA storage only

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-registry/pull/822

**Comment by EricWittmann** [comment]
This will be taken care of in the new/updated SQL storage we're working on now.

**Comment by dmvolod** [comment]
In this case we can close this issue, I think
