### ISSUE TITLE
Able to set additional Java properties for Docker images

### ISSUE THREAD

**Issue by dmvolod** [Apicurio/apicurio-registry#829]
It would be nice to have extra java options which will concatenated with predefined Java options to be able provide custom Java parameters. This applicable for all standards Java and native images.
This case can be implemented within custom build process #67

**Comment by EricWittmann** [comment]
Can you give some concrete examples of what you mean?  What sorts of options are you looking for?

**Comment by dmvolod** [comment]
Yes, sure.
This can be useful for setup any options without explicitly defining env variables or set it in the application.properties file, i.e.
-Dregistry.streams.topology.storage.topic=foobar

**Comment by EricWittmann** [comment]
Ah OK that's what I was thinking too.  I think the solution here is to leverage the Quarkus runtime application.properties file as documented here:  https://quarkus.io/guides/config#overriding-properties-at-runtime

Specifically option (4):

![image](https://user-images.githubusercontent.com/1890703/93337447-25b7b280-f7f7-11ea-88f4-ce42a9b7f106.png)

**Comment by EricWittmann** [comment]
I've been meaning to try this for e.g. SSL support.  But it's a powerful option for configuring runtime properties.  Even when using the docker image, users can create a local file and then `--mount` (bind) that file to the right location in the docker image so that the application picks it up.

**Comment by dmvolod** [comment]
Yes, agreed. The operator should utilize this option for configuring any required properties rather than ask for changing pre-defined file.

**Comment by EricWittmann** [comment]
@jsenko Hey what is the status of this in the operator?

**Comment by EricWittmann** [comment]
@jsenko Any thoughts on this for 2.0?

**Comment by jsenko** [comment]
With the latest dev version of the Operator, you can set an env. variable in the CRD called `JAVA_OPTIONS`.
