### ISSUE TITLE
Registry Rest Client closeable?

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#870]
When using the Registry Rest client in a standalone java application, I think I am seeing that the OK http client is keeping the application from completing.  Even after `main()` has completed, the app does not terminate.  I'm seeing these threads:

![image](https://user-images.githubusercontent.com/1890703/94016727-7e99c480-fd7c-11ea-8e18-6d682824ebe9.png)

I may be wrong and something else is keeping the app from terminating, but I can't look into it just now so I'm opening this ticket. :)

**Comment by tagarr** [comment]
I'm also seeing this, it does close but only after some time maybe like a minute

**Comment by EricWittmann** [comment]
The OK http docs seem to indicate you can close resources if you really want to, but that it is unnecessary.  And that e.g. connections will be reaped after some period of inactivity.  Which might be fine when using it on a server, but not as a client java app.

**Comment by EricWittmann** [comment]
@carlesarnal This should be high priority I think.
