### ISSUE TITLE
Support disabling Auth entirely

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#900]
@carlesarnal there may be a simple config property to disable auth without producing another image.  See the discussion here:

https://groups.google.com/g/quarkus-dev/c/isGqZvY829g/m/BNerQvSRAQAJ

**Comment by carlesarnal** [comment]
Hi @EricWittmann, I've tested this and it worked perfectly. Using the already existing env var `QUARKUS_OIDC_TENANT_ENABLED` we are able to enable/disable the auth feature for the backend side. Now we need to implement a mechanism for the frontend, I guess that it should be based on the configuration that the frontend gets from the backend. Thanks for the hint!

**Comment by EricWittmann** [comment]
OK let's use this GitHub issue for the UI changes as well.

**Comment by carlesarnal** [comment]
Fixed by #1032
