### ISSUE TITLE
Document the new AuthN/Z options

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#901]
We will soon have authentication/authorization support in the registry (version 2.0).  We'll need to update the documentation to include information about how to configure it.

**Comment by carlesarnal** [comment]
The auth implementation is based on Quarkus standards, so we should follow this documentation in order to provide ours: 

- https://quarkus.io/guides/security-openid-connect
- https://quarkus.io/guides/security-openid-connect-web-authentication

**Comment by EricWittmann** [comment]
Agreed - we need to have a documentation page about enabling Authentication and basic configuration, then refer to the Quarkus docs for additional custom config.
