### ISSUE TITLE
Ensure that Health, Metrics, and OpenAPI endpoints are not protected by auth (by default)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#902]
We'll want these endpoints to be unprotected, particularly so that k8s/OpenShift can properly monitor the application.

**Comment by carlesarnal** [comment]
Just some thoughts on this. Since most of the auth properties are overridable at runtime, there is no way so we can ensure those endpoints to be opened. We can provide some defaults, but we cannot ensure it.

**Comment by EricWittmann** [comment]
That's fine - default values for those endpoints should be open.  That's good enough.  If someone overrides them and messes up their own k8s deployment, that's on them.

**Comment by carlesarnal** [comment]
Closed by [924](https://github.com/Apicurio/apicurio-registry/pull/924)
