### ISSUE TITLE
Ensure that auth can be configured to support BASIC auth

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#903]
We'll definitely want to able to accept a bearer token as the typical way that e.g. the UI will provide credentials when invoking the API.  However, we should also ensure that BASIC auth works (or can be configured to work), as that is a more convenient way to provide auth credentials e.g. in DEV mode.

**Comment by carlesarnal** [comment]
For the DEV mode, this is possible right now using [this](https://quarkus.io/guides/security-built-in-authentication#basic-auth). If we want to support both, bearer and basic against keycloak at the same time, then that's not possible in Quarkus right now.

**Comment by antonmry** [comment]
it would be great to have basic auth without keycloak, even for PROD cases. Keycloak is a quite big dependency for some projects

**Comment by carlesarnal** [comment]
Hello @antonmry, yes, I'm aware of that. The intention of my comment was to made it clear that it's not possible to use both bearer and basic at the same time in a Quarkus + Keycloak deploymeny. If we remove Keycloak from the equation, then it's perfectly ok to use basic auth using Quarkus features like the ones described in the link above.
