### ISSUE TITLE
Ensure that auth config (e.g. keycloak server url) is pushed into UI app

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#904]
The UI app should be configured with the keycloak server URL, realm, and other relevant configuration properties by having that information pushed to it via the dynamic config servlet:

https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/java/io/apicurio/registry/ui/servlets/ConfigJsServlet.java

This allows the auth configuration properties used by the API layer to be shared by the UI - we don't want to configure them separately.

This may already be working...

**Comment by carlesarnal** [comment]
@EricWittmann, this isn't working right now, I guess we can accept it.

**Comment by carlesarnal** [comment]
Fixed by #926
