### ISSUE TITLE
Create an integration test specifically for Auth functionality

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#910]
We should create an auth integration test that uses Keycloak and Registry together and ensures that authentication rules are enforced.  So it should try various scenarios:

* User A attempts to perform Action X without appropriate permissions (fail)
* User B attempts to perform Action X with appropriate permissions (success)
* Attempt to make a protected API call without credentials fails
* Attempt to call e.g. /health without credentials succeeds
* Simple serdes test configured with credentials (success/fail depending on existence of configured credentials)

And I'm sure there are more auth scenarios we can add to this list over time.

**Comment by carlesarnal** [comment]
@famartinrh I'm happy with the tests that you added in #1102. Unless you have any objections I think we can close this.

**Comment by carlesarnal** [comment]
Or maybe we should add another test for the serdes scenario.

**Comment by famartinrh** [comment]
yes, there are still some testcases missing, I'll prefer to leave this open

**Comment by EricWittmann** [comment]
@famartinrh Confirming that this issue should remain open?

**Comment by famartinrh** [comment]
This can be closed, the remaining test case has been implemented in this PR #1174
