### ISSUE TITLE
Update REST client to throw specific exceptions for known failures

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#916]
Right now the client throws WebApplicationExceptions - instead it should throw specific exceptions for the common failures.  For example:

* ConnectException (could not connect to server)
* NotFoundException (http 404 error)
* AlreadyExistsException (http 409 error)
* ServerError (http 500 error)

Check the API description or jax-rs interfaces for more well-known errors.

**Comment by carlesarnal** [comment]
I think this is duplicated [here](https://github.com/Apicurio/apicurio-registry/issues/847) unless you're referring to update both the old and the new client (since the old one is also throwing `WebApplicationException`).

**Comment by carlesarnal** [comment]
@EricWittmann, let me know if you want me to take a look at this.

**Comment by EricWittmann** [comment]
Go for it!
