### ISSUE TITLE
ccompat API - compatibility vs compatibilityLevel

### ISSUE THREAD

**Issue by bobrossthepainter** [Apicurio/apicurio-registry#927]
Hi 
first off thanks for this great project.

We encountered some issue, when trying to communicate with the ccompat API (via AKHQ). It seems that there has been some change in the [CompatibilityLevelDto](https://github.com/Apicurio/apicurio-registry/blob/230007ceadfcd35413b680d2c878ceb2b497e2eb/app/src/main/java/io/apicurio/registry/ccompat/dto/CompatibilityLevelDto.java#L51). 

When the GET config API's are called, see Conluent API-Doc [get--config](https://docs.confluent.io/current/schema-registry/develop/api.html#get--config) and 
[get--config-subject](https://docs.confluent.io/current/schema-registry/develop/api.html#get--config-(string-%20subject)),
the returned Json must contain the key `compatibilityLevel` but in fact it contains `compatibility` instead. 
The `CompatibilityLevelDto` seems a bit undecided, because the attribute and getter-method annotations, which specify the actual Json key-attribute, differ.
So this seems to be a bug.

But be aware, the confluent API (PUT) for changing the actual compatibility Level expects the key to be `compatibility` [see API doc](https://docs.confluent.io/current/schema-registry/develop/api.html#put--config-(string-%20subject))

I hope, I have read the APIs and the code correctly and am looking forward to your feedback.

Thanks and best regards
Rob

**Comment by axblu** [comment]
We just ran into the same issue today using AKHQ, too.

**Comment by EricWittmann** [comment]
I think this PR already addresses this issue: 

https://github.com/Apicurio/apicurio-registry/pull/867

That will be included in the next release.

**Comment by bobrossthepainter** [comment]
Hi @EricWittmann , I fear that the change in #867 tackled the problem not quite right. When you take a look at the changes in  the lines 51 and 56 of the `CompatibilityLevelDto`, you can see that the json representation (jackson annotations) is contradicting within the class.
For the mentioned confluent API methods `compatibilityLevel` should be returned, which it isn't. I also tried using the `latest-snapshot` build from dockerhub and it didn't work.
Our current solution is that we build the image ourselves with the corrected annotation.

**Comment by EricWittmann** [comment]
OK thanks - I'll take a look and get this fixed.

**Comment by axblu** [comment]
@bobrossthepainter 
Would it be possible for you to provide your fix with the corrected annotation as a PR? Thanks!

**Comment by carlesarnal** [comment]
Fixed by #1044
