### ISSUE TITLE
SQL Injection vulnerability 

### ISSUE THREAD

**Issue by adiohana** [Apicurio/apicurio-registry#930]
We use Apicurio as our schema registry in Intuit. We currently use version 1.2.3.Final and everything is fine.
We want to use the latest version and looks like on version 1.3.1.Final a new vulnerability was introduced related to this 
[commit](https://github.com/Apicurio/apicurio-registry/commit/70d4bb99c6f8065c0942783d01634dcab6591638)

We are using [Contrast](https://www.contrastsecurity.com/) to scan our jars at runtime and identify security threats and while working with the latest version we found new SQL Injection vulnerabilities. 

I can't share the full report because its for internal use only but I can share the following details:

```
SQL Injection from \"artifactId\" URI Parameter on \"/api/artifacts/Test/meta\" page

...which was accessed within the following code:
io.apicurio.registry.storage.impl.jpa.JPARegistryStorage#_getArtifact(), line 191

...and ended up in this database query:
...s a INNER JOIN (SELECT artifact_id, max(version) AS MaxVersion FROM meta WHERE artifact_id = '__internal_wWzUjhPHxpml' AND key = 'state' AND value IN ('ENABLED','DISABLED','DEPRECATED') GROUP BY artifact_id) b ON a....
```

Let me know what you think

**Comment by EricWittmann** [comment]
Oh man - that's an obvious injection vector that I clearly missed during the code review.  Thanks for reporting this and offering to fix it.  The good news is that we're actually replacing the JPA implementation with something new (still working out the details).  But we should definitely get a fix in for this even though the whole thing will be going away shortly.

**Comment by EricWittmann** [comment]
@adiohana we have recently replaced the JPA storage impl with a SQL one.  If your scans find anything wrong please let us know!

**Comment by adiohana** [comment]
@EricWittmann  any estimation when this fix will be in the release version of the Docker image?

**Comment by EricWittmann** [comment]
This change was made to `master` and I didn't have a plan to port it over to the `1.3.x` branch.  But perhaps that was a mistake and it should be ported.  If you wanted to open a new PR against the `1.3.x` branch with this commit cherry-picked that would be awesome.  If not that's fine too, I can do it later.

The next major release `2.0.0.Final` has replaced the entire module, so it's not relevant.  Oh I mentioned that already.
