### ISSUE TITLE
Add mongodb support

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-registry#935]
Hello folks, many thanks for your gigantic contribution to open source. Can you please consider using MongoDB as a backend in future?

**Comment by carlesarnal** [comment]
Hi @tillias, thanks for your interest. Could you please add a few arguments of why we should consider MongoDB as a storage variant? I'm not arguing against it, just asking to start a healthy discussion. 

Could be even better if you also add some arguments on why you choose MongoDB vs other NoSQL solutions.

**Comment by tillias** [comment]
To be honest there are quite a few common cloud setups, where you don't have any relational db at all. Also with it's cloud Atlas option it is the easiest hassle-free nosql solution on the market. Also out of the 3 major vendors (Cassandra, MongoDB and HBase) it is the easiest to use and has top notch commercial support if you're going prod.

**Comment by EricWittmann** [comment]
I very much like the idea but honestly this would need to be a community effort - I don't anticipate enough interest internally to push this up on the priority list.

**Comment by tillias** [comment]
Agreed, do you have any documentation available, which interfaces should be implemented? I have checked https://github.com/Apicurio/apicurio-registry/tree/master/storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa but it looks like a separate assembly with parent set to apicurio-registry. How you plug different data providers into it?

**Comment by carlesarnal** [comment]
[This](https://github.com/Apicurio/apicurio-registry/blob/399487f37d15fab57fc19c174add9d7323fd6e31/app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java#L42) is the interface that should be implemented. We add the apropiate data provider by using profiles, [here](https://github.com/Apicurio/apicurio-registry/blob/399487f37d15fab57fc19c174add9d7323fd6e31/README.md#build-options) you have it documented.

**Comment by carlesarnal** [comment]
@tillias, let me know if you're interested in this, otherwise, I could try to find someone interested in contributing.

**Comment by tillias** [comment]
@carlesarnal please go ahead, I'm not planning stating it at least couple of weeks.

**Comment by carlesarnal** [comment]
Closing as we do not have the resources to add more storage variants and apparently there is no community interest.
