### ISSUE TITLE
Enhance search API to support query by properties

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#949]
Now that the user can add custom properties to the artifact and version meta-data, we need to have a way to search for artifacts by that information.  This requires the following changes:

* REST API - search must support key-value queries
* UI - allow the user to query by key-value
* Storage layer - storages must support querying by key-value

**Comment by vvilerio** [comment]
Hello,
for our business needs, I am currently working on implementing ElasticSearch Storage to improve the search feature of Apicurio-registry. It would be interesting if I took care this issue.

**Comment by EricWittmann** [comment]
We'd be very happy to have a contribution!

**Comment by carlesarnal** [comment]
Go ahead @vvilerio, contribution more than welcome!

**Comment by vvilerio** [comment]
Implementing ElasticSearch Storage : Work In Progress...

**Comment by EricWittmann** [comment]
This is done:  artifacts, versions, and groups can all be searched for by using the v3 "labels" (which are key-value).
