### ISSUE TITLE
Add tests and better UI handling of Artifact ID with special characters

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#973]
It's possible to create an artifact with artifactId containing slashes but at the moment of queriying it it's not found because the slash collides with the REST API paths...

I suggest to simply validate the artifactId and don't allow for special characters such as slashes

```
$ http :8080/api/artifacts X-Registry-ArtifactId:io.famartin.new-order/v1beta1 < ./new-order-schema.json
HTTP/1.1 200 OK
Cache-control: no-cache, no-store, must-revalidate
Content-Length: 148
Content-Type: application/json
Date: Mon, 02 Nov 2020 12:08:56 GMT
Expires: Sun, 01 Nov 2020 12:08:56 GMT
Pragma: no-cache

{
    "createdOn": 1604318936664,
    "globalId": 1,
    "id": "io.famartin.new-order/v1beta1",
    "modifiedOn": 1604318936664,
    "state": "ENABLED",
    "type": "JSON",
    "version": 1
}

$ http :8080/api/artifacts/io.famartin.new-order/v1beta1
HTTP/1.1 404 Not Found
Cache-control: public, max-age=31536000
Content-Length: 0
Content-Type: application/json
Date: Mon, 02 Nov 2020 12:09:13 GMT
Expires: Tue, 02 Nov 2021 12:09:13 GMT

```

**Comment by EricWittmann** [comment]
You have URL encode the Artifact ID, but it works fine if you do.  I'm not in favor of limiting the characters allowed - instead I'm in favor of testing to make sure other characters work as long as they are properly encoded in the URL.  Here is an example from the UI:

![image](https://user-images.githubusercontent.com/1890703/98013981-11d90780-1dc9-11eb-9ba9-df3ce869065e.png)

![image](https://user-images.githubusercontent.com/1890703/98013944-0685dc00-1dc9-11eb-8d17-b77ac3371a17.png)

It is quite possible that the UI doesn't handle EVERY weird character possible - so it would be good to test that.

In particular, I think that `/` will be likely used in a naming convention, at least until we have Artifact Groupings implemented....and maybe even after.   A common pattern in e.g. npmjs.com is to group modules by convention.  So you'll often see things like `@patternfly/module-1` and `@patternfly/module-2` as the naming convention for npm modules, even though npmjs.com doesn't support groupings.

**Comment by EricWittmann** [comment]
Thoughts from @Apicurio/developers or @Apicurio/ibm-developers ?

**Comment by alesj** [comment]
Yeah, that makes sense.

**Comment by famartinrh** [comment]
my bad on that, and agree on adding some testing of special characters handling, I think this could be closed

**Comment by EricWittmann** [comment]
After testing a bit more in the UI, I definitely was able to find some characters that broke things.  So will def. need some testing on this.

**Comment by carlesarnal** [comment]
Agree with @EricWittmann. I'm not in favour of limiting the valid characters for the `artifactId`.

**Comment by EricWittmann** [comment]
@famartinrh I've renamed this issue so it's a task to add more tests and also improve UI handling (maybe should be two issues) rather than closing it.
